### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lkmokadam** [singularityhub/singularityhub.github.io#100]
## Link to Container Collection Log, Build, or Collection (in that order)

Write here.

### Behavior when Building Locally

Write here.

### Error on Singularity Hub

Write here.

### What do you think is going on?

Write here.

**Comment by vsoch** [comment]
Good thing I can read your mind, the robots have a log that you can look at to figure out what the error is. I see several, so that is where to start. Congrats on posting issue #100! You win a cookie! :cookie: 

https://singularity-hub.org/containers/1460/log
