### ISSUE TITLE
Lost connection from github

### ISSUE THREAD

**Issue by honwaileong** [singularityhub/singularityhub.github.io#103]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/502

### Behavior when Building Locally

No auto build of Singularity detected. 

### Error on Singularity Hub

None. 

### What do you think is going on?

I accidentally screwed up some settings in my github repository, manually removing some OAuth apps in github. As a result, when I login to singularity-hub, I no longer could link up my github repository to Singularity-hub. I tried to manually setup a webhooks for the repository, but I don't know what the secret key is, so I'm kind of stuck. Is there a way for me to recover this? Could you reset it?

**Comment by vsoch** [comment]
If you removed the Oauth, then you essentially deleted your account. You need to start from scratch - make sure to log out from the browser, log in fresh to grant permission, and then try the build again.

**Comment by honwaileong** [comment]
I tried login fresh and didn't work for the first time. I tried again and it is working now. Thanks for your prompt reply.
