### ISSUE TITLE
tag display in container collection

### ISSUE THREAD

**Issue by shahzebsiddiqui** [singularityhub/singularityhub.github.io#105]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/143 

I would like to have a column ``tag`` that shows the image tag since I am building multiple containers in a collection that represent different HPC application. This would be more intuitive than to click inside each container image to see the tag.

**Comment by vsoch** [comment]
See the issue linked above (closed) for more detail and screenshots - this issue is still open and represented here (#105)

**Comment by vsoch** [comment]
Done! Please check your respective collections and let me know if you like the change. The "branch" column was largely useless so I added tag there, and it already feels much more useful :)

![image](https://user-images.githubusercontent.com/814322/36695518-96ddad92-1b0f-11e8-8a8e-a5ac3f81c83a.png)


Apologies for the crappy screen shot - my laptop is struggling, lol.

**Comment by shahzebsiddiqui** [comment]
@vsoch  it looks pretty good for starters I think we can close this task and get feedback from community. Another minor thing is why tag name is getting lower case. Check my files in https://github.com/shahzebsiddiqui/eb-singularity/tree/eb_images/centos/7.3.1611 and the corresponding containers in SHUB.

I tried following the documentation by using Singularity.<TAG-NAME> and it does not reflect this same behavior in SHUB.

For instance https://github.com/shahzebsiddiqui/eb-singularity/blob/eb_images/centos/7.3.1611/g/GCCcore/Singularity.GCCcore-5.4.0 translates to gcccore-5.4.0 as the tag. See https://www.singularity-hub.org/containers/1452/log 

I am not sure if container tags are case sensitive in singularity. I would presume that tag GCC and gcc are two different tags and two separate containers.

**Comment by vsoch** [comment]
Thanks! If you look at Docker Hub (and others) it's custom to make all lowercase - it generally decreases chance for error if the user asks for the wrong name.  https://github.com/docker/compose/issues/1416 I think it looks better too :)
