### ISSUE TITLE
Permission issues with administrative/member access on GitHub 

### ISSUE THREAD

**Issue by apeltzer** [singularityhub/singularityhub.github.io#107]
### Error on Singularity Hub
When clicking on "add new collection" and selecting a project in our organization that was not initially created from me, I "turn the project on" and click on submit and get back to the listing of all my collections. There is no new project created, unfortunately.

### What do you think is going on?

We got this fixed by setting my access permissions to "administrator" after being just a "member" when this happened. This fixed the issue. I'd expect the hub not showing repositories that I dont have the permissions on to show up in my selectable "collections view".

**Comment by vsoch** [comment]
Thanks @apeltzer ! To add some more comments, right now shub is showing all repos that a user has membership for, but this doesn't always give write permission to create webhooks. See this table here https://help.github.com/articles/repository-permission-levels-for-an-organization/ about permission needed for webhooks is to change "settings" (admin or owner).

**Comment by vsoch** [comment]
@apeltzer is this still an issue?

**Comment by apeltzer** [comment]
Didn't try as we're not using SH at the moment anymore...

**Comment by vsoch** [comment]
No worries, I'll close the issue then.
