### ISSUE TITLE
Make full uri and recipe visible upon hover or smth like that

### ISSUE THREAD

**Issue by yarikoptic** [singularityhub/singularityhub.github.io#108]
## Link to Container Collection Log, Build, or Collection (in that order)

when building from github receipes, uri might get lengthy and if there is also tags, they might all be truncated, so it is impossible to see which entry is actually which, see e.g. https://www.singularity-hub.org/collections/654
![and here is a webshot](http://www.onerussian.com/tmp/sing-cut.png)

So if at least I could figure out who is who by hovering over the row/column and getting some tooltip view of the full value, would be cool

**Comment by vsoch** [comment]
Totally agree! This is repeat of #105 so I'll close here. I can definitely do these fixes when some free time opens up, just a bit busy. Thanks @yarikoptic !

**Comment by vsoch** [comment]
oh heck, I can add a quick tooltip! Give me a few minutes.

**Comment by vsoch** [comment]
And now I feel better about closing this because it's actually fixed :) Your wish for a tag column... granted!

**Comment by vsoch** [comment]
...silly wabbit, tags are for kids!

**Comment by yarikoptic** [comment]
Gy, thanks!
But checkout mobile view... Even in a good one https://www.singularity-hub.org/collections/39 doesn't look that good :-/

**Comment by vsoch** [comment]
Yes, we know I'm not a web developer, and I only do things on computers. If it's possible to pull and interact with containers, then I'll more quickly prioritize this :)  For now you will have to endure the terror!

**Comment by yarikoptic** [comment]
ah ok, no problem.  I just discovered it because checked the "fix" while on the phone
