### ISSUE TITLE
build dying without much feedback

### ISSUE THREAD

**Issue by baberlevi** [singularityhub/singularityhub.github.io#113]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/containers/2019/log

### Behavior when Building Locally

Build completes

### Error on Singularity Hub

`Return value of 137`

### What do you think is going on?

No idea. This did take a long time to build locally, but otherwise was ok.

**Comment by vsoch** [comment]
The log indicates it was killed, so it took too long given the limits of shub building. I would recommend you separate the build into components and then use one of the images as a base, and build the other onto it. Try to keep it under 2 hours, or you will get Killed. Give that a go, and please share an update!

**Comment by baberlevi** [comment]
Layers are working. Thanks
