### ISSUE TITLE
Webhook isn't working or can't setup Collection.

### ISSUE THREAD

**Issue by JohnLangford** [singularityhub/singularityhub.github.io#115]
## Link to Container Collection Log, Build, or Collection (in that order)

I want to setup Vowpal Wabbit (https://github.com/JohnLangford/vowpal_wabbit ), but am having some configuration problem in setting things up.  

### Behavior when Building Locally

N/A.

### Error on Singularity Hub

I can't seem to add VW as a Collection no matter what I do in the singularity account.   See the detailed discussion here: https://github.com/JohnLangford/vowpal_wabbit/issues/1410 (bottom comment)

### What do you think is going on? 

There's either something broken in Singularity or something subtle about configuration.

**Comment by vsoch** [comment]
There were a few bugs I fixed this morning, could you try deleting the collection (in Singularity hub) and reconnecting? I should be alerted again via the server logs if an issue comes up!

**Comment by JohnLangford** [comment]
I don't think I have a collection to delete.

"My Collections" still leads to a mostly empty page with a "My Container
Collections" header followed by a "Add a Collection" button.

**Comment by vsoch** [comment]
Can you come on Gitter to chat? It will be easier to interactively look into this! --> https://gitter.im/singularityhub/lobby

**Comment by vsoch** [comment]
okay, so I don't see that you have any collections:

```
In [3]: user=User.objects.get(username='JohnLangford')

$ user
<User: JohnLangford>
$ user.collection_set.all()
<QuerySet []>
```
so that first page showing empty makes sense. If you are getting an error that the webhook already exists, it likely does and since Singularity Hub didn't do the deleting (because there was some bug) it still might exist with your collection (in Github settings). Could you look there?

**Comment by JohnLangford** [comment]
Adding from gitter:
Apparently, there are many webhooks on github (not sure why they are
multiplying).
I deleted all webhooks in singularity and then did Add a Collection ->
click on vowpal_wabbit -> Submit Query. The result on singularityhub was:
Errors: Hook already exists on this repository
The result on github was a 404 in the webhook with (I believe)
Singularityhub saying: {"status": "error", "message": "Collection not
found"}

**Comment by vsoch** [comment]
Do you still have this issue @JohnLangford ?

**Comment by JohnLangford** [comment]
No, but it looks like there may be a separate issue which has arisen.  

@jackgerrits maybe something broke with the shift to cmake?

**Comment by jackgerrits** [comment]
Would you be able to point me to where to look into this?

**Comment by JohnLangford** [comment]
When I look into the github webhooks it says the last successful push was
11/20 and the last push on 11/30 the error message:

{"status": "error", "message": "This branch is not actively building.
See https://www.singularity-hub.org/collections/740/branches/edit"}

This persists across redelivery.

Looking from the Singularity side, I see a container built on 7/5.

The relevant code is in the /singularity directory.

-John

**Comment by vsoch** [comment]
What branch are you trying to build, and is it turned on for building?

**Comment by JohnLangford** [comment]
The master branch, and yes.

-John

**Comment by vsoch** [comment]
I'm not sure what has been messed up - the webhook seems okay, but possibly pointing to the wrong collection? How should I know what you have changed / edited / deleted?

Maybe try setting up a fresh repository with a file to test? And not mess around with it?

**Comment by vsoch** [comment]
Can you please check on the exact branch that is associated with that webhook message? It's likely that it wasn't from master (and the message is correct). Also note that in order for the build to happen, from master, you need to have changes to your recipe file (a file with the same date as previous will not trigger).

**Comment by JohnLangford** [comment]
You are correct.  The payload has: "ref": "refs/heads/jackgerrits-patch-2",
so we aren't triggering things properly.

I did run into an issue in singularity though.  Looking at:
https://www.singularity-hub.org/containers/3410/view results in a blue
banner that says:

   We had an issue retrieving files for this container! Try another build?

   -John

**Comment by vsoch** [comment]
If the dumps of metadata are too big to send to the server, they aren't sent, so that's why you see this message. If you want to try different kinds of triggers there are also deploy and manual (build based on selecting a commit in the interface).
