### ISSUE TITLE
Keeps asking me to login

### ISSUE THREAD

**Issue by nickjer** [singularityhub/singularityhub.github.io#117]
I am not entirely sure where to post this issue, so feel free to point me in the right direction if this is the wrong place.

I am pretty lazy and so I regularly type in the url https://singularity-hub.org in my browser (note that I do not type out `www`). I login with my GitHub credentials successfully, but then I notice after I login it redirects me to https://www.singularity-hub.org (note the `www` subdomain) and sets a `sessionid` cookie with the domain set to `www.singularity-hub.org`.

Now when I open up a new tab and browse to https://singularity-hub.org it asks me to login again even though I am currently logged in.

A couple of possible fixes:

- redirect all `singularity-hub.org` requests to `www.singularity-hub.org`
- or set `sessionid` cookie domain to `singularity-hub.org`

As an aside, from a security perspective one suggestion would be to set the `sessionid` cookie's secure flag, to prevent the cookie from being passed in clear text. Although this would break user sessions that don't use HTTP over SSL.

**Comment by vsoch** [comment]
Hey @nickjer! You posted in the right spot :)  This is a weird problem because the redirect URL has to be one thing that cannot change, but as a user you could be coming from either. We had problems for a really long time just with both the www and not working with the certificates (I had to register them both from a custom file, it's pretty cool) so I was happy that it was working, period.

This is the case where those two things have the subtle difference. I noticed this too, thought about it, and figured it didn't hurt to sort of automatically log me out. You can imagine a user always going to the www. version and not having issue.

That said, I think that this should be addressed, because you shouldn't have this issue. Your suggestions are great, and I think your intuition about better handling the url via the sessionid might be good to try.  I likely won't be able to get to this asap, lots of things going on, but I'll keep the issue open and will get to it the next time I need to fuss with the server.

**Comment by nickjer** [comment]
Great, no rush. I can definitely use the `www.` subdomain in the meantime. Thanks!

**Comment by vsoch** [comment]
hey @nickjer I'm still pretty annoyed by this particular issue - which of your two suggestions do you think is the better of the two, and how would you recommend doing it?

**Comment by nickjer** [comment]
Simplest solution is the first one. Just redirect the "naked" domain (`singularity-hub.org`) to the `www` subdomain.

I am not entirely show what server or load balancer you are using to serve the site (e.g., Apache, NGINX, or other solution), but you should be able to find documentation on how to set up the redirect as this is a fairly common problem.

**Comment by vsoch** [comment]
hey @nickjer can I ask for your help? I tried a standard solution I found, but it didn't seem to make a difference. Here are relevant sections for nginx.conf

```
server {
    server_name www.singularity-hub.org;
    return 301 $scheme://singularity-hub.org$request_uri;
}

server {
  listen                *:80;
  server_name           singularity-hub.org;

...
}

server {

        listen 443;
        server_name           singularity-hub.org;

...
        location / {
            include /etc/nginx/uwsgi_params.par;
            uwsgi_pass uwsgi:3031;
        }

}
```

**Comment by vsoch** [comment]
okay, so with the configuration that I shared (plus changing the url on the server to not have www) this might be closer to working. Give it a go and let me know!

**Comment by nickjer** [comment]
Are you trying to redirect the `www` subdomain to the "naked domain"? I though you wanted it the other way around.

One possibility is:

```nginx
server {
  listen 80;
  server_name singularity-hub.org www.singularity-hub.org;
  return 301 https://www.singularity-hub.org$request_uri;
}

server {
  listen 443 ssl;
  server_name singularity-hub.org;
  return 301 https://www.singularity-hub.org$request_uri;

  # you might need SSL certs here
}

server {
  # your original server config here
}
```

**Comment by nickjer** [comment]
With your latest change I only get the redirect for `http` requests.

**Comment by vsoch** [comment]
I was trying to redirect www.singularity-hub.org to naked singularity-hub.org. Should it be the other way around? I can try the configuration that you shared if you think having www. is better, and I'll switch back the GitHub response URLs too.

**Comment by vsoch** [comment]
How can I have two blocks to each listen on 80 and 443? Wouldn't that issue an error?

**Comment by vsoch** [comment]
Yeah I just tried adding singularity-hub.org to the first block, the name conflicts:

```bash
nginx_1   | nginx: [warn] conflicting server name "singularity-hub.org" on 0.0.0.0:80, ignored
```
How could the other server blocks (where you listed  "your original server config here" not have a server name?

**Comment by nickjer** [comment]
Can you show me the three blocks you have now? Also, I am fine taking this into an email conversation,

**Comment by vsoch** [comment]
So happy to close this! Your help was amazing @nickjer thank you so much!

**Comment by vsoch** [comment]
Also, building will likely be opened up sometime today - right now you'll get a message that it's disabled.
