### ISSUE TITLE
Failed invoking the NEWUSER namespace runtime: Invalid argument

### ISSUE THREAD

**Issue by smoe** [singularityhub/singularityhub.github.io#119]
Dear @vsoch,

I installed singularity with conda and thought to follow the example deployment from https://github.com/singularityhub/singularityhub.github.io/wiki/Deploy

## Link to Container Collection Log, Build, or Collection (in that order)

$ singularity run shub://vsoch/hello-world
Progress |===================================| 100.0%
ERROR  : Failed invoking the NEWUSER namespace runtime: Invalid argument
ABORT  : Retval = 255
$ singularity --version
2.4.2-dist

### What do you think is going on?

Could it be a Python version thingy? It is 2.7 over that comes with conda.

Best,

Steffen

**Comment by vsoch** [comment]
If you are running this on your local machine then you should open the issue here https://www.github.com/singularityware/singularity/issues as it's an issue with Singularity (runtime) and not Singularity Hub. Thank you!

**Comment by smoe** [comment]
Thank you, @vsoch. Over at singularity I found this closed issue https://github.com/singularityware/singularity/issues/415 which basically says that I need to contact our system adminsitrator for the likely need of a system-wide installation as root.

**Comment by vsoch** [comment]
Awesome! Yeah it seems to be different at every place. When you've installed and used singularity once... you've installed and used singularity once, haha :)
