### ISSUE TITLE
Display of deeply nested folders

### ISSUE THREAD

**Issue by TormodLandet** [singularityhub/singularityhub.github.io#12]
The current visualization of files on https://singularity-hub.org/containers/XXX/view makes it impossible to see the contents of custom python site packages /usr/local/lib/python2.7/site-packages/* which can be interesting to see what Python packages are included in an image

Even when zooming to 80% or less the rightmost items disappear. This is true for all such deeply nested folders (Firefox, linux)

I do not consider this very important, just something to be aware of

**Comment by vsoch** [comment]
This is fixed and will be in the next release - see #40 I'm going to close this issue in favor of that one, thanks @TormodLandet !
