### ISSUE TITLE
Build status badge

### ISSUE THREAD

**Issue by mbhall88** [singularityhub/singularityhub.github.io#120]
I know there is a badge you can add to Github that links to your container(s) being hosted on Singularity Hub but I was wondering if there is a way to have a build passing/failing badge also (similar to something like travis CI). I had a look at the API for my containers but there doesn't seem to be any fields in the response JSON that could be used to judge this.  

Any thoughts?

## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/685

example of passing container: https://www.singularity-hub.org/containers/2227

### Behavior when Building Locally

N/A

### Error on Singularity Hub

N/A

**Comment by vsoch** [comment]
This would be a cool feature! Right now you would have to link to the collection page and view the button. I'll keep this in mind for a future update!
