### ISSUE TITLE
Singularity hub built images should contain a shub:// url for them in the metadata

### ISSUE THREAD

**Issue by yarikoptic** [singularityhub/singularityhub.github.io#122]
## Link to Container Collection Log, Build, or Collection (in that order)

ATM, having a local image file, it is not possible to figure out its "origin":

```shell
$> singularity inspect ./neurodebian-neurodebian-master-latest.simg 
{
    "org.label-schema.usage.singularity.deffile.bootstrap": "debootstrap",
    "org.label-schema.usage.singularity.deffile": "Singularity",
    "org.label-schema.schema-version": "1.0",
    "SINGULARITY_IMAGE_VERSION": "0.0.unknown",
    "org.label-schema.build-date": "Fri,_16_Mar_2018_14:00:48_+0000",
    "org.label-schema.usage.singularity.deffile.mirrorurl": "http://http.debian.net/debian/",
    "org.label-schema.usage.singularity.version": "2.4.1-feature-squashbuild-secbuild-2.4.1.g220f8e0",
    "org.label-schema.build-size": "5353MB",
    "org.label-schema.usage.singularity.deffile.osversion": "stretch"
}
```
May be the images generated on the singularity hub could contain some kind of "origin" notion with a URL and anything else necessary to it could later be pulled down again.
Q: May be it is possible to ask singularity hub for a particular image given its checksum?  related -- may be above json record could contain the "hub-md5sum" or alike?

**Comment by vsoch** [comment]
The build is up to Singularity, so if you want this to be present, add it as a label! And yes, you can pull based on the hash if you add --hash to the pull command with shub.

**Comment by yarikoptic** [comment]
> The build is up to Singularity, so if you want this to be present, add it as a label!

I am talking about images from others, which I might have pulled and renamed and have no recollection where I got it from.
In our case -- we want them for repronim project where we are trying to trace components (packages, repositories, etc) to collect enough information to compare them ("am I using the same components?)") and where possible to reinstall (do all the same git clone, apt-get install, ...).  Singularity image file seems to have no information about its origin, although it could easily be added while building on singularityhub since it has that information available.

> pull based on the hash if you add --hash

that one just renames the file to match the hash...  What I meant was to be able to pull it based on the hash:
```shell
$> singularity pull --hash shub://292bd27a43f924283e5913db342227fb
ERROR Cannot find image. Is your capitalization correct? 
```

**Comment by vsoch** [comment]
> I am talking about images from others, which I might have pulled and renamed and have no recollection where I got it from.
I would use Singularity Global Client then, it helps you with this management, eg:

```
 sregistry images | grep hub
8  January 14, 2018	remote	   [dockerhub]	continuumio/anaconda3:latest
9  January 14, 2018	remote	   [dockerhub]	continuumio/miniconda3:latest
13 January 15, 2018	local 	   [dockerhub]	library/centos:7@778c6f08ac8d6ef5ceaee9ce77ff7df9
19 January 23, 2018	local 	   [hub]	shahzebsiddiqui/eb-singularity:anaconda2-4.4.0@b761d1f2607f8e94c9250919d93d79d7
35 February 09, 2018	local 	   [hub]	vsoch/hello-world:latest@ed9755a0871f04db3e14971bec56a33f
```
Organization of your images I think is outside the scope of Singularity Hub.

that one just renames the file to match the hash... What I meant was to be able to pull it based on the hash:

> that one just renames the file to match the hash... What I meant was to be able to pull it based on the hash:

You have to provide the image uri, and then get a hash as a result. To pull a specific hash you would then provide the uri with @hash, e.g., see the examples in the table above.

**Comment by vsoch** [comment]
I'm not saying an ability to figure out the origin is a bad idea or feature, but it belongs with the build software, not Singularity Hub. It's not in Singularity Hub business to add extra metadata or otherwise mess around with the build file. It is (I believe) being added to Singularity version 3.0 image signing, and this would provide a complete signed image. As for the url, you are able to pull a full name and version url, in the format <repo>/<namespace>:<tag>@<hash> and then save it with Singularity Registry, and given that there are multiple ways to skin the cat here, I'm not convinced this is a pressing, dire need.
