### ISSUE TITLE
UI issue: collection page confusingly shows build status "..." when page width too small.

### ISSUE THREAD

**Issue by omsai** [singularityhub/singularityhub.github.io#124]
On Firefox 52.7.3 when the browser window width is 1435 pixels or smaller, the build "status" always shows "...".  I spent a day scratching my head not realizing whether or not my builds were submitting, couldn't check the logs, etc.

**Comment by omsai** [comment]
See https://www.singularity-hub.org/collections/913

**Comment by vsoch** [comment]
On Chrome: 
![image](https://user-images.githubusercontent.com/814322/38770409-cdf0811a-3fe0-11e8-96e7-bf5c223b8990.png)

and on Firefox:
![image](https://user-images.githubusercontent.com/814322/38770417-f449a918-3fe0-11e8-8416-a9e08f01ab54.png)

I don't quite understand the issue, could you show me?

**Comment by omsai** [comment]
Here are my screenshots (these are Xfce on Debian 9 and also on Gentoo):

Firefox 52.7.3 ESR (Debian 9)
![image](https://user-images.githubusercontent.com/166624/38772349-f975bf24-4023-11e8-864b-0a71587c1992.png)

Tor Browser 7.5.3 / Firefox 52.7.3 ESR (Debian 9)
![image](https://user-images.githubusercontent.com/166624/38772338-be7c15d0-4023-11e8-813a-20b9c9dfb63b.png)

Indeed, though the button does render on Chromium 64.0.3282.119 (Debian 9):

![image](https://user-images.githubusercontent.com/166624/38772362-391ffe5a-4024-11e8-8097-4f8e65c5ff8d.png)

**Comment by vsoch** [comment]
Can you look in the js console and see if the browser / adblock is blocking any scripts? Right click then inspect then console tab!

**Comment by omsai** [comment]
I think I neglected to mention that if I resize the window over the ~1435 pixels, then the button appears:
![image](https://user-images.githubusercontent.com/166624/38772445-5c2671ca-4026-11e8-9551-3837f26c0ef4.png)

The 3 extensions I have are Zotero, Privacy Badger and HTTPS Everywhere (disabling them didn't have an effect).  Nothing in the javascript output besides depreciation warnings, and no output additional output when I resize the window.  Could it be a CSS issue?  I'm looking at the Style Editor and the btn class definition in `style.css` but don't know what I'm looking for yet.

Are you able to replicate the issue by unpacking [tor browser](https://www.torproject.org/projects/torbrowser.html.en) on your system?  I wonder if it's specific to Firefox 52.7.3 ESR.

**Comment by omsai** [comment]
Some progress!  In the inspector rules if I add `overflow: visible` to the `<td>` properties I see the button, but it's not pretty:

![image](https://user-images.githubusercontent.com/166624/38772594-05b76b9c-402a-11e8-8530-51e408da2c93.png)

**Comment by vsoch** [comment]
Ah! I just got some intuition (I'm afk but can test this later!) I think there is a min-width of maybe 38 or something pixels on the button... what happens if you remove that attribute?

**Comment by omsai** [comment]
There is a `width: 130` on the button (element  / HTML tag itself), and removing that helps but only very slightly.  There doesn't seem to be a `min-width` present in the hierarchy and adding a low `min-width` also doesn't help.

**Comment by vsoch** [comment]
okay, replicated! Here is the issue replicated:

![image](https://user-images.githubusercontent.com/814322/38773005-600b7f20-4011-11e8-81e5-9d6fd26e3ca8.png)

And when I remove the width property, it shows up. 

![image](https://user-images.githubusercontent.com/814322/38773007-6b84fe4e-4011-11e8-8cec-9352685c9890.png)

Does this fix it for you as well? I am using `tor-browser-linux64-7.5.3_en-US.tar.xz`

**Comment by omsai** [comment]
Thanks for all your help so far!

Your suggestion is something I had tried, but you'll find if you shrink the window slightly more to <= 984 pixels, the button disappears instead of clipping gracefully as in your first set of screenshots you posted.  I feel the button disappearing is problematic because it effectively imposes a minimum window width requirement of 984 pixels, but removing `width: 130` is definitely better than the old 1435 pixel minimum window width!  Perhaps this is actually a limitation of this version of Firefox / CSS.

![image](https://user-images.githubusercontent.com/166624/38773206-7cf86c2c-4036-11e8-9dd8-16913c4c1e17.png)

**Comment by vsoch** [comment]
I can definitely make this fix for you, and it's at a loss of the buttons looking pretty on all pages that do have support for the width (because the buttons become unequal sizes). I don't think it's reasonable to jump through hoops to try and get it working under 900 or something pixels - Singularity Hub isn't intended to be used on mobile devices and I don't plan to invest (in the near future) investing a lot of time in that until the next complete revamping of the interface. Let me know if you want this adjustment, or if you can live with just using a larger browser window :)

**Comment by omsai** [comment]
I can live with the ~900 pixels.  My laptop screen isn't big enough for the 1400+ pixels!  Thanks again.

**Comment by vsoch** [comment]
okay please take a look! I just pushed the change.
