### ISSUE TITLE
Build fails with false negative

### ISSUE THREAD

**Issue by funkey** [singularityhub/singularityhub.github.io#127]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/containers/2661/log

### Behavior when Building Locally

Builds without errors

### Error on Singularity Hub

ERROR Return Code 1: b'Using container recipe deffile: /tmp/tmp2o7z1n2c/singularity/Singularity

### What do you think is going on?

No idea ;)

After the "error", the build continues and looks like it finishes successfully. However, the build is still marked as failed.

**Comment by vsoch** [comment]
There are several errors in the log, the first is close to the top:

```
/bin/cp: cannot stat \'gunpowder\': No such file or directory
```
Then you can see why it exits on 255:

```
+ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: \'requirements.txt\'
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the \'pip install --upgrade pip\' command.
\x1b[31mABORT: Aborting with RETVAL=255
```
This is not a False negative based on these observations.

**Comment by funkey** [comment]
You are absolutely right! I didn't look further after spotting the first "error". Thanks a lot!

**Comment by vsoch** [comment]
No worries! :O)
