### ISSUE TITLE
How to copy files from repository to Singularity image?

### ISSUE THREAD

**Issue by funkey** [singularityhub/singularityhub.github.io#128]
I would like the Singularity image to contain files that are in the repository that contains the recipe. 

Locally, I would just
```
%files
    lime_juice /src/guacamole/
```
which works provided that `lime_juice` is in `$PWD`, e.g., the root directory of the repository.

During the build of Singularity hub, however, the repository is checked out in a temporary directory
```
Cloning into '/tmp/tmpjj1f97hu'...
```
and `$PWD` is `/root/repo`. Other environment variables don't seem to give a hint where the repository resides:
```
+ env
USER=root
SINGULARITY_CHECKLEVEL=3
SHLVL=3
HOME=/root
SINGULARITY_CHECKTAGS=bootstrap
SINGULARITY_BUILDDEF=Singularity
SINGULARITY_STAGE2=1
SINGULARITY_version=2.4.1-feature-squashbuild-secbuild-2.4.1.g220f8e0
SINGULARITY_ENVIRONMENT=/.singularity.d/env/91-environment.sh
SINGULARITY_MESSAGELEVEL=1
_=/bin/sh
SINGULARITY_libexecdir=/usr/local/libexec
SINGULARITY_sysconfdir=/usr/local/etc
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
SINGULARITY_DEFFILE_FROM=tensorflow/tensorflow:1.7.0-gpu
SINGULARITY_CHECKS=no
LANG=C
SINGULARITY_IMAGE=/root/build
SINGULARITY_DEFFILE_BOOTSTRAP=docker
DEBIAN_FRONTEND=noninteractive
SINGULARITY_bindir=/usr/local/bin
SINGULARITY_ROOTFS=/usr/local/var/singularity/mnt/container
PWD=/root/repo
```

**Comment by vsoch** [comment]
The files will still be relative to the repository, which is the working directory of the build. So you should be able to add the file without specifying the /root/repo.

Eg.

```
%files
/path/in/repo.txt
```
Added to `/repo.txt` in image. Take a look at some of the other builds on Singularity Hub and their associated repos for examples.

**Comment by funkey** [comment]
Unfortunately, this does not seem to be the case. I tried the following:
* `lime_juice` [1] (relative to repository root),
* `../lime_juice` [2] (relative to `Singularity` file), and
* `/lime_juice` with a leading `/` as you suggest.

In each case, the build fails with `/bin/cp [...] No such file or directory`.

I poked around in the other builds but could so far not find a recipe with the `%files` directive.

My collection: https://www.singularity-hub.org/collections/958
The branch I use: https://github.com/funkey/gunpowder/tree/singularity (the recipe is in `singularity/Singularity`)

[1] [build log](https://www.singularity-hub.org/containers/2671/log)
[2] [build log](https://www.singularity-hub.org/containers/2661/log)

**Comment by vsoch** [comment]
Try getting the files in another way then (maybe just clone the repo from inside the container?), because the builders can't be updated any time soon.

**Comment by vsoch** [comment]
Do you need any more help with this @funkey or can we close the issue?

**Comment by funkey** [comment]
Thanks for following up. We decided to not use Singularity hub eventually.
