### ISSUE TITLE
'Bootstrap' type not supported: docker

### ISSUE THREAD

**Issue by pstrz** [singularityhub/singularityhub.github.io#129]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/containers/2548/log

### Behavior when Building on Singularity, just a couple of weeks ago

No problems.

### Error on Singularity Hub, today

ERROR Return Code 1: b"Enabling debugging
Ending argument loop
Singularity version: 2.4.1-feature-squashbuild-secbuild-2.4.1.g220f8e0
Exec'ing: /usr/local/libexec/singularity/cli/build.exec
Using container recipe deffile: /tmp/tmp2u6rw9cm/Singularity.HPC
Building into existing container: /root/build
Using container recipe deffile: Singularity.HPC
Sanitizing environment
\x1b[0mAdding base Singularity environment to container
\x1b[31mERROR: 'Bootstrap' type not supported: docker

### What do you think is going on?

Fails on the very first line, 'Bootstrap: docker'. This worked a couple of weeks ago, and I still have a container that uses it. Now I need to add more lines to the recipe, but the very first line fails. What changed?

**Comment by vsoch** [comment]
I've seen this exact error! For me it happened when the file had been worked on in some of interface (like a browser) that would add newlines that you can't see like `\r`. The builder has not changed - it's a pre-baked image (for 2.4.1 as we see above) so was it possible that someone edited the file with a non linux editor, and has introduced these characters?

**Comment by vsoch** [comment]
If Singularity is to be usable on different OS eventually, and support things like copy pasting from a browser, I would bring up this issue on the main board:

https://www.github.com/singularityware/singularity/issues

We would want the parser of the file to remove thees characters, or if they are ok, to minimally not fail if the exact string match to docker does not work because of some varying newline.

**Comment by pstrz** [comment]
You're right. I was using the recipe I downloaded from SHub (from my already-working container). I reopened it in a text editor and cleaned it up a bit, and it seems to work fine now. Thanks.

Though, yeah, I would expect a recipe for a working container, downloaded and re-run, to still work. And I did. But I was wrong.

**Comment by vsoch** [comment]
This is totally understandable! I had two recipes in front of me, they looked *exactly* the same, and using diff they were exactly the same! I forget how I found that weird character, but getting rid of it resolved the issue for me. This is why I stay away from things like Microsoft Excel... I'm always afraid of what might be hiding in those little cells :) Glad this worked for you!
