### ISSUE TITLE
Retrieving image hashes

### ISSUE THREAD

**Issue by effigies** [singularityhub/singularityhub.github.io#130]
Supposing I have an image URL, is there a way to retrieve the associated hash? Or would it make sense to try to download the image and hash it myself? And is there any notion of validation, such as signatures, or is HTTPS considered sufficient guarantee? Finally, what is the hash algorithm, and is there any allowance for different algorithms in the future?

The context here is for a BIDS app. The derivative dataset description contains a field called `'SingularityContainerMD5'`, and I would like to automatically populate it when running the app from a singularity container. While I can set a predicted URL as an environment variable, I can't set a variable containing the hash without changing the hash of the container. (Unless running in singularity sets a container hash environment variable? That would be pretty nice, though it may break some assurances for the container to modify the environment.) Additionally, if the hash can be something other than MD5, I need to be flexible enough to handle that case.

Sorry if this is the wrong place to ask this question. I didn't see a better place for general questions.

**Comment by vsoch** [comment]
You can use the API and get the version! See singularity-hub.org/api to see the endpoints. You can also pull a container with --debug to see some example urls.

**Comment by vsoch** [comment]
You can also inspect the container labels and see if there is a version there. For older versions of Singularity there might have been a label added, but I'm not sure if it's there anymore.

**Comment by effigies** [comment]
Cool, thanks. And just to check, the hash algorithm is MD5?

**Comment by vsoch** [comment]
Yes! It should be, here is how it's calculated during build https://github.com/vsoch/singularity-python/blob/f1f241f285f25d73cff16942a11d2c393d094f48/singularity/analysis/reproduce/hash.py#L173

**Comment by effigies** [comment]
Thanks!
