### ISSUE TITLE
building gatk4: git-lfs rate limits exceeded

### ISSUE THREAD

**Issue by IHautaI** [singularityhub/singularityhub.github.io#131]
## Link to Container Collection Log, Build, or Collection (in that order)

Building a container with everything necessary for the GATK4 preprocessing pipeline ( in SCIF, as opposed to their docker image ) for use with nextflow

https://www.singularity-hub.org/containers/2801/log

### Behavior when Building Locally

Builds just fine locally.

### Error on Singularity Hub

git-lfs rate limit exceeded ( near bottom of the log ).

### What do you think is going on?

No idea. Not sure why it would exceed the rate limit on singularity-hub but not locally.

I'm doing the localJar build and I'm not pulling the test files, just the ones necessary for building: https://github.com/broadinstitute/gatk#building

**Comment by vsoch** [comment]
When you clone the repo locally, I assume you are logged in with your Github? It could be that there is some default quota, and as an anonymous user you exceed it on this clone. I am in the middle of traveling but I'll take a look at this as soon as I get back to my computer! As a sanity check try doing the clone where you are an anonymous user.

**Comment by vsoch** [comment]
Ah, looking at the log I think it's likely you ran out of disk space. How big is the entire download?

**Comment by IHautaI** [comment]
Thanks for the quick response!
I'm checking on the anonymous user build right now.
The final size of the image is 2.6G, not sure on how big the GATK clone is when building.

**Comment by IHautaI** [comment]
It doesn't appear to be github login.  Total gatk size was around 890M after git-lfs ran.

**Comment by vsoch** [comment]
Okay, it looks like the error code is 429:

 > 429 - The user has hit a rate limit with the server. Though the API does not specify any rate limits, implementors are encouraged to set some for availability reasons.

 - [docs](https://github.com/git-lfs/git-lfs/blob/e1ccef9712583f20df5a27d6f3bea96e5cdb5693/docs/api/batch.md)
 - [code](https://github.com/git-lfs/git-lfs/blob/42bb740a6f614d4f90ca573252b5cd390fc4baef/lfsapi/errors.go#L95)

And there is this additional (unrelated?) error:

```bash
debconf: delaying package configuration, since apt-utils is not installed
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)
```

The other thing that sticks out is the "smudge error" and I've never seen this before (albeit I don't use LFS). I would try various ways of doing the checkout, or adding debug/trace to using lfs?

https://github.com/git-lfs/git-lfs/issues/2652

You could also try getting the files another way?

**Comment by vsoch** [comment]
Do you still have an issue here? Closing, as this is an issue with git-lfs.
