### ISSUE TITLE
Accept Terms of Service Button Not Working

### ISSUE THREAD

**Issue by RyanAshbaugh** [singularityhub/singularityhub.github.io#133]
I am trying to link my Github account to singularity hub as I have never used singularity hub before, but I cannot get past the terms of service.

On the bottom of the terms of service page is a blue box stating "You must agree to the terms of service to continue." and below that a blue button that says "I Agree", but when the button is clicked it does not continue. The button turns white until somewhere else on the screen is clicked but, it will not advance to the next page and let me get past it.

I can login using my Github account but just get brought back to the terms of service page. I have tried multiple browsers and haven't had any luck yet.

I am not sure if this is the best place for this issue, but I couldn't find anywhere more relevant.

Should I expect to be brought to a new page after clicking "I Agree", or did it simply work when the button was clicked? It just seems strange to be continually brought back to the terms of service page when logging in and out if it did in fact work correctly.

**Comment by vsoch** [comment]
hey @RyanAshbaugh ! Do you see any error messages in the JavaScript console when you load the page, or click?

**Comment by RyanAshbaugh** [comment]
I do see multiple errors, multiple of "TypeError: $logo[0] is undefined", and another that says "Source map error: request failed with status 404 Resource URL: https://www.singularity-hub.org/static/js/jquery.min.js Source Map URL: jquery.min.map".

The image below shows the errors in more detail.

![screenshot from 2018-05-29 12-59-36](https://user-images.githubusercontent.com/12957210/40673638-4e6614fe-6340-11e8-925a-bb03c6aa3c4b.png)

Is this what you were referring to?

**Comment by vsoch** [comment]
Could you try loading the page (and doing the agree afresh) with your various adblockers / etc. disabled? That would be my first guess - the submit relies upon Jquery so if these errors are being triggered, it's probably just not working.

**Comment by RyanAshbaugh** [comment]
I have resolved the issue, I believe it was related to the fact that the window was snapped to only half of the screen when attempting to click "I Agree". 

I maximized the window to the full screen and the blue description box and blue "I Agree" button appeared on the right side of the terms of service rather than below. I am guessing is related to the errors which mention "initRightMenu" shown in the picture above.

Once maximized, the first time I clicked "I Agree" it worked just fine.

Thanks and sorry for the trouble!

**Comment by vsoch** [comment]
haha no worries! Web development continues to astound me in how challenging it is for tiny details like this I never would imagine! I bet it had something to do with mobile vs. not, which would change depending on the size of your window. I'm glad that it's fixed up! I'm closing the issue, and please reopen if there is more trouble.
