### ISSUE TITLE
Date sorting seems to be off 

### ISSUE THREAD

**Issue by bbarker** [singularityhub/singularityhub.github.io#138]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/1220#

### Error on Singularity Hub

The July 17 2018 entry will sometimes appear in between July 6 and July 16.

### What do you think is going on?

We've entered a singularity and time is no longer monotonic! Or, perhaps, there is an issue with how dates are being compared.

**Comment by vsoch** [comment]
Haha, thank you :)

:space_invader:

**Comment by vsoch** [comment]
Oh dear, we've entered Singularity? I better start stock piling that supply of avocados... !

**Comment by vsoch** [comment]
Leaving this here for future me (or anyone that wants to try a fix attempt!)
https://datatables.net/reference/option/columns.type

**Comment by vsoch** [comment]
hey @bbarker I just worked on this about 30 minutes, couldn't get it working. I opted to sort by the tag, ascending, instead. So still the status here is "can't figure out how to fix."
