### ISSUE TITLE
Failure copying files into container from root of repo

### ISSUE THREAD

**Issue by bbarker** [singularityhub/singularityhub.github.io#140]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/containers/3614/log

### Behavior when Building Locally

Container builds correctly

### Error on Singularity Hub

```
/bin/cp: cannot stat './Base/OpenMPI/config.nix': No such file or directory
ERROR: Failed copying file(s) into container
```

### What do you think is going on?

As discussed in #139, the build is believed to occur from the root of the repo, but since `./Base/OpenMPI/config.nix` is addressable from the root of the repo, I believe it is most likely assumed that the build happens from the same directory as the singularity recipe file. More importantly, I believe this means there is no way to address a file from the repo root.

A possible workaround would be to add an environment variable: SINGULARITY_REPO_ROOT that is an absolute path and can be accessed from the `%files` section.

Another workaround, which is user oriented, is to direct users to put all singularity recipes at some directory (call it RecipeRoot, typically the root of the collection repository), and all files that must be used in the build must be children of RecipeRoot.

**Comment by vsoch** [comment]
This is the recipe? 

https://github.com/federatedcloud/NixTemplates/blob/develop/Base/OpenMPI/Singularity.nix_alpine_openmpi_3cdef444dbb9648d67074bbaab8216851d0dd11d

The last change was 2 days ago, I thought you were going to change it? Can you point me to the recipe that this is coming from?

**Comment by bbarker** [comment]
Ah yes, I have made the default branch develop, so when I merge to master things get build on SHub :-). So it is on master (and a different file name as indicated in the build log - incidentally both fillename and branch are indicated in the shub build log, but I'll try to remember to link in for convenience next time): https://github.com/federatedcloud/NixTemplates/blob/master/Base/OpenMPI/Singularity.nix_alpine_openmpi_5a14a0d9988b1d0dfe2a8a5c2ad2f12595d5d6c8

**Comment by bbarker** [comment]
In case this is all pointless, and I do a revert on the commit (in the rewrite-history sense), I'll post the contents of the recipe here for posterity:

```
Bootstrap: shub
From: federatedcloud/NixTemplates:nix_alpine_base_14e053b44868adf9413cad2c6394cfbdfb149b81

# For development:
# Bootstrap: localimage
# From: Base/nix_alpine_base_bc4bd803c3aaa8622b493bcf66190c3944706ec3_testing.img

%environment
export TRIGGER=1
export PATH="${PATH}:/usr/local/bin"

%setup

%files
./Base/OpenMPI/config.nix /template/hometmp/.config/nixpkgs/
./Base/OpenMPI/dev-env.nix /nixenv/nixuser/
Utils/persist-env.sh /nixenv/nixuser/
./Base/OpenMPI/mpi4py_benchmarks /nixenv/nixuser/
./Base/OpenMPI/entrypoint* /nixenv/nixuser/
./Base/OpenMPI/default.nix /nixenv/nixuser/
./Base/OpenMPI/default.sh /nixenv/nixuser/

%runscript

USER=$(whoami)
echo "runscript user is $USER"

# Run the base nix runscript to initialize nix
sh /.singularity.d/runscript-nixbase

# We need to overwrite the file from base
cp -R /template/hometmp/.config/nixpkgs/* $HOME/.config/nixpkgs/

$nixenv && cd /tmp && sh /nixenv/nixuser/persist-env.sh /nixenv/nixuser/dev-env.nix

# TODO: May need this later
# cp ./Base/OpenMPI/default-mca-params.conf ${HOME}/.openmpi/mca-params.conf

#TODO: check if "$@", if not, run default.sh
# exec /bin/sh "$@"
exec /bin/sh "/nixenv/nixuser/default.sh"
```

**Comment by bbarker** [comment]
@vsoch Any thoughts on this? Perhaps I just misunderstood what it means for the build to be happening from the root of the repo; certainly I'm not surprised that the above doesn't work, since all paths (in my experience) referenced from a singularity recipe seem to assume the CWD is the directory the Singularity recipe resides in.

If this is unlikely to be fixed or fixed anytime soon, I can just reorganize my repo for now. But I think providing a `SINGULARITY_REPO_ROOT` variable might help with this.

**Comment by vsoch** [comment]
It's implemented to be similar to Docker, and when I build a container I generally have a mindset that I interact with the filesystem relative to the same directory as the recipe file (Dockerfile or Singularity). Any change / variance from that would make the builder special, which I'm not convinced is a great idea. However I'm open to any changes that have considerable support / request from the larger community. When this happens, they can go in when I do server work or certificate updates. Changes to the server, since this isn't a professionally deployed and scaled application, do actually coincide with restarting the container, which means a bloop in downtime and potential for 500 responses for whomever is using it at the time. Docker is also not always consistent with these restarts, and sometimes the entire server actually needs to be restarted. For these reasons, I'm not going to quickly do a change to the codebase and a server restart for a custom feature requested by one person. Does that make sense I hope?

**Comment by vsoch** [comment]
It looks like @bbarker has reorganized repo to work, closing issue. Thanks!
