### ISSUE TITLE
Git push does not automatically trigger a re-build

### ISSUE THREAD

**Issue by tdelhomme** [singularityhub/singularityhub.github.io#142]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/1404

### Behavior when Building Locally

No issue with building.

### Error on Singularity Hub

No errors.

### What do you think is going on?

Build trigger is on commits.
Here is my [github repo](https://github.com/IARCbioinfo/template-nf), I use conda to install softwares, from both a [YAML file](https://github.com/IARCbioinfo/template-nf/blob/master/environment.yml) describing them and a [singularity file](https://github.com/nf-core/EAGER2/blob/master/Singularity) where commands to use conda are stored.
The problem here is that my container depends on these two files but the build is done only if the modification is done on the `singularity` file.
I suggest that we should have a re-build for each commit (not depending on the modified file), what do you think about this?

**Comment by vsoch** [comment]
I would recommend for your case either a manual build, or a deployment build. Since Singularity Hub is maintained by just me, with limited resources, I can't afford to have the container build with **every** user commit. There are definitely options for you to take (via deployment, or manual, or some other method that changes the file) so I hope these might work for you :)

**Comment by vsoch** [comment]
See my comments at the issue linked above. There are several strategies you could take to get the behavior you want, and we do need to keep the way Singularity Hub is now as a strategy to choose the "latest" Singularity file when there are more than one. It's also (typically) redundant to rebuild on an unchanged file, so if this doesn't work for you, I'd suggest a manual build or a CI strategy that DOES edit the file (for example, why not have a version string as a variable (environment or label) in the build recipe?

**Comment by tdelhomme** [comment]
@vsoch this is a great idea to add a version on the singularity file to force the build, thanks! Will try that.

**Comment by vsoch** [comment]
Awesome! Yeah I needed the same trick a while back, and funnily enough it made my containers a little better :) Happy building!

**Comment by tdelhomme** [comment]
Thanks !!
