### ISSUE TITLE
'ERROR: Could not locate /bin/sh inside the container

### ISSUE THREAD

**Issue by ebioman** [singularityhub/singularityhub.github.io#144]
## Link to Container Collection Log, Build, or Collection (in that order)

Collection:
https://www.singularity-hub.org/collections/1398

Log:
https://www.singularity-hub.org/containers/4036/log

Build:
 ebioman/SmrtLinkSingularity:falconunzip 

### Behavior when Building Locally

Building locally is working perfectly with the following work-flow:

    sudo singularity build --sandbox test MyDef.def
    sudo singularity build MyImage.img test

I can execute e.g  `singularity exec MyImage.img samtools` which works as expected

### Error on Singularity Hub

ERROR Return Code 1: ('ERROR: Could not locate /bin/sh inside the container
',)

### What do you think is going on?

I saw some older tickets with similar errors pointing into issues of ownership, but they should be fixed in more recent versions.

I am using 2.5.2-dist and dont understand where the issue stems from

**Comment by vsoch** [comment]
How does it build? I don't see any "From" or "Bootstrap" in the recipe:

https://github.com/ebioman/SmrtLinkSingularity/blob/add-license-1/Singularity.FalconUnzip

**Comment by vsoch** [comment]
eg, your working containers have:

```bash
Bootstrap: docker
From: centos:latest
```

**Comment by ebioman** [comment]
Okay, never felt that silly - I couldn't access the github via terminal on that machine and copy&pasted the recipe. In the process I managed to forget 3 lines which were obviously very crucial.
Sorry for wasting your time

**Comment by vsoch** [comment]
haha, you know, I did something like this a few days ago! I didn't mean it, but I accidentally erased an entire line to collect an input variable, and then well, it was undefined :P No worries!
