### ISSUE TITLE
Build stuck in "Running" state for 7 days.

### ISSUE THREAD

**Issue by abensonca** [singularityhub/singularityhub.github.io#147]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/1639

### Behavior when Building Locally

Builds successfully locally.

### Error on Singularity Hub

Still in state "Running" after 7 days.

### What do you think is going on?

Not sure - it's a long build locally (~4 hours with 16 cores), but I would expect it to be finished by now.

**Comment by vsoch** [comment]
Heyo! I can check this out for you. Can you tell me the specs of your local machine, version of singularity, and size of final image?

**Comment by abensonca** [comment]
Thanks! Here's the info:

Local machine is 8 core Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz:

$ uname -a
Linux andrew-Precision-3520 4.4.0-133-generic #159-Ubuntu SMP Fri Aug 10 07:31:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ singularity --version
2.5.2-dist

$ ls -l fedora-27.simg 
-rwxr-xr-x 1 root root 2956984351 Sep  7 11:42 fedora-27.simg

**Comment by vsoch** [comment]
Oh and it occurs to me - I’ve seen the builder die (and not been able to send message back to the server) so likely what is happening is that your build is taking up too much memory or disk space, and it gets killed automatically after 2 hours. This builder only has 2 or 4 cores I believe and will be killed at a much lower time than your build so I can almost assure you that is the issue. I’ll take a look at your recipe and see if I can make suggestions for breaking down the build time.

**Comment by abensonca** [comment]
ok, thanks. my guess is that it's because it needs to build a modified GCC (with a custom patch). Once that is actually fixed in GCC directly I can avoid that problem and the build time should be much lower.

**Comment by vsoch** [comment]
Wow you are indeed compiling a ton!  I think that there is an easy fix, if you build a base image ( and put on docker hub or if small enough another image on singularity hub ) then you can use that image as a base and add the modified software on top of it. That should reduce the build time enough so that it will fit within the allotted.

**Comment by abensonca** [comment]
OK - that sounds like something I can do. Thanks!

**Comment by vsoch** [comment]
Great! And just to clarify - you don't have a builder instance actively running - the state of "running" is due to the miscommuication. So your best bet (when the base is done) is to delete that container and then start fresh with another commit.

If there is something actively running that you want me to check up on for you (for example, I think we should look at the CPU usage during your build) ping me here and I can run over to the shub tab and look at the monitoring.

**Comment by abensonca** [comment]
Thanks. I'll probably try uploading an image to DockerHub next week and then try this again. I'll let you know if I run into any problems. Thanks for your help!

**Comment by vsoch** [comment]
ok sounds good! :) If you are on the East coast, stay safe with the storms!

**Comment by abensonca** [comment]
I'm in Hawaii right now, so we just had our tropical storm, but it wasn't too bad by the time it reached Honolulu!

**Comment by vsoch** [comment]
Ping @abensonca any updates?

**Comment by abensonca** [comment]
@vsoch Unfortunately I haven't had time to get back to this yet. Hopefully I'll be able to sometime this month though.

**Comment by vsoch** [comment]
ok no worries. Thanks for the update.

**Comment by vsoch** [comment]
If you are sure size isn't an issue (I would bet it's size, but I can't see your instance so I can't confirm) then try secure build, install as follows:

```
cd /tmp
git clone -b feature-squashbuild-secbuild-2.5.0 https://github.com/cclerget/singularity.git
cd /tmp/singularity && ./autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && sudo make secbuildimg
```
Then when you build, add the `--isolated` flag. You can also again issue a build and if you tell me the right time I can shell in to the builder and see if there is anything meaningful to relay back. I offered to do this previously.

**Comment by abensonca** [comment]
Thanks! I'll try this (probably won't be until late October though).

**Comment by brucemoran** [comment]
@vsoch thanks for the info, and sorry for the unnecessary issue post. Ran secure build and completed fine. As size is then the issue, I have divided into several recipes which are building and hopefully complete.

**Comment by vsoch** [comment]
ok great!
