### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by DrJones85** [singularityhub/singularityhub.github.io#148]

**Comment by vsoch** [comment]
```
singularity pull shub://vsoch/hello-world
```
```
singularity run shub://vsoch/hello-world
```
haha, you closed it! Thanks for stopping by!

**Comment by DrJones85** [comment]
> ```
> singularity pull shub://vsoch/hello-world
> ```
> ```
> singularity run shub://vsoch/hello-world
> ```
> haha, you closed it! Thanks for stopping by!

Yeah, sorry. I wanted to search other issues and didn't realize I was posting. I will search further and if I still have issues, I will post again with details. 

Thanks for replying so fast!
