### ISSUE TITLE
Multiple containers per repo

### ISSUE THREAD

**Issue by markeganfuller** [singularityhub/singularityhub.github.io#15]
For HPC application teams it would be nice to have multi-container repositories as opposed to one container per repository eg:

```
├── aligngraph
│   └── centos7-aligngraph.def
├── macaulay2
│   └── centos7-macaulay2.def
├── mrbayes
│   └── ubuntu-mrbayes-3.6.2_openmpi-2.1.0.def
├── pandoc
│   └── centos7-pandoc-1.12.3.1-1.el7.def
├── python
│   ├── centos7-python-2.7.5.el7.def
│   ├── centos7-python-3.4.3-7.el7.def
│   └── centos7-python-3.4.def
├── R
│   ├── centos7-R.def
│   └── README.md
└── README.md
```

Some thoughts on implementation:

* How to detect a def file? or just list defs in `Singularity`?
* How to deal with image size settings?
* Detecting only changed defs and only building those?

**Comment by vsoch** [comment]
Hmm interesting... we could definitely have the builders "sniff" for changed files, and we could do a hash of the content to assess for changes. The issue here is reproducibility... all of a sudden one commit and build is linked to multiple images, only some of which may have changed. It also hugely increases the (almost certainty) that the builder instance would run out of disk space. It also would mean extremely long running builds. Do you have ideas for how to get around these issues? The entire process of cloning and assessing the repos doesn't happen on the application server... it is done by the builder, so we wouldn't be able to deploy multiple builders for one repo.

**Comment by vsoch** [comment]
The other issue is uris- having one image per repo maps very cleanly to a uri, and different branches map nicely to tags for different versions. This approach would require the user to manually define some uri for each file, which makes the simple process of turning on the repo and being done turn into one that is much more complicated. Further, with the current setup, if all the metadata went away, you could rebuild the entire images storage easily. With this approach, we would lose those custom user paths and names.

**Comment by vsoch** [comment]
So I think my thoughts up to this point is that if we do something like this, it must have a workflow that fits cleanly into the Github flow and definition of things, and should require minimal additional variables set by the user that, given if they were lost, would be hard to regenerate.

**Comment by vsoch** [comment]
Just curious - given that you might have different people maintaining the packages, what are the downsides to having a .git file in each of those directories? Eg:

```bash

├── python (with different versions on different branches)
│   ├── Singularity
│   ├── README.md
│   └── .git
├── R
│   ├── Singularity
│   ├── README.md
│   └── .git
```
That way, let's say that my HPC center really likes your python (but isn't interested in the rest) the modularity of the above approach would support forking that repo and using those definition files.

Perhaps we might think about a way that can link collections of containers (eg, R and python) into some larger group? Is that the desire?

**Comment by markeganfuller** [comment]
>Do you have ideas for how to get around these issues? The entire process of cloning and assessing the repos doesn't happen on the application server... it is done by the builder, so we wouldn't be able to deploy multiple builders for one repo.

Not sure about this one, but multiple builders sounds like the requirement, perhaps a builder which can trigger other builders? I'll admit I haven't investigated the code.

>This approach would require the user to manually define some uri for each file, which makes the simple process of turning on the repo and being done turn into one that is much more complicated

Perhaps something automatic like `repo/branch_or_tag/path/file_name` eg `shub://markeganfuller/singularity-containers/master/centos7-python-2.7.5.el7` ? This is pretty much how github handles files.

> Further, with the current setup, if all the metadata went away, you could rebuild the entire images storage easily. With this approach, we would lose those custom user paths and names.

I'm not sure the path / name matter for the image, its more just us keeping things organised especially where there's multiple versions or additional files per image.

>So I think my thoughts up to this point is that if we do something like this, it must have a workflow that fits cleanly into the Github flow and definition of things, and should require minimal additional variables set by the user that, given if they were lost, would be hard to regenerate.

Agreed, I'd love this to be as slick as possible.

> Just curious - given that you might have different people maintaining the packages, what are the downsides to having a .git file in each of those directories?

We have a team of ~5 people and in our current modulefiles system ~400 modules (~230 unique). We don't really want to manage 247 separate repositories containing a single file each and I'd say at least for our use case that a single repository makes more sense. In a similar vein, UCL have this repository for their application builds: https://github.com/UCL-RITS/rcps-buildscripts

> That way, let's say that my HPC center really likes your python (but isn't interested in the rest) the modularity of the above approach would support forking that repo and using those definition files.

I see your point here and it would be nice to have this ability but I think our use case and sheer amount conflicts with this slightly. I think this makes 100% sense for 'vendors' but for sites which have compilations of a lot of different tools its cleaner to go "here's our containers" as one repo.

> Perhaps we might think about a way that can link collections of containers (eg, R and python) into some larger group? Is that the desire?

Hmm, potentially, but the first thing that comes to mind there is git-submodules which are generally awkward to work with, perhaps something along the lines of `r10k` for puppet which uses a file like https://github.com/puppetlabs/control-repo/blob/production/Puppetfile and then running the command pulls down those repos to a folder that's in `.gitignore` for the main repository?

Actually the r10k style ideal might not be awful, its how puppet is effectively avoiding git-submodules and enabling reuse, it does mean many individual repos but allows a 'collection' as it were.

**Comment by qobilidop** [comment]
I think it makes sense to implement something similar to what Docker Hub does. In Docker Hub, when doing an automated build, there is an option to set the Dockerfile Location, which defaults to `/`. This does not require extra effort from the user to turn on an automated build using the default settings, and it opens up new possibilities.

**Comment by vsoch** [comment]
@qobilidop - in doing that, Docker Hub stores (in its database) that specification of the location. Given that Docker Hub was compromised, to rebuild all those image the user would need to specify that again. By making it required to put at /, and allowing for tags with other branches, this means that the Singularity Hub database could go away equivalently, and a build that is reconnected would reproduce exactly as it was before. 

@markeganfuller I agree that the use case of Singularity Hub for an organization or larger institution that wants to build at scale is not ideal - and for this reason I've started developing a Singularity Registry, which will be a local hub that an institution can deploy to have more programmatic, controlled access. If you look at the singularity-registry wiki I would appreciate any feedback that you might have.

**Comment by vsoch** [comment]
@markeganfuller just for an update - this is going to supported for registries (eg, HPC centers) to maintain a setup (almost just like) the one you provided. I just added the milestone, no ETA but it's in the works!

**Comment by vsoch** [comment]
Another update, this is ready to go and will be possible with Singularity version 2.0. The one difference is that the folder organization still relies on a file called "Singularity" with an extension (however long) corresponding to the tag. So - a file "Singularity.ubuntu" in three different folders in the same repo would be akin to the specifying the same image to be built, and in the case of redundancy, the newest is used. This gives flexibility to organize images however you need, but still be specific in naming. I'm going to add the finished milestone to this one (but not closing) and definitely would appreciate more feedback when the next version goes out!
