### ISSUE TITLE
Error : Can not find image: Check your capitlization

### ISSUE THREAD

**Issue by Amjadhpc** [singularityhub/singularityhub.github.io#151]
## Link to Container Collection Log, Build, or Collection (in that order)

Hello
I have uploaded and build my container on singularity hub. 
There are no errors in the log

https://www.singularity-hub.org/containers/5195/log

https://www.singularity-hub.org/containers/5195

https://www.singularity-hub.org/collections/1787

### Behavior when Building Locally

I build the image  locally using Singularity V 2.6.0 .
It gave no issues

### Error on Singularity Hub

When i try to check out the image i get the following error
 singularity  pull shub://Amjadhpc/PHEnix
ERROR Cannot find image. Is your capitalization correct?

### What do you think is going on?

I do not see any issues in build or Error.  So i am not sure what is the issue

**Comment by vsoch** [comment]
You have left off the tag “6.0”

**Comment by vsoch** [comment]
Try this:

```
singularity pull shub://Amjadhpc/PHEnix:6.0
```
When you don't specify a tag, it defaults to "latest." You don't have a latest so the error message is correct, it cannot find the image.

**Comment by Amjadhpc** [comment]
Thank you,
That  works fine.
https://www.singularity-hub.org/collections/1787/usage

This page needs then to be updated to include tag?

**Comment by vsoch** [comment]
The usage is for the general collection. It does not include a tag. Glad you figured it out!
