### ISSUE TITLE
None of the uri links work

### ISSUE THREAD

**Issue by lancewilson-monash** [singularityhub/singularityhub.github.io#155]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/1396

### Error on Singularity Hub
Error message on page when clicking all uri links
e.g https://www.singularity-hub.org/containers/4618/view
We had an issue retrieving files for this container! Try another build?

### What do you think is going on?

The collection has completely different build images made by tag. Maybe there are too many images?

**Comment by vsoch** [comment]
This is probably more of an interface bug and definitely my fault - the "view" button (or the view) that you would get with the first click is for the "tree" view, and this indeed needs a list of files. However, in the case that the list is too long (and the send of it failed to happen from the builder) you can still get the container, just without that list, but then we can't make the visualization.

So - if you click on the green buttons instead, you can still get the container view for example:

https://www.singularity-hub.org/containers/4618

And I hope this is what you might be looking for? To properly fix I should just remove the link entirely given that the files aren't found, I'd consider that a bug :P

**Comment by lancewilson-monash** [comment]
Excellent. I was after the build log as a locally built container is different to the singularity hub container. Build log is found and the big green button works fine.
