### ISSUE TITLE
When adding a new collection with multiple containers, only a few of them are built.

### ISSUE THREAD

**Issue by eburgueno** [singularityhub/singularityhub.github.io#162]
## Link to Collection
https://www.singularity-hub.org/collections/2322

### Error on Singularity Hub

When adding a new collection with multiple containers, only a few of them are built. The others remain stuck at 'SETUP' and never actually build.

I've seen this happening with collections that have more than 3 containers, but I can't remember which ones. I used to just change the collection settings to Manual build and trigger the missing ones by hand, but this gets old quickly.

**Comment by vsoch** [comment]
There is only one builder per collection, so likely it's overwhelming that builder - I would try breaking your collection down into more than one repo and seeing if that helps.

**Comment by eburgueno** [comment]
That might help indeed, but is not ideal long term considering that all the containers in the collection are just different versions of the same tool, so it doesn't make sense to separate them to different repos.

A different workaround would be to have a 'rebuild' button next to each 'Status' line that can trigger a manual rebuild of those containers that do not have a 'COMPLETE' status. But I know this is not a real fix.

**Comment by radoye** [comment]
I'd support this kind of request. Are there any plans to support build dependencies, within a single collection? 

We group containers and leverage dependency graphs to shorten build times and reduce pull bandwidth. It would be convenient not to have to trigger manual builds.

**Comment by vsoch** [comment]
If your builder is overwhelmed you can separate into multiple collections. If you want to use prebuilt bases Docker Hub works well for that!

**Comment by vsoch** [comment]
The original issue seems to be resolved (the collection is green) so I'm going to close here. For future updates to shub, we're currently collecting feedback, so if you didn't get an email, see the form here -> https://forms.gle/AmA2sqnZxvvecms56 Thanks everyone!
