### ISSUE TITLE
Trigger build issue

### ISSUE THREAD

**Issue by willgpaik** [singularityhub/singularityhub.github.io#175]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/collections/2152

### Behavior when Building Locally

N/A

### Error on Singularity Hub

Trigger build didn't take me to build option but after several tries, I got a message: You've done that too many times, try again tomorrow.

### What do you think is going on?

Possibly website is not stable?

**Comment by vsoch** [comment]
Hey @willgpaik - I'm about to announce this (you are too quick!) but there are new limitations on the number of requests that you can make per view. For trigger build, you are limited to 10 per day (so use them wisely!) We had recent malicious use of our service and this is the only way we can ensure keeping it open. I'll have an official announcement soon, and for now, limits are here -> https://singularityhub.github.io/singularityhub-docs/docs/regulatory/limits

**Comment by willgpaik** [comment]
Hi @vsoch, thank you for the information regarding limits. However, my problem was not really about the limit. Trigger build button didn't take me to the build option page today. Message in blue box shown on the collection page told me trigger cannot be done. I didn't know that counts toward my build limit since it didn't even go through. Can you check if trigger build works on your end? Since my daily max was reached, I cannot test it today anymore.

**Comment by vsoch** [comment]
hey @willgpaik - yes that is also correct, and sorry that I wasn't more clear. I just released an official notice here -> https://singularityhub.github.io/singularityhub-docs/2019/release-announcement/ Basically all building is disabled unless you are one of the testing users, meaning you will be able to spend some time testing different aspects of the service. if you'd like to be a testing user I can add you (and you'll still need to wait until tomorrow to trigger) or if you don't want to test, likely building will be re-enabled for everyone early next week.

**Comment by vsoch** [comment]
You might have missed, but the service has been down since early July because of malicious use of our API. I've been working 24/7 to add many changes, and unfortunately many of them limit usage of triggers, and overall building. Currently, since it's just opening back up, all building avenues are disabled for a regular user, and since you didn't know this you hit the limit. It wouldn't have made a difference between (as the message correctly indicated) building is disabled.

**Comment by willgpaik** [comment]
Hi @vsoch, thanks for the update. It was very clear and helpful. I don't mind testing but what are the expectations for test users?

**Comment by vsoch** [comment]
Nothing terribly strict, just that you'll do work as normal and send me a message if you run into some issue (like you did here!)

**Comment by willgpaik** [comment]
Sure, that's not a problem. I guess I can close this issue now. Thank you!

**Comment by vsoch** [comment]
Great! Just to let you know, I won't be able to add you until tomorrow morning, but it should be okay since the block will release by then. Wait for me to update the issue here before trying.

**Comment by vsoch** [comment]
okay you're added!

**Comment by willgpaik** [comment]
Sorry to bother you again but I still cannot build due to error message: Building is disabled
I don't mind waiting till next week though.

**Comment by vsoch** [comment]
@willgpaik the trigger won't work, but you should be able to push from GitHub. If you are okay with waiting, that might be best - I wanted to limit the custom groups of build users to just the commit -> build case.
