### ISSUE TITLE
Whittle down GitHub permissions

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularityhub.github.io#176]
Per @yarikoptic suggestion, GitHub permissions have gone a long way since the original implementation of the server, and very likely we can better fine tune permissions to ask for less. @yarikoptic if I put some changes live tomorrow with reduced permissions would you be willing and able to test?

**Comment by yarikoptic** [comment]
Sure, although I already allowed as is for two accounts, but I guess I could find more

**Comment by vsoch** [comment]
I think once I update the permissions on the server, it asks you to reauthenticate (and nullifies the old).

**Comment by vsoch** [comment]
hey @yarikoptic I'm ready to test, but looking here https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/ I don't see how I could remove some permissions. There doesn't seem to be a "read only" access to repositories. We need `repo:status` to get details about the commits (e.g, dates and files changed.) The main difference between public/private access is that private has just `repo` and public has `repo:status` because we can read the repos publicly. Let me know your thoughts / ideas.

**Comment by yarikoptic** [comment]
yeah, strange why there is no separation into read and write for that `repo:status`... I guess that is life.  So no good ideas on my end, I guess just close this issue and thanks for considering tuning it up

**Comment by vsoch** [comment]
Thanks @yarikoptic , closing.
