### ISSUE TITLE
Building is diabled

### ISSUE THREAD

**Issue by Poulami-Sarkar** [singularityhub/singularityhub.github.io#177]
I am trying to build my container by the manual trigger. Although I enabled building in the settings, whenever I click on trigger build, I keep getting a message saying " building is disabled". Could someone please help me with this issue?

**Comment by vsoch** [comment]
It will be disabled for probably one more day, sorry for the inconvenience! Details here https://singularityhub.github.io/singularityhub-docs/2019/release-announcement/

**Comment by vsoch** [comment]
hey @Poulami-Sarkar building should be enabled for you now! You will need to authenticate with GitHub, and if you have existing repos, you'll need to go into your respository settings and update the webhook to not use www.
