### ISSUE TITLE
GitHub login mandatory for search?

### ISSUE THREAD

**Issue by richelbilderbeek** [singularityhub/singularityhub.github.io#179]
Hi,

When I want to [search the singularity-hub.org website](https://singularity-hub.org/accounts/login/?next=/search) I get this screen:

![login](https://user-images.githubusercontent.com/2098230/61937513-51426280-af8f-11e9-93b2-8d567e4f7160.png)

I feel it discouraging that such a login is mandatory, when all I want is to see what the website is about. 

Additionally, when I do click 'Login with GitHub', the website is requesting admin access:

![acccess](https://user-images.githubusercontent.com/2098230/61937751-d62d7c00-af8f-11e9-8427-f7c90700f2a0.png)

Sure, I trust you people, but this also feels discouraging.

Is this mandatory GitHub login is intentional? 

 * If not, I am happy to have reported this. Happy to help :+1:
 * If yes, I am sure there are (probably financial?) reasons to keep it as such ...

Keep up the good work :+1:

**Comment by vsoch** [comment]
Yes this is also one of the changes since we had a malicious user. It’s not ideal from a usability perspective, but it’s essential that it’s not easy to discover containers. The login permissions are standard to allow connecting public and private repos for wenhooks.

**Comment by richelbilderbeek** [comment]
Too bad to hear that. Well, that was exactly The Good Reason I wanted to hear!

Keep up the good work, will close this Issue :+1:

**Comment by richelbilderbeek** [comment]
Hi @vsoch.

I am sorry to re-open this, yet here is why: I was working through some Singularity examples, with the `echo "Rooooar`s and the `Help me. I'm in the container`s. This mandatory GitHub login feels so un-Singularity/Vanessasaurian, it bothered me too much.

It would feel more friendly/Singularity/Vanessasaurian to add some text below the GitHub login buttons, for example:

![login2](https://user-images.githubusercontent.com/2098230/61990742-b016e300-b046-11e9-9f6f-c390cb153da0.png)

Clicking the 'Why?' results in sharing The Good Reason with the user there.

I hope you enjoy my suggestion. The current state feels such a dissonant compared to the Singularity user manual. I do not expect to have my suggestion implemented, but I am happy it is off my chest.

Keep up the good work :+1:

**Comment by vsoch** [comment]
Hi @richelbilderbeek - Singularity Hub was very "Vanessaurian" and open for three years - it wasn't very friendly to have that generosity abused to the point of having to consider closing the service for everyone, and putting my group in a bad position to recover from it. It's only been able to remain open with setting of limits and changes that I agree, change the usability of the site, and not for the better. As the developer and maintainer of this service, I am obligated to choose security over all. I appreciate your feedback on wanting an extra "Why?" but this is not something that should be advertised on the site. If it is hugely bothersome you are a free human to use another service (you can try Sylabs cloud) or method to build your containers, or (reasonably) log in to access those views. Thanks for the feedback.
