### ISSUE TITLE
Typo on singularity-hub.org

### ISSUE THREAD

**Issue by mvdoc** [singularityhub/singularityhub.github.io#18]
Hi,
I was checking out the singularity hub webpage and noticed a typo (Ber**E**keley), but couldn't find out the repo, so I'm opening this issue. See screenshot below

![image](https://cloud.githubusercontent.com/assets/6150554/26291728/3cb786ee-3e65-11e7-9826-a2dddbe88c76.png)

**Comment by vsoch** [comment]
haha, oups, sorry about that! Let me fix that right up ... one sec!

**Comment by vsoch** [comment]
That was in the footer - good catch! And even further, I had a div off so the cutest of the robots wasn't even showing! Does this look ok now?

![image](https://cloud.githubusercontent.com/assets/814322/26292654/ac0ef8b8-3e85-11e7-9981-9877bead8e97.png)
 
Let me know if I missed anything - sorry about the spelling error! Berkeley is one of those words it has taken me years to figure out where to put the e's, and I still throw in extra ones every now and then :)

**Comment by mvdoc** [comment]
Looks great to me (and honestly I have a hard time with the Es in Berkeley as well ;) and I love the robots 👍

**Comment by vsoch** [comment]
Glad to help! Closing issue.
