### ISSUE TITLE
Remove API link from user menu 

### ISSUE THREAD

**Issue by richelbilderbeek** [singularityhub/singularityhub.github.io#180]
When I am logged in at [https://singularity-hub.org/](https://singularity-hub.org/) and I click 'API' ...

![click_api](https://user-images.githubusercontent.com/2098230/61939381-6ae5a900-af93-11e9-891b-9cb98b1d7cdf.png)

... I get this error:

![api](https://user-images.githubusercontent.com/2098230/61939420-818c0000-af93-11e9-9649-363a44bd7755.png)

I guess this is not what was intended, so I'll just report it. Happy to help :+1:

**Comment by vsoch** [comment]
That’s actually since correct, the browsable endpoints have been removed. The bug is still having the link there :)

**Comment by richelbilderbeek** [comment]
Cool, good luck fixing it :+1:

**Comment by vsoch** [comment]
Already done! Thanks for the issue @richelbilderbeek, I missed this one! Closing.
