### ISSUE TITLE
Provide a "restart build" function on build errors

### ISSUE THREAD

**Issue by sdruskat** [singularityhub/singularityhub.github.io#181]
E.g., https://singularity-hub.org/containers/10505/log / https://singularity-hub.org/collections/3363

I think it'd be great to be able to restart a build that has errored, e.g., via a button next to the "Error" button on the collection page.

In my case, I set up the wrong builder for my very first build (2.5.2 instead of 3.x), so the build failed. I would like to be able to just restart the same build in this case.

**Comment by vsoch** [comment]
You should be able to cancel and then trigger a build for the same container.

**Comment by vsoch** [comment]
This functionality is provided by doing cancel and then trigger, so (being conservative about shub) I don't see implementing it in the near future.
