### ISSUE TITLE
How do you specify arguements? like `--writable` for example

### ISSUE THREAD

**Issue by MuhsinFatih** [singularityhub/singularityhub.github.io#184]
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/containers/10548/log

### Behavior when Building Locally

[On singularity documentation](https://singularity.lbl.gov/quickstart), arguments for singularity such as [--writable](https://singularity.lbl.gov/quickstart#writable-image) are described, and they work as described in the documents

### What do you think is going on?

I cannot find the same functionality for singularity-hub documented anywhere in docs. I tried simply adding the argument with manual trigger in the section for recipe file by appending `--writable` as if I was passing in a command-line argument, didn't expect it to work, and it didn't.

Is it possible to specify arguments to the singularity command?

**Comment by vsoch** [comment]
Containers on singularity hub only have the option to build a SIF binary.  The goal is to support reproducible science and building a writable container does not support that.  You would need to build a SIF, pull to your local machine, and then build the binary into a writable container if that’s what you absolutely need.

**Comment by MuhsinFatih** [comment]
The reason I want this is I need to install different python packages to my container, which is then used with an hpc scheduler. singularity allows local changes to the image, but those local changes are not visible to the scheduler as it runs the image under different user. Re-building an image every time I need to install a python package is not practical, and I currently don't have access to a linux device that has enough capacity and memory for singularity with sudo access. 

Wouldn't it be useful if we could provide writable version of an image along with read-only, possibly with different version tag?

**Comment by vsoch** [comment]
Thanks for the details for your issue. I would try installing python in the container and then interacting with the user's .local folder (install with --user), or use an updated version of singularity with --fakeroot or pull from Docker Hub with updated containers. I bet there are other ideas too - are you a member of the Singularity list? That's where I'd start. https://groups.google.com/a/lbl.gov/forum/#!forum/singularity

**Comment by MuhsinFatih** [comment]
I am already installing packages with --user, but those changes are only saved locally. If I copy the singularity image to another machine, it will not have the changes I made. Similarly, if I send a job to hpc scheduler, it won't have the changes I made.

--fakeroot seems promising, but it isn't installed here and I don't have control over singularity version. I will ask the administrator, but the point I'm trying to make is that for development it would be useful to have the writable option, and not everyone will have access to a sudo-enabled machine. Not allowing writable on singularity hub is just adding an extra unnecessary step to the process. Maybe allow it but make it require something specific, so you discourage use of it on singularity hub in general?

**Comment by vsoch** [comment]
@MuhsinFatih I cannot provide writable to you via a builder, it's out of the question for security, and it's generally bad practice for reproducibility. Singularity Hub is run at Stanford and I can support what perhaps 80-90% of users need - and --writable does not fall in that category. I can help you as much as I can to think of other solutions (and I recommend the list!) but I cannot provide this request.

**Comment by ramou** [comment]
@MuhsinFatih there;s also the option of using an overlay for mutable
elements of what you're doing. If it's the baseline that you want on
singularity-hub, you can take care of the rest outside of it. If the
HPC call writes tp its local overlay image, installing locally the
python packages needed, it would persist between calls and have no
bearing on what is stored on singularity-hub.

The key thing is that singularity runs as the user, so if you're just
talking about local installs, this works fine. If you want root-esque
installs, that would be outside the scope of what singularity
supports, if I understand correctly. Above it sounds like you're just
doing local python install stuff that you don't want to repeat every
time, so I believe that in theory the solution I suggest would work. I
haven't tried something exactly like that, and I bet the people on
singularity lists might give you more tried advice, but I think that's
probably more the direction you would benefit from heading in.

On Sun, Aug 11, 2019 at 9:18 AM Vanessasaurus <notifications@github.com> wrote:
>
> @MuhsinFatih I cannot provide writable to you via a builder, it's out of the question for security, and it's generally bad practice for reproducibility. Singularity Hub is run at Stanford and I can support what perhaps 80-90% of users need - and --writable does not fall in that category. I can help you as much as I can to think of other solutions (and I recommend the list!) but I cannot provide this request.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Stuart Thiel, P. Eng.

**Comment by vsoch** [comment]
Thanks @ramou, that's a great suggestion!

**Comment by MuhsinFatih** [comment]
> @MuhsinFatih there;s also the option of using an overlay for mutable elements of what you're doing. If it's the baseline that you want on singularity-hub, you can take care of the rest outside of it. If the HPC call writes tp its local overlay image, installing locally the python packages needed, it would persist between calls and have no bearing on what is stored on singularity-hub.

@ramou By 'overlay for mutable elements', Do you mean something like a python virtual environment or are you talking about a specific functionality that singularity has?

**Comment by vsoch** [comment]
It's sort of similar to docker - a single writable layer is added over your image, so you have writable (without sudo, etc.) Check out the docs here https://sylabs.io/guides/3.3/user-guide/persistent_overlays.html - I haven't looked or tried overlays in a while, so post issues to https://www.github.com/sylabs/singularity/issues if you have specific questions.

**Comment by MuhsinFatih** [comment]
Got it, thanks!
