### ISSUE TITLE
can't delete account

### ISSUE THREAD

**Issue by jwscook** [singularityhub/singularityhub.github.io#185]
## Link to Container Collection Log, Build, or Collection (in that order)

Trying to delete my account here https://singularity-hub.org/u/profile

### Behavior when Building Locally

I can't delete my account on the Singularity hub.

### Error on Singularity Hub

I click button `Danger Zone > Delete Account`. The button turns from red to white. The account is not deleted.

### What do you think is going on?

Some link between me and an organisation that I'm in is stopping the process from completing.

**Comment by jwscook** [comment]
It did work after all. I shouldn't be so impatient.

**Comment by vsoch** [comment]
It goes through your collections and containers, and needs to delete them, and likely this took a bit of time. I didn't receive any error notifications so there weren't any issues on the server. Thanks for reporting!
