### ISSUE TITLE
Container for racon with CUDA support builds locally but not on shub

### ISSUE THREAD

**Issue by TomHarrop** [singularityhub/singularityhub.github.io#188]
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/containers/10967/log

### Behavior when Building Locally

Builds with Singularity 3.2.0. I've run the tests included with the software in the container and they complete fine.

### Error on Singularity Hub

I'm not sure why this is failing, as there don't appear to be any errors in the log. This is the final line of the log:

```
Return value of 1.
```
A bit earlier in the log I see this

```
[34mINFO: [0m Adding help info
[34mINFO: [0m Adding labels
[34mINFO: [0m Adding environment to container
[34mINFO: [0m Adding runscript
[34mINFO: [0m Creating SIF file...
[34mINFO: [0m Build complete: /root/build/container.sif
ERROR Final image does not exist.
```

### What do you think is going on?

It's a large container (2.2 GB) and it takes a long time to build locally. Am I hitting a resource limit?

Also this software is using CUDA, could it be that something I have on my computer is required to build the container?

**Comment by vsoch** [comment]
hey @TomHarrop - it could definitely be memory (when it's creating the SIF) or missing libraries - what happens if you build this on a small instance without cuda?

**Comment by TomHarrop** [comment]
Hi Vanessa, thanks for the reply!

Here it is *without* CUDA on my machine, resulting in a 274 MB image:

```
INFO:    Build complete: racon-nocuda_1.4.7.sif
	Command being timed: "sudo singularity build racon-nocuda_1.4.7.sif ../tools/Singularity.racon-nocuda_1.4.7"
	User time (seconds): 176.84
	System time (seconds): 19.31
	Percent of CPU this job got: 33%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 9:40.54
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1029712
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 1
	Minor (reclaiming a frame) page faults: 3594199
	Voluntary context switches: 337003
	Involuntary context switches: 40475
	Swaps: 0
	File system inputs: 288
	File system outputs: 3208952
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

This no-CUDA recipe also failed to build on `shub`: https://singularity-hub.org/containers/10981/log

**Comment by vsoch** [comment]
The builder uses a secure build which doesn't have access to the same resources that your system has, e.g.

```
[WARNING:] Not mounting current directory: user bind control is disabled by system administrator
[WARNING:] Ignoring libraries bind request: user bind control disabled by system administrator
```
so my best guess is that's the issue, or when you compile it needs some library that isn't made available. Have you tried just building on Docker Hub and pulling to Singularity?

**Comment by TomHarrop** [comment]
Ok, thanks. My Docker skills aren't great, so for now I've just pushed the locally-built .sif to sylabs cloud.

If there's a switch I can use when building locally to emulate the `shub` builder (e.g. disable user binds), I'm happy to play around with the recipe to find out what I'm missing.

**Comment by vsoch** [comment]
Would it help if I helped you with a Dockerfile?

**Comment by TomHarrop** [comment]
Thanks, but I think it's OK on sylabs cloud. I could even pull it to shub from there, I guess.

I really need to learn Docker sometime!

**Comment by TomHarrop** [comment]
Hi @vsoch 

I've been having this issue again building with the Singularity 3.2.1 builder on shub. Here are two builds that failed with `singularity-builder-3-2-1-100-gb-private`, but worked with `singularity-builder-2-5-100-gb-private`:

https://singularity-hub.org/containers/11471/log
https://singularity-hub.org/containers/11455/log

I test my recipe files locally with singularity 3.2.0 before pushing them to github and both worked.

I don't know if it's something I've done to that repo. There is a failed build there that I haven't been able to delete (nothing happens when I click the trash can icon), and I haven't been able to get builds to trigger via git commits in a while (I use manual triggers for it). Builds seem fine with `singularity-builder-3-2-1-100-gb-private` on another repo of mine (https://singularity-hub.org/collections/3718). 

Sorry if I've borked something here!
Tom

**Comment by vsoch** [comment]
@TomHarrop the first file looks ok, the second file is so big I can't load it or download or otherwise view it, so I'm not sure I can help without that. It sounds like you need to debug a bit - maybe create a new repo with the recipe in question, and we can go from there?

Also, the container collection limit is 50, so you aren't seeing new builds because you're already way over (the behavior to not build on commit given over the limit is expected). :) I would strongly suggest reorganizing your build strategy to not have a monolithic repo.

**Comment by TomHarrop** [comment]
Oh crud, I thought it was 100. Will rearrange, try your suggestion and reopen if necessary, thanks.
