### ISSUE TITLE
Reduce necessary permissions on linking with github

### ISSUE THREAD

**Issue by olifre** [singularityhub/singularityhub.github.io#19]
It seems when logging in with github, permissions to read and WRITE all my personal account data and all my repositories is requested. 
I would totally be fine with read access only, which should be sufficient as far as I can see, but uncontrollable **write** access to all my repos and my profile is a bit excessive. 

Is this really needed?
It's something preventing me from linking this service with my normal github account - or an organization, even...

**Comment by vsoch** [comment]
hey @olifte! We need write to make webhooks. Do you have other suggestions?

**Comment by olifre** [comment]
> We need write to make webhooks.

Thanks for the quick reply, that already helps me to understand why it's needed. 
Though, that does not explain why write is needed also for the "personal user data" on github instead of for the repositories only. 

Maybe another solution could be to document how the webhooks need to look like, and let the more cautious users set them up themselves? 

Also, if I compare e.g. with travis-ci, here is the list of permissions they requested via oauth:
- Read org and team membership
- Access commit status
- Access deployment status
- Access user email addresses (read-only)
- Write repository hooks

i.e. no full repo access, only access to write repo hooks. That would be perfectly fine with me.

**Comment by vsoch** [comment]
Thanks @olifre ! Yes I think we can definitely be more specific about permissions asked for - I'll be sure to test this out with the next version of Shub (it will be updated right after 2.3 release)

**Comment by olifre** [comment]
> Yes I think we can definitely be more specific about permissions asked for - I'll be sure to test this out with the next version of Shub (it will be updated right after 2.3 release)

Perfect, many thanks! 
Full access to account information (including "write" for the accounts mail address - which essentially allows impersonation) is really a no-go for organizations otherwise - and it would be sad to not be able to use singularity hub just due to not-specific permissions. 

Please update this issue ticket once the permissions are more fine-grained, then I will certainly link my github to singularity hub and test it out (and recommend it to my colleagues).

**Comment by vsoch** [comment]
will do!

**Comment by vsoch** [comment]
This issue, when fixed, will also address https://github.com/singularityhub/singularityhub.github.io/issues/7

**Comment by gnperdue** [comment]
I'd like to second the requests made in this issue - it is unsettling to give over so much access.

**Comment by vsoch** [comment]
just to update you guys - this will definitely be the case for the next version of Singularity Hub. I completely agree on all points.

**Comment by vsoch** [comment]
hey @olifre ! How does this level of permissions look?

![image](https://user-images.githubusercontent.com/814322/27842763-dcd15a32-60da-11e7-8e5a-e787c13c346f.png)

The webhooks and commits do not give code access, and the account information is also read only. Would this be suitable for your group?

**Comment by olifre** [comment]
hey @vsoch ! This looks **significantly** better, I believe that's acceptable. 
Just to make sure, let's ping my colleague @wiene . 
Does the last permission imply that Singularity Hub also provides feedback for commits integrated in Github, i.e. "container build worked"? That's a cool feature!

**Comment by vsoch** [comment]
The commit status part may not even be necessary, likely being able to create (and then receive a webhook is sufficient) but I'm testing that one out to see what kind of cool stuff could be possible :)
