### ISSUE TITLE
unable to pull the container from sregistry

### ISSUE THREAD

**Issue by ashwinidr3** [singularityhub/singularityhub.github.io#194]
### Links

 - container collection:
 - GitHub repository or recipe file:

### Version of Singularity

3.2.1-1.1.el7

### Behavior when Building Locally

Write here.

### Error on Singularity Hub

There was a problem sharing your container! Submit an issue for help. 7 days. 

2.singularity run shub://container.page/test/lolcow:latest
INFO:    Downloading shub image
FATAL:   Failed to get manifest from Shub: No response received from singularity hub

### What do you think is going on?

when i try to generate a link a temporary link to download the container, i get the error "There was a problem sharing your container! Submit an issue for help. 7 days. ". also i am unable to download container via other methods given in usage tabs.

the following are the errors
1.singularity run shub://container.page/test/lolcow:latest
INFO:    Downloading shub image
FATAL:   Failed to get manifest from Shub: No response received from singularity hub

also i have converted my account to super user and admin. but i do not see the admin tab in GUI even after restarting dockerc-ompose.

any help is appreciated.
Thank you!!

**Comment by vsoch** [comment]
This is the issue board for Singularity Hub, not sregistry.
