### ISSUE TITLE
Cannot see Master branch commits when manually triggering

### ISSUE THREAD

**Issue by sgiavasis** [singularityhub/singularityhub.github.io#195]
### Links

 - container collection:
    https://singularity-hub.org/api/build/3794
 - GitHub repository or recipe file:
    https://github.com/FCP-INDI/C-PAC/blob/master/Singularity

### Error on Singularity Hub

I recently created this collection, and I'd like to manually trigger a build from Master. When I go to do so, none of the commits show up under "Select A Build". Note, this is after I enabled the "develop" branch to be an additional build, and after I selected that, I only saw commits from "develop". I turned that off and went to trigger the Master branch build and I'm getting nothing under "Select A Build" (only the -).

I try anyway, with the Recipe File filled out appropriately, and I get "You must select a commit and branch to build."

### What do you think is going on?

Seems to not be seeing the Master branch commits? I didn't try manually triggering before selecting the develop branch as an additional and I don't know if the Master branch commits would have been visible before that- not sure if switching on the additional branch and then switching off caused some kind of bug.

**Comment by vsoch** [comment]
Could you please share the link to your collection (what you copy pasted is 404)

Commits aren't specific to a branch (at least if I remember correctly) so it sounds like the request to get any commits isn't working correctly.

**Comment by sgiavasis** [comment]
Oop, sorry, try this?
https://singularity-hub.org/collections/3794

Thanks for the quick response!

**Comment by vsoch** [comment]
ok should be all set!

![Screenshot from 2019-11-15 14-29-05](https://user-images.githubusercontent.com/814322/68970144-a01d3d80-07b4-11ea-8ceb-05c5d1621605.png)

You are the first person to go over the paginated limit for your branches, so when you updated the list by requesting to see them, and since master was off, it completely removed it from the list. I just added it back in (as enabled) manually so that it shows up.

**Comment by sgiavasis** [comment]
It works!! Thank you @vsoch !

I am unsure of how I should feel regarding this dubious honor. 😆

**Comment by vsoch** [comment]
Maybe... proud!
![image](https://user-images.githubusercontent.com/814322/68972242-32671680-07a0-11ea-935a-92e83c41ee08.png)

**Comment by vsoch** [comment]
I'm guessing you are all set? I'm going to close the issue.
