### ISSUE TITLE
 collection with this repository id already exists. is this a fork or base of a repository already added?

### ISSUE THREAD

**Issue by kristyhoran** [singularityhub/singularityhub.github.io#196]
### Links

 - container collection:
 - GitHub repository or recipe file:

### Version of Singularity

Write here

### Behavior when Building Locally

Write here.

### Error on Singularity Hub

Write here.

### What do you think is going on?

Write here.

**Comment by vsoch** [comment]
If you get this message, it means that a fork of your repository (or an upstream) is already added to Singularity Hub. Each repository (and a fork of it) has a unique id on GitHub, and on Singularity Hub we only allow one repo per unique id to be added.
