### ISSUE TITLE
Build killed just before completion due to running for 2 h (error code 137)

### ISSUE THREAD

**Issue by Sparrow0hawk** [singularityhub/singularityhub.github.io#197]
### Links

 - container collection: https://singularity-hub.org/collections/3963
 - GitHub repository or recipe file: https://github.com/Sparrow0hawk/erkale_singularity/blob/master/erkale_sing 
 - Logs - https://singularity-hub.org/containers/11958/log

### Behavior when Building Locally

Builds correctly to a .sif under 2h

### Error on Singularity Hub

Build is killed just before build completes due to running to 2 h

### What do you think is going on?

Is there anyway to run this build slightly longer than 2 h as the build was killed just before it completed?

Thanks!

**Comment by vsoch** [comment]
How much memory does your host have where it builds successfully, and how long exactly does it take?

**Comment by Sparrow0hawk** [comment]
The host has 8G of RAM and takes 74m48.555s

**Comment by vsoch** [comment]
I'm thinking this isn't going to work - the builder has 1/4 the RAM and the limit is 2 hours. Are you able to build a base image (e.g., used from Docker Hub) to do some of the time intensive tasks?

**Comment by Sparrow0hawk** [comment]
I'll have a look at building a base image

**Comment by vsoch** [comment]
Sounds good, good luck!
