### ISSUE TITLE
Launch an interactive session

### ISSUE THREAD

**Issue by ChihHsuanWei** [singularityhub/singularityhub.github.io#199]
### Links

 - container collection:
 - GitHub repository or recipe file:

### Version of Singularity

Write here

### Behavior when Building Locally

Write here.

### Error on Singularity Hub

Write here.

### What do you think is going on?

Write here.

**Comment by vsoch** [comment]
Could you please clarify what your question is?

**Comment by vsoch** [comment]
Closing, please re-open with a more clear description of the issue and I'd be happy to help or answer your question.
