### ISSUE TITLE
firefox issue with certificates

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularityhub.github.io#2]
the problem is that the certificate is only for
"singularity-hub.org" but not (additionally) for
"www.singularity-hub.org" and Firefox correctly gives a warning
when connrecting to https://www.singularity-hub.org instead of
silently redirecting to https://singularity-hub.org/ as e.g. Chrome
does.

**Comment by akkornel** [comment]
Yo!

I just checked, and I don't see this problem anymore.  I checked the SSL cert, and I see the SSL cert has Subject Alternative Names set for singularity-hub.org and www.singularity-hub.org, so I think this issue has been fixed!

**Comment by vsoch** [comment]
hehe, yes I finally figured out that I could make a little configuration file with TWO names in one schwoop! Thanks for updating this issue! Closing.
