### ISSUE TITLE
singularity-hub built container has an extra blank first line in /singularity and other setup issues

### ISSUE THREAD

**Issue by alaindomissy** [singularityhub/singularityhub.github.io#20]
I am having trouble with getting a build by singuarity-hub for the following repo:
[eclip singularity-cwl pipeline](https://github.com/YeoLab/eclip-dev)

**Building locally works fine** , with:
```
sudo singularity create --size 4608   eclpi-0.1.5.99.img
sudo singularity bootstrap eclip-0.1.5.99.img Singularity
```
**Building on singularity-hub presents the following issues**  
after downloading  with `singularity pull shub://YeoLab/eclip-dev:master` I notice:
1. /singularity file has a blank line at the top before my intended first line which should be the shebang line:  `#/usr/bin/env bash`
2.  the /opt folder only has the conda subfolders , but noe of the other 10 or 12 other folders supposed to be copied into /opt and added to PATH by the Singularity builder file

I can `sudo singualrity exec +w image bash` into the container and remove the blank line at top of /singularity which makes the container a little less broken.  But I don't have a simple fix for all the missing installations in the container.

**I have tried:**
1.  to make the github repo public and private
2.  different sizes for the builder on singularity hub

**I noticed in the singularity-hub logs:**
1. a` not found 404 message`, but many other containers that work fine have the same 404 message
2. a warning about` lines too long in the Singularity file`,  I now got rid of that message after I split some of the conda install commands

**Context:**

1. singularity version for building locally :  I am using 2.2.1 
It seems singularity-hub is using version 2.2 . Is this a problem ? 
2. singularity version for pulling from singularity hub  : I am using release 2.2.99, either installed on my ubuntu laptop, or inside [the new pre-installed vagrant box ](https://atlas.hashicorp.com/singularityware/boxes/singularity-2.2.99)
3. singualrity config:  `/usr/local/etc/singularity/singularity.conf` does not have anything special in either of my singularity installations; I think... but let me know if I should upload it here 

Thanks for any help!

**Comment by vsoch** [comment]
hey @alaindomissy can you share the path to the repo (with build spec file?) The link above I get 404

![image](https://cloud.githubusercontent.com/assets/814322/26526201/30b65872-4327-11e7-9ef3-c34be17fce03.png)

**Comment by alaindomissy** [comment]
oops... the repo was private. It is now public. Please try again:
https://github.com/YeoLab/eclip-dev

**Comment by vsoch** [comment]
ah found it on shub :)

https://singularity-hub.org/containers/989/

I will take a look! Probably tomorrow because I need to have dinner. Stay tuned!

**Comment by alaindomissy** [comment]
Take you time. Thank you! And `bon appetit` ! :-)

**Comment by vsoch** [comment]
ah, ok. The quick answer is that not much building is going on at all - we had an early bug that would just cut given a long string, and in your latest build I see that bug:

```
ERROR : Overly-long string encountered.
ABORT : Retval = 255
Creating and bootstrapp
```

So what is happening is that the container is building without most of your install steps. The skeleton is there ( eg runcript) but none of the actual stuff that is supposed to happen in post. The good news is that this bug is long fixed, so when the builders are updated with 2.3 this should build without a hitch.

**Comment by vsoch** [comment]
And the 404 errors are normal / expected - I probably should reduce the verbosity because of that. It just means the builder didn't find one of the optional metadata values.

**Comment by vsoch** [comment]
`bon appetit!!` :plate_with_cutlery:

**Comment by alaindomissy** [comment]
Oh , that's great . Could I work around the bug by having only short strings in my Singuarity file ?
Should I not have the "\" continuation  to next line for bash commands ?

**Comment by alaindomissy** [comment]
`\` continuation to next line

**Comment by vsoch** [comment]
It looks like it actually has to do with the length of the %post, which triggers that error, see [this old comment](https://github.com/singularityware/singularity/issues/456#issuecomment-275712614) for the issue. I encountered this myself, and the workaround I used was to put the entire %post section in a post.sh script, and have the %post section run that. And copy the post.sh into the container during %setup. [Here is the example for my container](https://singularity-hub.org/containers/129/) and I'll include below:

```
Bootstrap: docker
From: ubuntu:trusty

%setup

    cp post.sh $SINGULARITY_ROOTFS

%runscript

    if [ $# -eq 0 ]; then
        echo "\nThe following software is installed in this image:"
        column -t /Software/.info | sort -u --ignore-case        
        echo "\Note that some Anaconda in the list are modules and note executables."
        echo "Example usage: analysis.img [command] [args] [options]"  
    else
        exec "$@"
    fi
        
%post

    chmod u+x /post.sh
    ./post.sh
```

The drawback with this approach is that, given that something fails in post, you won't get it necessarily caught by Singularity. However, given that you know your post is bug free, it should be a good work around to build the container.

**Comment by alaindomissy** [comment]
Ok great... It is time to let you eat! Thank you !

**Comment by vsoch** [comment]
hey @alaindomissy any updates on this after testing with the new builders?

**Comment by alaindomissy** [comment]
The trick of splitting Singularity into separate setup.sh and post.sh worked like a charm with the old builders. That was great. I have now moved on to the new builder based on singularity 2.3 and returned to having a single Singularity file with all configuration into its different sections. It is working well. Thanks

**Comment by alaindomissy** [comment]
T
