### ISSUE TITLE
Manually triggering builds not working

### ISSUE THREAD

**Issue by sjw42** [singularityhub/singularityhub.github.io#203]
### Links

 - container collection:
 - GitHub repository or recipe file:

### Version of Singularity

n/a

### Behavior when Building Locally

n/a

### Error on Singularity Hub

I attempted to manually trigger a build for two of my containers. A notification that the build would be placed in the queue was shown, but this does not appear to have happened (builds never started). I apologize if I am not submitting this to the correct place or providing the right information. 

### What do you think is going on?

I do not believe that I have exceeded any of the build/view limits, so I am not sure what the problem might be. Again, I am sorry if this is not the right forum for seeking assistance, and thank you for your time.

**Comment by vsoch** [comment]
Can you please share the name of the container and collection? I can look into this for you tomorrow.

**Comment by sjw42** [comment]
It wasn't showing up previously, but one of the containers (sjw42/fmriprep_icsaci) did build after all, so it just need to give the one that didn't (sjw42/NiBetaSeries) more time. Either that, or there may be an issue with my recipe file - it is a new collection that I am trying to get working. Sorry for taking up your time, and thanks very much for the quick response.

**Comment by vsoch** [comment]
No worries! Please ping here if you need any help, and I’m always glad to take a look over a recipe.
