### ISSUE TITLE
New commit not building

### ISSUE THREAD

**Issue by jzhanghzau** [singularityhub/singularityhub.github.io#204]
### Links

 - container collection: https://singularity-hub.org/collections/3886
 - GitHub repository or recipe file:https://github.com/jzhanghzau/thesis

### Version of Singularity

the latest .

### Behavior when Building Locally

The last time it worked for me was on Jan 23,but yeasterday when i did a new commit,it had no response.

### Error on Singularity Hub

No containers found in the pending queue.

### What do you think is going on?
no idea,i aslo checked the webhooks.

**Comment by vsoch** [comment]
Ah thank you for reporting this! There was a worker that died (and need to be started again) that totally missed my awareness. I just got him back up and running, and he's working through his back log now. If you want to be extra careful you can give it another try sometime tomorrow. Sorry about the issue!

**Comment by jzhanghzau** [comment]
thanks ,it works for me again.
