### ISSUE TITLE
java heap space error

### ISSUE THREAD

**Issue by RichardCorbett** [singularityhub/singularityhub.github.io#208]
### Links

 - container collection:   https://singularity-hub.org/containers/12557/log
 - GitHub repository or recipe file: https://github.com/RichardCorbett/PROFYLE_TMB

### Version of Singularity

Write here

### Behavior when Building Locally

Hi folks I can build this locally on my network without any special switches. ie:
`sudo singularity build  --force PROFYLE_TMB PROFYLE_TMB.recipe
`
### Error on Singularity Hub

my build is failing when some java code is supposed to run to reformat some files after they are downloaded.
```
...
00:01:07 Loading interactions from : /usr/TMB/snpEff/./data/GRCh37.75/interactions.bin
java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOf(Arrays.java:3332)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
...
```

### What do you think is going on?

It looks like the java command is asking for 16Gb, perhaps that is more than is allocated to the build jobs on singularityhub?

**Comment by vsoch** [comment]
Yes, unfortunately the Singularity Hub instances only have about 3.75 GB of memory. You can try:

 - decreasing the requested amount, and I'd give it some buffer
 - building some base on Docker Hub and pulling said base after the memory operation is done
 - using sylabs cloud

**Comment by RichardCorbett** [comment]
Thanks.   I tried a build locally using only 3Gb but ran out of RAM and it crashed.   I'll take a look into using sylabs.

**Comment by vsoch** [comment]
Great! Sorry I can't offer more than that, I've been running this for almost 4 years now, and also procuring funding, refactoring when needed, responding to issues, and the thing that I definitely can't do is give total freedom to use expensive resources. Good luck with Sylabs Cloud, closing issue.

**Comment by RichardCorbett** [comment]
No problem.   I really appreciate your responsiveness.   Best of luck!

**Comment by vsoch** [comment]
Thanks! It's almost dinner here, so for this tiny bloop of space time, all is well! haha ;)
