### ISSUE TITLE
el7 builders possible?

### ISSUE THREAD

**Issue by adriansev** [singularityhub/singularityhub.github.io#209]
### Links
 - container collection:
https://singularity-hub.org/collections/4175

 - GitHub repository or recipe file:
https://github.com/adriansev/cvmfs2go

### Version of Singularity
singularity version 3.5.3-1.1.el7

### Behavior when Building Locally
no problem, succesful

### Error on Singularity Hub
Nothing happens : No containers found in the pending queue.

### What do you think is going on?
well, i use yum bootstrap so i need a centos7 host
is it possible?
Thank you!

**Comment by vsoch** [comment]
Please try a Docker bootstrap with a centos image, the host is not centos.

**Comment by adriansev** [comment]
ok, thanks, this is a no-go for me.
