### ISSUE TITLE
Cloud builder singularity-builder-2-3-50gb is not accepted, but it's in the drop-down menu

### ISSUE THREAD

**Issue by mvdoc** [singularityhub/singularityhub.github.io#21]
### Error on Singularity Hub

I temporarily switched to `singularity-builder-2-2-1-50gb`, and upon reverting back to the default I found I can't, see error here:

![image](https://cloud.githubusercontent.com/assets/6150554/26704982/f4f6d040-4700-11e7-91dc-824cc8f47722.png)

### What do you think is going on?

Make sure that `singularity-builder-2-3-50gb` is among the accepted values?

**Comment by vsoch** [comment]
hey @mvdoc ! I just found the bug and it will be resolved when I restart the server. It looks like the Google metadata call was having some trouble for an image, so I'm going to debug that first. I will post here when the server is restarted (fixing the above issue) stay tuned!

**Comment by vsoch** [comment]
Hey @mvdoc could you give this another test? The builders are updated, as is the string error. I'm also writing up some docs that help tell the user how to update their builder, since current collections won't have it done automatically.

**Comment by mvdoc** [comment]
@vsoch it works now, thanks!

**Comment by vsoch** [comment]
woohoo! Awesome!
