### ISSUE TITLE
how to trigger a manual build

### ISSUE THREAD

**Issue by adriansev** [singularityhub/singularityhub.github.io#210]
### Links
 - container collection:
https://singularity-hub.org/collections/4183
 - GitHub repository or recipe file:
https://github.com/adriansev/el7hep

### Version of Singularity
3-4-2-100-gb

The problem is that i cannot trigger the build on master.
I did many times (now i'm blocked) trigger-> select dash and Singularity and Build but nothing happened and no error messages were shown.
Any idea what is going on?
Thank you!

**Comment by vsoch** [comment]
You can only access an interface 25/day (or for some, just 10) so if you are blocked you'll need to wait until the next day. Once you are unblocked, please walk me through what you are trying to do, with screenshots if needed, and the error messages / other that you see. Thanks!

**Comment by vsoch** [comment]
It looks like your Singularity recipe is a symbolic link, which if I recall correctly the builder should be able to handle, but you might be better off specifying the .def file directly. Also please confirm all of the settings you are using in your Collection Settings page - for example, there is an option to do a manual trigger for a build (and I suggest you try this first). Chat tomorrow!

**Comment by adriansev** [comment]
So, i found the problem: when triggering the manual build it request a commit, and i was taking the `-` as a default head instead of missing variable. As soon as i actually selected the commit the build started. Would be possible to have the default entry `-` to mean the head of the branch? (in this case the master)?   
Thank you!

**Comment by vsoch** [comment]
Great! The `-` is just indicative of an empty select box - I never thought that someone would choose it as their commit! I'd be happy to look into if there is some way to remove / disable this empty value.

**Comment by adriansev** [comment]
Well, i would propose to have `HEAD` as default value, with the meaning of the head of the branch...
given the possibility and recommendation to have versions mapped to branches, most often the intent of a builder would be to build the latest version of the said branch
