### ISSUE TITLE
Webhooks are rejected with 500

### ISSUE THREAD

**Issue by ctpelok77** [singularityhub/singularityhub.github.io#216]
### Links

 - container collection:
https://singularity-hub.org/collections/4449

 - GitHub repository or recipe file:
https://github.com/ctpelok77/fd-red-black-postipc2018

### Version of Singularity
Tried all three

### Behavior when Building Locally

Not tried

### Error on Singularity Hub

Not showing errors, not showing any activity.

### What do you think is going on?

Webhooks from github are rejected with error code 500.
Here is the body of the response:
{"status": "error", "message": "This branch is not actively building. See https://singularity-hub.org/collections/4449/branches/edit"}

The build is enabled, I am building from master.

**Comment by ctpelok77** [comment]
Not sure if that's related, but I also cannot choose a commit for manual build. I can only see the "-" and the field is not writeable.

**Comment by vsoch** [comment]
hey @ctpelok77 ! I know this error well - you've exhausted the branch limit for one call to the API (how we get branches for a collection) so that master isn't in the list. Here is what Singularity Hub sees:

```
{'branches': {'emil-new-integration': False,
  'hcea-cleanup': False,
  'ijcai-2011': False,
  'ipc-2011-fixes': False,
  'issu139': False,
  'issue-114': False,
  'issue-149': False,
  'issue-289': False,
  'issue104': False,
  'issue107': False,
  'issue108': False,
  'issue109': False,
  'issue112': False,
  'issue116': False,
  'issue119': False,
  'issue120': False,
  'issue122': False,
  'issue123': False,
  'issue132': False,
  'issue133': False,
  'issue133new': False,
  'issue134': False,
  'issue17': False,
  'issue22': False,
  'issue26': False,
  'issue28': False,
  'issue44': False,
  'issue67': False,
  'issue77': False,
  'issue89': False}}
```
This has only happened once before in the ~4 years or so, so it's not something I've refactored the server to fit (I am very conservative about making changes generally). What I can do now is add the branch to your collection and remove the others, and what I'd suggest you do moving forward is to go into your GitHub repository settings and have it automatically clean up branches.

Your collection is saved with master set to build now:

```
{'branches': {'master': True}}
```
Could you please give it a try?

The reason you couldn't get commits is the same - the commits were derived from active branches (and you had none).

Sorry for the trouble, but hopefully these suggestions will work for you!

**Comment by ctpelok77** [comment]
It works, thank you! 
I often work with repos that have a large number of branches. Maybe worth making sure that the default branch is in the list?

**Comment by vsoch** [comment]
The default branch doesn't actually come back as anything special in the response, it's just one in the list!

**Comment by vsoch** [comment]
Let me do a quick test to see how easy it would be to paginate, brb.

**Comment by vsoch** [comment]
Wow, you have a LOT of branches.

```
len(available_branches)
474
```

**Comment by ctpelok77** [comment]
There is a "default_branch" property in the response (see example here: https://developer.github.com/v3/repos/#get )

**Comment by vsoch** [comment]
okay I just did a (manual) update so you would actually have 474 (yikes!) if you want to take a look - this won't go live until the next server update which wouldn't be for a few months.

**Comment by vsoch** [comment]
The call done is https://api.github.com/repos/ctpelok77/fd-red-black-postipc2018/branches.

**Comment by vsoch** [comment]
It's not really a sure thing to just assume that the user wants the default branch, there is actually no good way to predict what other branches they might want to build. So we either truncate at 30 and give the user advice to manage branches, or the update I just did, which paginates the request to return all branches found.

**Comment by ctpelok77** [comment]
I was only suggesting that if you go with truncating at, say, 30, it might be helpful to many to add the default branch to that small subset. Obviously, it will not cover all cases.

**Comment by vsoch** [comment]
Sorry I can be more clear - I already updated the call to the branches endpoint to paginate.

**Comment by ctpelok77** [comment]
Appreciate your help! I guess we can close the issue now

**Comment by vsoch** [comment]
I'll add the finished label (and we can leave open) and that's an indicator / reminder to future me to do some sanity checks when I next do server work. Thanks for reporting the issue!

**Comment by vsoch** [comment]
Hey just a quick update - this will go live in 2 weeks (after August 21st).

**Comment by vsoch** [comment]
Okay, change is live! This should no longer be an issue. Thanks for your patience!

**Comment by ctpelok77** [comment]
Thank you for handling this issue so efficiently!
