### ISSUE TITLE
Singularity recipe not building. Any help much appreciated!

### ISSUE THREAD

**Issue by tjhendrickson** [singularityhub/singularityhub.github.io#217]
### Links

 - container collection: 3125
 - GitHub repository or recipe file: https://github.com/tjhendrickson/CORTADO

### Version of Singularity

Write here

### Behavior when Building Locally

Within the Singularity recipe file I am attempting to install Miniconda and required python packages. I copied and pasted what I believe are the offending lines in the Singularity recipe:
**wget https://repo.anaconda.com/miniconda/Miniconda2-py27_4.8.3-Linux-x86_64.sh -O /opt/Miniconda2.sh
bash /opt/Miniconda2.sh -b -p /opt/Miniconda2
export PATH="/opt/Miniconda2/bin:${PATH}"
/opt/Miniconda2/bin/conda install -y -q -c conda-forge nibabel=3.0.1 cifti=1.1 pandas=1.0.1 nilearn=0.6.2 scikit-learn=0.22.2.post1**.

I made a few mods to point Miniconda to a different folder that I had access to. It runs without issue.

### Error on Singularity Hub

**+ bash /opt/Miniconda2.sh -b -p /opt/Miniconda2
0%| | 0/37 [00:00Extracting : pysocks-1.7.1-py27_0.conda: 0%| | 0/37 [00:00 + /opt/Miniconda2/bin/conda install -y -q -c conda-forge nibabel=3.0.1 cifti=1.1 pandas=1.0.1 nilearn=0.6.2 scikit-learn=0.22.2.post1
Building graph of deps: 0%| | 0/7 [00:00 File "/opt/Miniconda2/bin/conda", line 13, in
sys.exit(main())
File "/opt/Miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 150, in main
return conda_exception_handler(_main, *args, **kwargs)
File "/opt/Miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
return_value = exception_handler(func, *args, **kwargs)
File "/opt/Miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1082, in __call__
return self.handle_exception(exc_val, exc_tb)
File "/opt/Miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1115, in handle_exception
return self.handle_application_exception(EncodingError(exc_val), exc_tb)
File "/opt/Miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1129, in handle_application_exception
self._print_conda_exception(exc_val, exc_tb)
File "/opt/Miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1133, in _print_conda_exception
print_conda_exception(exc_val, exc_tb)
File "/opt/Miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1056, in print_conda_exception
stderrlog.error("
%r
", exc_val)
File "/opt/Miniconda2/lib/python2.7/logging/__init__.py", line 1200, in error
self._log(ERROR, msg, args, **kwargs)
File "/opt/Miniconda2/lib/python2.7/logging/__init__.py", line 1293, in _log
self.handle(record)
File "/opt/Miniconda2/lib/python2.7/logging/__init__.py", line 1302, in handle
if (not self.disabled) and self.filter(record):
File "/opt/Miniconda2/lib/python2.7/logging/__init__.py", line 617, in filter
if not f.filter(record):
File "/opt/Miniconda2/lib/python2.7/site-packages/conda/gateways/logging.py", line 60, in filter
record.msg = record.msg % new_args
File "/opt/Miniconda2/lib/python2.7/site-packages/conda/__init__.py", line 78, in __repr__
return '%s: %s' % (self.__class__.__name__, self.__unicode__())
File "/opt/Miniconda2/lib/python2.7/site-packages/conda/__init__.py", line 74, in __unicode__
res = '%s' % (new_message % new_kwargs)
ValueError: unsupported format character '|' (0x7c) at index 472
ABORT: Aborting with RETVAL=255
Image failed build: build end 312 seconds.
Return value of 1.
End Time: Wed Jun 17 18:42:46 UTC 2020.**

### What do you think is going on?

I am not totally sure, it seems like it should run. I know that Singularity recipes behaves poorly when user input is requested so I added the "-y -q" to the conda install command at some point to try and avoid that issue. That, of course, did not do the trick. I am not sure that there may be an odd carriage return somewhere? That is the only thing I can think of.

Best,

-Tim

**Comment by vsoch** [comment]
Have you built this recipe successfully locally?

**Comment by vsoch** [comment]
okay, I just tried to build your container locally and I got the same exit with failure:

```

Package scipy conflicts for:
nilearn=0.6.2 -> scipy
scikit-learn=0.22.2.post1 -> scipy
nibabel=3.0.1 -> scipy
cifti=1.1 -> nibabel -> scipy

Package setuptools conflicts for:
python=2.7 -> pip -> setuptools
scikit-learn=0.22.2.post1 -> joblib[version='>=0.11'] -> setuptools
nilearn=0.6.2 -> joblib -> setuptools

FATAL:   While performing build: while running engine: exit status 1
[1]+  Done                    gedit rse/main/__init__.py  (wd: ~/Desktop/Code/rseng/rse)
(wd now: /tmp/CORTADO)
```
Let me look at the error message and see if I can offer any help!

**Comment by vsoch** [comment]
This looks like it's a dependency issue - the conflicts are not able to be resolved, and you can see that in the full error message:

```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                              

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - nibabel=3.0.1 -> python[version='>=3.5.1']
  - nilearn=0.6.2 -> python[version='>=3.5']
  - pandas=1.0.1 -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=2.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libopenblas conflicts for:
nibabel=3.0.1 -> numpy[version='>=1.12'] -> libopenblas[version='>=0.2.20,<0.2.21.0a0|>=0.3.2,<0.3.3.0a0|>=0.3.3,<1.0a0']
scikit-learn=0.22.2.post1 -> scipy -> libopenblas[version='>=0.2.20,<0.2.21.0a0|>=0.3.3,<1.0a0|>=0.3.2,<0.3.3.0a0']
pandas=1.0.1 -> numpy[version='>=1.14.6,<2.0a0'] -> libopenblas[version='>=0.3.2,<0.3.3.0a0|>=0.3.3,<1.0a0']
cifti=1.1 -> numpy -> libopenblas[version='>=0.2.20,<0.2.21.0a0|>=0.3.2,<0.3.3.0a0|>=0.3.3,<1.0a0']
nilearn=0.6.2 -> scikit-learn -> libopenblas[version='>=0.2.20,<0.2.21.0a0|>=0.3.3,<1.0a0|>=0.3.2,<0.3.3.0a0']

Package packaging conflicts for:
cifti=1.1 -> nibabel -> packaging[version='>=14.3']
nilearn=0.6.2 -> nibabel -> packaging[version='>=14.3']

Package libgcc conflicts for:
nilearn=0.6.2 -> scipy -> libgcc
nibabel=3.0.1 -> scipy -> libgcc
scikit-learn=0.22.2.post1 -> scipy -> libgcc

Package nibabel conflicts for:
nilearn=0.6.2 -> nibabel
cifti=1.1 -> nibabel

Package six conflicts for:
nibabel=3.0.1 -> h5py -> six
cifti=1.1 -> six
pandas=1.0.1 -> python-dateutil[version='>=2.6.1'] -> six[version='>=1.5']
nilearn=0.6.2 -> nibabel -> six

Package numpy conflicts for:
nilearn=0.6.2 -> numpy
nilearn=0.6.2 -> nibabel -> numpy[version='1.10.*|1.11.*|1.13.*|>=1.12|>=1.13|>=1.11.3,<2.0a0|>=1.9|>=1.9.3,<2.0a0|>=1.14.6,<2.0a0|1.12.*|>=1.15.1,<2.0a0|>=1.11|>=1.18.1,<2.0a0']

Package _libgcc_mutex conflicts for:
scikit-learn=0.22.2.post1 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='conda_forge|main']
python=2.7 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='conda_forge|main']
pandas=1.0.1 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex[version='*|0.1',build='conda_forge|main']

Package ca-certificates conflicts for:
cifti=1.1 -> python -> ca-certificates
python=2.7 -> ca-certificates

Package pytz conflicts for:
nilearn=0.6.2 -> matplotlib-base -> pytz
pandas=1.0.1 -> pytz[version='>=2017.2']

Package scipy conflicts for:
nilearn=0.6.2 -> scipy
scikit-learn=0.22.2.post1 -> scipy
nibabel=3.0.1 -> scipy
cifti=1.1 -> nibabel -> scipy

Package setuptools conflicts for:
python=2.7 -> pip -> setuptools
scikit-learn=0.22.2.post1 -> joblib[version='>=0.11'] -> setuptools
nilearn=0.6.2 -> joblib -> setuptools
```

**Comment by vsoch** [comment]
The error that you see on shub is likely that the console doesn't support one of the characters printed in the output above, it's mostly a distraction from the main issue. To fix this, you'll have to figure out how to resolve dependencies. Why are you using Python 2, to be curious? It's been deprecated now a while, and a lot of the software you need has much more updated versions.

Anyway, I'm glad to help, although I think this issue is outside of the scope of a singularity hub builder.

**Comment by vsoch** [comment]
I'm testing it for you now with Miniconda 3.

**Comment by vsoch** [comment]
Try this - it changes the miniconda install and that's it. It went through the conda install fine, and I pressed control+c at the FSL install, so it would be worth testing to see if it completely builds.

```
Bootstrap: docker

From: ubuntu:trusty-20170119

%files

run.py /run.py
modified_files/generate_level1_fsf.sh /generate_level1_fsf.sh
modified_files/generate_level2_fsf.sh /generate_level2_fsf.sh
modified_files/RestfMRILevel1.sh /RestfMRILevel1.sh
modified_files/RestfMRILevel2.sh /RestfMRILevel2.sh
rsfMRI_seed.py /rsfMRI_seed.py
modified_files/task-rest_level1.fsf /task-rest_level1.fsf
modified_files/task-rest_level2.fsf /task-rest_level2.fsf
modified_files/91282_Greyordinates.dscalar.nii /91282_Greyordinates.dscalar.nii


%environment
export LC_ALL=C
export CARET7DIR=/opt/workbench/bin_rh_linux64
export OS=Linux
export FS_OVERRIDE=0
export FIX_VERTEX_AREA=
export FSF_OUTPUT_FORMAT=nii.gz
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
export PYTHONPATH=""
export FSLDIR=/usr/local/fsl
export FSL_DIR="${FSLDIR}"
export FSLOUTPUTTYPE=NIFTI_GZ
export PATH=/usr/lib/fsl/5.0:$PATH
export FSLMULTIFILEQUIT=TRUE
export POSSUMDIR=/usr/share/fsl/5.0
export LD_LIBRARY_PATH=/usr/local/fsl/lib:${LD_LIBRARY_PATH}
export FSLTCLSH=/usr/bin/tclsh
export FSLWISH=/usr/bin/wish
export FSLOUTPUTTYPE=NIFTI_GZ

%post

# Make local folders/files
mkdir /share
mkdir /scratch
mkdir /local-scratch
mkdir /input_dir
mkdir /output_dir
mkdir /fsf_template_dir
touch /parcel_dlabel.nii

# Install basic utilities
apt-get -qq update
apt-get install -yq --no-install-recommends libquadmath0 libglib2.0-0 python wget bc bzip2 ca-certificates libgomp1 tar tcsh unzip git libgomp1 perl-modules curl libgl1-mesa-dev libfreetype6 libfreetype6-dev


# Install conda and needed python tools
cd /opt
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda
export PATH="/opt/conda/bin:${PATH}"
/opt/conda/bin/conda install -y -q -c conda-forge nibabel=3.0.1 cifti=1.1 pandas=1.0.1 nilearn=0.6.2 scikit-learn=0.22.2.post1

# Install the validator 0.26.11, along with pybids 0.6.0
apt-get update
apt-get install -y curl
curl -sL https://deb.nodesource.com/setup_10.x | bash -
apt-get remove -y curl
apt-get install -y nodejs
npm install -g bids-validator@0.26.11
/opt/conda/bin/pip install git+https://github.com/INCF/pybids.git@0.6.0

# Install Connectome Workbench version 1.3.2
apt-get update
cd /opt
wget http://brainvis.wustl.edu/workbench/workbench-rh_linux64-v1.3.2.zip
unzip workbench-rh_linux64-v1.3.2.zip
export PATH=/opt/workbench/bin_rh_linux64:${PATH}


# Upgrade our libstdc++
echo "deb http://ftp.de.debian.org/debian stretch main" >> /etc/apt/sources.list
apt-get update
apt-get install -y --force-yes libstdc++6 nano

# Install FSL 6.0.1 along with ubuntu dependencies
apt-get update
cd /opt
wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py
/usr/bin/python fslinstaller.py -d /usr/local/fsl -E -V 6.0.1 -q -D
export FSLDIR=/usr/local/fsl
. ${FSLDIR}/etc/fslconf/fsl.sh
export PATH=${FSLDIR}/bin:${PATH}


# Make scripts executable
chmod +x /run.py /rsfMRI_seed.py /generate_level1_fsf.sh /generate_level2_fsf.sh /RestfMRILevel1.sh /RestfMRILevel2.sh /task-rest_level1.fsf /task-rest_level2.fsf

%runscript

exec /run.py "$@"
```

**Comment by tjhendrickson** [comment]
Wow thank you so much Vanessa!

Thank you for going through all of this testing. Part of the issue here is
that due to COVID and working from home I no longer have a machine to build
containers locally. I suppose I could look into whether I could easily do
this with my windows laptop... Anyway, I've been using Singularity Hub to
test my builds for the time being, but it is not as verbose as local builds.

I do not have a good reason why I was using python2, it was the version of
python I used for previous builds. Much of my other software is in python3
anyway and since it is preventing the build it makes sense to port over to
python3.

Best,

-Tim

**Comment by vsoch** [comment]
Glad to help!
