### ISSUE TITLE
How does singularity hub deal with github repository renaming ? not reflected in my collections

### ISSUE THREAD

**Issue by cokelaer** [singularityhub/singularityhub.github.io#219]
### Links

 - container collection:   https://singularity-hub.org/collections/4586
 - GitHub repository or recipe file: github.com/cokelaer/damona

### Version of Singularity

This is about the singularity_hub  rather than singularity itself

### Behavior when Building Locally

looks good locally and on singularity hub

### Error on Singularity Hub

1. I had a repository names github.com/cokelaer/ngstools
2. I renamed it into github.com/cokelaer/damona
3. I rebuild a recipe online and everything went well
4. Yet, the name of the repository on the web site https://singularity-hub.org/collections/4586 is still cokelaer/ngstools

Does it mean I have to delete the current collection, recreate a new one and rebuild all singularity image or do we have a better solution ? 

### What do you think is going on?

Since the rebuild of a container worked after a rebuild, I believe this is just a question of renaming the repository on the HTML page.

**Comment by vsoch** [comment]
I could change this for you, would that work? The repository is actually stored based on its id (a number) which is why it still works. The name is mostly metadata that is captured when you first connect.

**Comment by vsoch** [comment]
okay I've confirmed this collection belongs to you and does redirect to the new name, so I've changed the name - please take a look!

**Comment by cokelaer** [comment]
what about the uri ? they seem to still have the previous name ? thanks

**Comment by vsoch** [comment]
Okay check now!

**Comment by cokelaer** [comment]
great. it works. thanks for quick reply and fix. I let you close the issue I suppose.

**Comment by vsoch** [comment]
Sure thing, happy to close the issue and help out!
