### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by belledon** [singularityhub/singularityhub.github.io#22]
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/containers/1056/log

### Behavior when Building Locally

Bootstrap completes and container is operational

### Error on Singularity Hub

```
Running test scriptlet
Finalizing Singularity container
/tmp/tmpw95c4ays/image
DEBUG:shub_builder:Built image: /tmp/tmpw95c4ays/b340d5cb482e863b562e3999a975c4c5
INFO:shub_builder:Final time of build 195 seconds.
INFO:shub_builder:Singularity 2.3-master.gf737013 being used.
Traceback (most recent call last):
File "", line 1, in 
File "/usr/local/lib/python3.5/dist-packages/singularity/build/google.py", line 245, in run_build
params=params)
File "/usr/local/lib/python3.5/dist-packages/singularity/build/main.py", line 191, in run_build
old_version=old_version)
File "/usr/local/lib/python3.5/dist-packages/singularity/package.py", line 160, in package
file_obj,tar = get_memory_tar(image_path)
File "/usr/local/lib/python3.5/dist-packages/singularity/reproduce.py", line 513, in get_memory_tar
byte_array = cli.export(image_path)
File "/usr/local/lib/python3.5/dist-packages/singularity/cli.py", line 220, in export
output = self.run_command(cmd,sudo=sudo)
File "/usr/local/lib/python3.5/dist-packages/singularity/cli.py", line 81, in run_command
output = run_command(cmd,suppress=suppress) # suppress doesn't make difference here
File "/usr/local/lib/python3.5/dist-packages/singularity/utils.py", line 113, in run_command
output, err = process.communicate()
File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
stdout, stderr = self._communicate(input, endtime, timeout)
File "/usr/lib/python3.5/subprocess.py", line 1745, in _communicate
stdout = b''.join(stdout)
MemoryError
```

### What do you think is going on?

I set the container to be 10GB which makes sense that it wouldn't load into ram for a job (assuming you are building these on a cluster). This container is fairly bare bones. The majority of the space is probably occupied by the nvidia driver. Other than that, there are a few python modules. I did not play around with the smallest possible size but I think that I tried around 5GB and it complained about space during bootstrapping when building locally.

**Comment by vsoch** [comment]
ok, I'm testing this now. Thankfully I kept a boolean variable that can turn on/off using memory for the tar - you can imagine memory is a nice solution given that you have (smaller) images and want to do quick operations with the tar, but it's not optimal for this case! I will let you know when I finish testing and update singularity-python. I think it should be able to install the updated version (from pip) and we won't need to regenerate the builders, so we will have to test to see if it works. I'll let you know when to push again - stay tuned!

**Comment by vsoch** [comment]
ok (I think) this is where it bugged out before - generating the image:

```
>>> image_package = package(image_path=image,
...                                 spec_path=params['spec_file'],
...                                 output_folder=build_dir,
...                                 sudopw='',
...                                 remove_image=True,
...                                 verbose=True,
...                                 old_version=True)
DEBUG:shub_builder:Found runscript.
INFO:shub_builder:Adding software list to package.
DEBUG:shub_builder:Adding Singularity to package...
DEBUG:shub_builder:Adding VERSION to package...
DEBUG:shub_builder:Adding runscript to package...
DEBUG:shub_builder:Adding folders.txt to package...
DEBUG:shub_builder:Adding files.txt to package...
DEBUG:shub_builder:Package created at /tmp/build/image2.img.zip
```
the above is generated using the (old way) which is singularity export to a file (.tar) instead of to memory, and reading as bytes.

**Comment by vsoch** [comment]
oh by the way, there was one pip install that failed when I was testing, this one:

```
python3 -m pip install myavi
Collecting myavi
  Could not find a version that satisfies the requirement myavi (from versions: )
No matching distribution found for myavi
```

**Comment by vsoch** [comment]
okey doke - the new version (with old_version=True) to not use the memory tar is uploaded to pypi! If you wouldn't mind, could you commit again to trigger a build? If it's the case that the builder updates with pip, then it should build (or at least not hit that same bug). If it's the case that I need to update the builder itself, then you'll have to give me a bit more time to do that :)  Thanks for your help with this!

**Comment by belledon** [comment]
Oops, sorry forgot to mention that I made another branch `chainer_v2.0` without `myavi`. I triggered both now.

**Comment by belledon** [comment]
All good here. The container builds!

**Comment by vsoch** [comment]
Woohoo! So good to hear!! Feel free to close the issue, and please poke again if trouble arises.

**Comment by belledon** [comment]
Thanks again for all your help!
