### ISSUE TITLE
build error on singularity-hub (is my build too long ?)

### ISSUE THREAD

**Issue by cokelaer** [singularityhub/singularityhub.github.io#220]
### Links

 - container collection: 4586
 - GitHub repository or recipe file: 
https://github.com/cokelaer/damona/blob/master/recipes/conda/Singularity.conda_4.7.12

### Version of Singularity

singularity hub. latest version on local

### Behavior when Building Locally

Generates a 300Mb image is a few minutes

### Error on Singularity Hub

The build finishes with an error. No obvious message from the log here: https://singularity-hub.org/containers/13838/log

### What do you think is going on?

The build seems to take lots of time on the singularity hub. This may be the issue. The recipes installs some librairies with apt-get, then I install a conda version. It looks like the build stops at that point. Maybe

**Comment by vsoch** [comment]
hey @cokelaer - your recipe link is 404, but based on the path I think you are hitting this issue. https://github.com/singularityhub/singularityhub.github.io/issues/215. I won't be able to fix this until it's time for server updates, so in the meantime you can try building recipes from the root, or using an older builder.

**Comment by cokelaer** [comment]
@vsoch, thanks. I fixed thelink (for book keeping and help you). I rebuilt the image locally in debug mode and also tto get some info. 
so this is with version 3.6.0 of singularity and it took 277s (user time). 

This is the final line:

    277.34user 24.02system 2:00.36elapsed 250%CPU (0avgtext+0avgdata 909076maxresident)k

so 9Gb of memory. Also,  one warning at the end:

    WARNING: /root/.conda/pkgs does not exist

I do not think this is an issue since the image built and works properly.

When you say *you can try building recipes from the root, or using an older builder.*, what do you mean from the root ? the build requires the sudo, which I use. do you mean something else ? thanks

**Comment by vsoch** [comment]
If your recipe is located in a subfolder of your repository, the build will fail (this is a known bug) so you should put it in the base (or the root) of the repository, not in a subfolder.

**Comment by cokelaer** [comment]
hum, I'm quite surprise since the other recipes worked and there are also in sub-directories at the same level ?

**Comment by vsoch** [comment]
It's a bug only with a few versions of the builder, so it could be that you are using a version that doesn't have it.

**Comment by cokelaer** [comment]
I see. one more question then, what is the current version of singularity on the server and do you an estimate date for the server update ? thanks in advance

**Comment by vsoch** [comment]
You should be able to see the singularity version that your builders are using in your collection settings. For updates, depending on how busy I am it will likely be sometime in the fall or at the end of the year. this year is a bit different because the whole server needs updating which is a lot more work so I might wait until I do that.

**Comment by cokelaer** [comment]
I see. I had version 2.5 I believe ;I switched to 3.4 and will have a go.

**Comment by cokelaer** [comment]
same results. I guess I'll wait for the next update. You can close the issue; thanks again for the quick feedbacks

**Comment by vsoch** [comment]
Thanks @cokelaer ! Just an update for you - see my message here - https://github.com/singularityhub/singularityhub.github.io/issues/215#issuecomment-670771506 I'll have a fix for you to test in two weeks (likely August 21st morning or evening). I'm going to close the issue here since it's represented in #215. Thanks again for reporting!
