### ISSUE TITLE
Final image does not exist after build complete message

### ISSUE THREAD

**Issue by ftabaro** [singularityhub/singularityhub.github.io#221]
### Links

 - container collection: https://singularity-hub.org/collections/4638
 - GitHub repository or recipe file: https://github.com/ftabaro/MethylSnake/blob/master/singularity/Singularity

### Version of Singularity

Tried both with 3.2.1 and 3.4.2

### Behavior when Building Locally

Locally on 3.5.3 builds correctly

### Error on Singularity Hub

Build completes, final image does not exist and log file prints more compilation commands.

```
[34mINFO: [0m Build complete: /root/build/container.sif
ERROR Final image does not exist.

gcc -I"/usr/local/lib64/R/include" -DNDEBUG -I/usr/local/include -fvisibility=hidden -fpic -g -O2 -c slice-assign-array.c -o slice-assign-array.o

gcc -I"/usr/local/lib64/R/include" -DNDEBUG -I/usr/local/include -fvisibility=hidden -fpic -g -O2 -c slice-assign.c -o slice-assign.o
...
```
Full log: https://www.dropbox.com/s/awfkejpcx3w2gbs/shub.txt?dl=0

### What do you think is going on?

Some async error? Shub searching for image before actual container compilation finishes?

**Comment by ftabaro** [comment]
Seems related to #215 but the error is there also with builder 3.4.2.

**Comment by ftabaro** [comment]
The same recipe in a simpler repository (a single recipe file, no folders or other fancy stuff) builds fine with 3.4.2 builder.

**Comment by vsoch** [comment]
It’s 100% #215 - please follow that issue, and note the comment that the builder will be updated within a week or so. Closing here for duplicate issue.
