### ISSUE TITLE
Deleting account

### ISSUE THREAD

**Issue by containrs** [singularityhub/singularityhub.github.io#222]
Hello, 
I was trying to delete my account. The delete account button seems not to work. I've read a previous issue about it needing some time but I tried it multiple days now. By inspecting the page there seems no action to be programmed by clicking the button? 
Thanks for your help!

**Comment by vsoch** [comment]
hey @containrs I'd be happy to help here! Let's first debug a little bit why it's not working. The command uses [confirm]() first to verify that you want to delete:
```javascript
confirm("Are you sure you want to delete your account?")
```
Can you open any window and test that out and see if it returns True? Here is what it looks like for me:

![image](https://user-images.githubusercontent.com/814322/90961548-067f6c80-e467-11ea-9c54-48687ee25f68.png)

If that doesn't work, it might be a browser issue. In that case, if you look at the source of the page you'll see the URL to go to directly to delete your account, and you can try entering that into the browser.

I did just try to query for your username, "containrs" and I couldn't find it, so is there any chance the delete did work?

**Comment by containrs** [comment]
Ah ok I think then it's on me, mainly because I didn't provide enough info. Sorry about that.
The full story is that I renamed my github and hoped it would also rename the singularity hub account. Since that didn't happen I wanted to delete the singularity hub account in order to create a new one with the new github user name. The old username was "flx-hub". I assume the change in name brought up some issues. 
I still tested confirm and it seems to work for other things like deleting a collection, but not for the account deletion.
I think there are two options that would help my issue: either deleting the "flx-hub" account, or renaming it to containrs. I hope that is not a lot of effort.

**Comment by vsoch** [comment]
I can do either, but I need some kind of confirmation that you own the account. Can you give me a repo with the old username that now directs to yours?

**Comment by containrs** [comment]
there is only one collection on the account called flx-hub/container 3 builds 1 download.
Is that sufficient?

**Comment by vsoch** [comment]
The name would need to redirect to yours (containrs) https://github.com/flx-hub/container. From my standpoint, you could be giving me someone else's user name. I need to have confirmation that you own the account. Let me see if there is an associated email that I can send a confirmation code to, and you could verify.

**Comment by vsoch** [comment]
Ah nevermind it does redirect! I had a space in it. Let me take a look at the account.

**Comment by vsoch** [comment]
okay I'm sending a confirmation to the email associated with the account. Please tell me what it is here.

**Comment by containrs** [comment]
7889

**Comment by vsoch** [comment]
okay all set, your previous collections and user account are deleted. Let me know if you need help with anything else, otherwise feel free to close the issue.

**Comment by containrs** [comment]
thanks a lot for the help!
