### ISSUE TITLE
build on singularity-hub times out even when fbuilding locally in up to 5mins

### ISSUE THREAD

**Issue by tinavisnovska** [singularityhub/singularityhub.github.io#223]
### Links

 - container collection: https://singularity-hub.org/collections/4784
 - GitHub repository or recipe file: Singularity.preprocess

### Version of Singularity

Locally v3.3.0, on singularity-hub v3-4-2

### Behavior when Building Locally

builds in up to 5 mins, 16gb RAM

### Error on Singularity Hub

build times-out on 'wget miniconda2'  (line 11 of the recipe, when lines 11-23 are commented out, the build successfully finishes  on singularity-hub in up to 5 mins)

### What do you think is going on?

no clue ;) it seems like the problem can be either with wget (does not seem likely at all) or with wgetting from anaconda but if that is the case, there probably would be many others complaining about that as well,..

I've moved the recipes from a subfolder 2 levels inside the repo first to one level inside the repo and finally to the repo root to eliminate any issues related to the folder structure mentioned in the issues #215 #220
I've changed url for miniconda2 bash script from  https://repo.anaconda.com/ to https://repo.continuum.io/ as suggested in the issue #217 
neither one of the changes resolved my issue.

Thanks for any help!

**Comment by vsoch** [comment]
Can you please share the GitHub repository?

**Comment by tinavisnovska** [comment]
Have sent you an invite.

**Comment by vsoch** [comment]
Got it! So I interactively created a builder and was able to build your container (relatively quickly) with the wget line, and then uncommenting the other lines (and it seems to work as well, and quickly). I'm afraid I'm as stumped as you are - it could be a transient thing, or something different about how the container is built without the interactive session. Possibly try exporting:

```bash
export DEBIAN_FRONTEND=noninteractive
```
This is a long shot, but did you try the 2.5 builder? And the other (newer) variant of 3.4.2? That at least could tell us if it's something about the builder!

**Comment by tinavisnovska** [comment]
Hi, 
the newer variant of 3.4.2 did the trick and it builds the recipe in 5mins without a problem so maybe there is something going on with the older v3.4.2 builder after all. 

Anyway, thanks heaps for pointing in that direction!

**Comment by vsoch** [comment]
Sure thing! Sorry for the trouble.
