### ISSUE TITLE
//dcouvin/CRISPRCasFinder:4.2.18 

### ISSUE THREAD

**Issue by archanaydv** [singularityhub/singularityhub.github.io#224]
### Links

 - container collection:
 - GitHub repository or recipe file:

### Version of Singularity

Write here

### Behavior when Building Locally

Write here.

### Error on Singularity Hub

Write here.

### What do you think is going on?

Write here.

**Comment by vsoch** [comment]
Please include the link to the recipe on GitHub, the collection builder name, and attach the log file here. I cannot help without any information...
