### ISSUE TITLE
Hanging on running for a build

### ISSUE THREAD

**Issue by thomas-robinson** [singularityhub/singularityhub.github.io#225]
### Links

 - container collection: https://singularity-hub.org/collections/4931
 - GitHub repository or recipe file: https://github.com/thomas-robinson/fms_containers/blob/main/gcc10/openmpi/ubuntu/Singularity.FMS-netcdf4.6.3

### Version of Singularity

3.6.4 (local)

3-4-2-100-gb (shub)

### Behavior when Building Locally

```bash
singularity build -f Singularity.FMS-netcdf4.6.3.sif Singularity.FMS-netcdf4.6.3
```
builds successfully

### Error on Singularity Hub

The status has said "running" for 4 hours now.  According to the documentation, it would have been killed after 3 hours.  The container takes about 15 minutes to build locally.

### What do you think is going on?

I can't diagnose the problem because I don't have access to any log files or output.  I am using spack to build netcdf, so it could be possible that the spack build is taking too long?  The file isn't that big (612 MB)
```bash
$ ls -lrth Singularity.FMS-netcdf4.6.3.sif
-rwxr-xr-x. 1 Thomas.Robinson gfdl 612M Nov  2 14:12 Singularity.FMS-netcdf4.6.3.sif
```
Also, this is my first foray into the world of containers, so it's most likely some sort of user error.

**Comment by vsoch** [comment]
I’ve seen a similar issue with hanging on installing packages, and it was fixed with switching to a different builder. Can you try the other version of 3.4.2 and make sure you use a recipe in the root of the repository? You can also easily try the 2.5.1 builder.

**Comment by thomas-robinson** [comment]
Switching to 3.4.2 solved my build issue.  Thanks for your help.
