### ISSUE TITLE
latest commit id mismatch between general Container Collections page and specific collection page

### ISSUE THREAD

**Issue by alaindomissy** [singularityhub/singularityhub.github.io#23]
### Container Collection commit ids:
**collection:**
https://singularity-hub.org/collections/161/ 

when searching for YeoLab/eclip-dev  https://singularity-hub.org/collections,
the latest commit id is shown as : 02a50a2d3dc7ad948242ca23a9cb976d5f879de3

**latest build**
https://singularity-hub.org/containers/1149/
has commit id: 219a210555c8d91df04eb83e3a2740d2136e2812 

### Error on Singularity Hub

latest commit id mismatch between general Container Collections page and specific collection page

### What do you think is going on?

"looks like a bug in a query somewhere"

**Comment by vsoch** [comment]
hey @alaindomissy ! It was indeed a query bug - I was doing a query to get all the collections, and just returning the first in the list (which wasn't actually sorted by the date). I'm really glad that you opened this issue though, because it made me realize showing some random commit ID in the collections page isn't so useful at all for the user. Instead of just adjusting the commit, what I did is remove it entirely, and add a field for the collection description and it's last modified date. Now, a user can use the search box to search, and see what containers have been recently modified:

![image](https://user-images.githubusercontent.com/814322/26850037-29c85a06-4ad4-11e7-8f81-69547ffedf95.png)

and I went a bit further, and added a link to the Github too:

![image](https://user-images.githubusercontent.com/814322/26850374-43fa8920-4ad5-11e7-9445-e2201e1df9da.png)

This doesn't resolve the issue in the way that you expected, but is it better? I definitely like it better, and I'm hoping you do too :)

**Comment by alaindomissy** [comment]
Very nice!
I have 3 semi-related comments/questions if I may: 

1) I would personally prefer an ISO format for the date if possible: 2017-04-12 instead of 4-12-2017, but may be that's just me...

2) I kind of like the github commit ids and hope they don't completely disappear from the history of builds as well. If they do, is there a way to retrieve them with singularity inspect ? Would I need tosomehow manually adding a label in the Singularity file? Not sure how to do that as editing the Singularity file means making a new commit...

3) I often want to pull an image that is not the most recent. This is possible. I go to the list of old build's click on commands and I am able to copy this to my clipboard:
```
singularity pull shub://1033
singularity pull shub://YeoLab/eclip-dev:master
```
Now this is confusing me at least three times:   :-) 
- I only need to run one of these 2 lines, but I get both if I paste into my terminal
- If I choose shub://YeoLab/eclip-dev:master, I get the latest build and not the older build I wanted
- If I choose shub://1033 the downloaded image file I get is named YeoLab-eclip-dev-master.img, which looks like being the latest build, but it is not (at least I think so!?). So I usually go back to the list of historic builds I go and find the commit id for shub://1033 and rename the image with 
```
mv YeoLab-eclip-dev-master.img 858bccb13253d4d5e91d2a267eed0d88eae34712
```
I should probably rename the image to 1033,but somehow the commit id looks more reassuringly unique. Again that may be just me....

**Comment by vsoch** [comment]
>> I would personally prefer an ISO format for the date if possible: 2017-04-12 instead of 4-12-2017, but may be that's just me...

You got it! Done.

>> I kind of like the github commit ids and hope they don't completely disappear from the history of builds as well. If they do, is there a way to retrieve them with singularity inspect ? Would I need tosomehow manually adding a label in the Singularity file? Not sure how to do that as editing the Singularity file means making a new commit...

They are very important, and of course are still maintained just as before. They don't disappear at all - they are still present on all the collection detail pages. The only place I replaced them is the "all collections" view where you are browsing across collections (and there is little meaning between commit ids between entirely different repositories).

>> I often want to pull an image that is not the most recent. This is possible. I go to the list of old build's click on commands and I am able to copy this to my clipboard:

Ah, so for a particular container, you should use the number. The second (master) is going to pull the most recent for that branch.

>> I only need to run one of these 2 lines, but I get both if I now my clipboard paste into my terminal
If I choose shub://YeoLab/eclip-dev:master, I get the latest build and not the older build I wanted
If I choose shub://1033 the downloaded image file I get is named YeoLab-eclip-dev-master.img, which looks like being the latest build, but it is not (at least I think so!?). 

Even if it's not the latest, if it was built on master branch, it's going to be named with master. And latest doesn't pull the most recent for a branch, it pulls the most recent across the collection (eg, all branches).

>> So I usually go back to the list of historic builds I go and find the commit id for shub://1033 and rename the image with
mv YeoLab-eclip-dev-master.img 858bccb13253d4d5e91d2a267eed0d88eae34712

You actually don't need to do this - when you pull you can ask singularity to name the container based on the commit id. For example:

```
singularity pull --commit shub://YeoLab/eclip-dev:master
```

should name by the commit, `--hash` will name by the hash, and `--name meatballs.img` will let you determine a custom name.

see the docs [here](http://singularity.lbl.gov/docs-pull#image-names) for details on pulling, or [here](https://github.com/singularityhub/singularityhub.github.io/wiki/Deploy#naming-your-container) for the same on the hub wiki.

**Comment by alaindomissy** [comment]
I should have read the docs! That's perfect. Thanks

**Comment by vsoch** [comment]
great! Feel free to close the issue if we've addressed each point.

**Comment by alaindomissy** [comment]
Sorry for being picky but the [date ISO8601 standard](https://en.wikipedia.org/wiki/ISO_8601) would actually be 2017-06-07 instead of 2017-6-7, in other words this format: YYYY-MM-DD :-)

**Comment by vsoch** [comment]
Why don't you give a go at the correct format to use, here is the docs:

https://docs.djangoproject.com/en/dev/ref/templates/builtins/#date

**Comment by alaindomissy** [comment]
:-) I think we would need {{ value|date:"Y-m-d" }} 
Were you suggesting I try to make a pull request ? I would be happy to try.... but I do not know where to start to look for the code for that website https://singularity-hub.org/  
Is it django based ? Thanks

**Comment by vsoch** [comment]
whaaa -la!!

![image](https://user-images.githubusercontent.com/814322/26858771-47426de2-4b01-11e7-99ad-191c482ff061.png)

How's that?

Yep, Django all the way! I <3 Python!

**Comment by alaindomissy** [comment]
YAY! Bravo. This seems like a great Finale. Let me close this. Thanks!

**Comment by vsoch** [comment]
:D  It was cool to learn about that format too, I haven't ever really thought about it :) Thanks as always for your bug reports!
