### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by dcasciotti** [singularityhub/singularityhub.github.io#230]
### Links

 - container collection:
 - GitHub repository or recipe file:

### Version of Singularity

Write here

### Behavior when Building Locally

Write here.

### Error on Singularity Hub

Write here.

### What do you think is going on?

Write here.

**Comment by vsoch** [comment]
I can’t help you if you give me no context. Happy New Year!

**Comment by vsoch** [comment]
No context, please provide the links to the container collection and GitHub repository file as specified, along with the sections that are asked for:

1. Version of Singularity
2. Behavior when building locally
3. Error on Singularity Hub
4. What do you think is going on.
