### ISSUE TITLE
Option to upload an existing .simg rather than rely on triggered builds?

### ISSUE THREAD

**Issue by dPys** [singularityhub/singularityhub.github.io#232]
My workflow involves custom tweaks to the container made after building it. Is there a way that I can incorporate this into my images that get maintained on hub?

**Comment by vsoch** [comment]
Unfortunately not! I would suggest doing a CI build on some free service (GitHub actions, CircleCI or similar), doing that tweak, pushing to a Docker registry (quay is my favorite, but of course there is Docker Hub and recently GitHub packages) and then pulling down to a Singularity container.

**Comment by dPys** [comment]
Darn. Well thanks for the quick reply about it anyway! Might be good to add this one to the wish-list?
