### ISSUE TITLE
Error when pulling container

### ISSUE THREAD

**Issue by georgepar** [singularityhub/singularityhub.github.io#234]
Hi all,

I've integrated singularity hub with my repo, but I am not able to pull the container. Specifically I get the following error:

```bash

singularity pull shub://georgepar/slp

FATAL:   While pulling shub image: error fetching image to cache: failed to get manifest for: shub://georgepar/slp: the requested manifest was not found in singularity hub
```

Also the failed pulls seem to count towards the daily 50 pull quota.

Do you have any suggestions? Thank you!

### Links

 - container collection: https://singularity-hub.org/collections/5346/
 - GitHub repository or recipe file: https://github.com/georgepar/slp/blob/master/Singularity

### Version of Singularity

3.7.3

### Behavior when Building Locally

Container builds and is able to run scripts.

### Error on Singularity Hub

No apparent error. The container is marked as running.

### What do you think is going on?

I do not have enough information to debug this behavior.

**Comment by georgepar** [comment]
I didn't know that there was another stage after RUNNING (COMPLETE). Sorry for the issue.

**Comment by vsoch** [comment]
Totally okay! I'm glad that you got everything working.
