### ISSUE TITLE
Cannot exec container from shub 403 Forbidden

### ISSUE THREAD

**Issue by radiantone** [singularityhub/singularityhub.github.io#235]
[xxxx@xxxxx ~]$ singularity exec --containall  shub://radiantone/gsas2container:gsas2 /work/miniconda/bin/python gsas_example.py
FATAL:   Unable to handle shub://radiantone/gsas2container:gsas2 uri: failed to get manifest for: shub://radiantone/gsas2container:gsas2: 403 Forbidden

### Links

 - container collection: radiantone/gsas2container:gsas2
 - GitHub repository or recipe file: https://github.com/radiantone/gsas2container/blob/main/Singularity.gsas2

### Version of Singularity

3.7.1-1.el7

### Behavior when Building Locally

Container builds fine

### Error on Singularity Hub

Builds fine

### What do you think is going on?

Rate limiter?

**Comment by vsoch** [comment]
Yes 403 means the container or collection reached its weekly pull limit. When it resets you should pull the container once and use the binary to avoid that.
