### ISSUE TITLE
Building is disabled

### ISSUE THREAD

**Issue by baxpr** [singularityhub/singularityhub.github.io#236]
### Links

 - container collection: https://singularity-hub.org/collections/5170
 - GitHub repository or recipe file: https://github.com/baxpr/gf-edat

### Error on Singularity Hub

`Building is disabled`

`You've used 0 out of 10 of your daily builds.`

What am I missing? Thanks!

**Comment by vsoch** [comment]
Sorry you missed the announcement!

https://twitter.com/vsoch/status/1380980790301888513

**Comment by vsoch** [comment]
You could use Docker Hub or Quay.io to pull to singularity, the Sylabs free tier on their cloud, or (more recently what I found is possible) saving an image to a repository release asset: https://github.com/singularityhub/singularity-deploy. And then you can pull with shpc. Good luck!

**Comment by baxpr** [comment]
I missed it, all right! Best wishes :)

**Comment by vsoch** [comment]
Thank you @baxpr <3
