### ISSUE TITLE
Get error that building is disabled

### ISSUE THREAD

**Issue by Romit-Maulik** [singularityhub/singularityhub.github.io#237]
### Links

https://github.com/Romit-Maulik/singularity_recipes

### Version of Singularity

N/A

### Behavior when Building Locally

N/A

### Error on Singularity Hub

I keep getting a "Building is disabled" message when I try to trigger a manual build. I also do not see any of my recipes. I also ensured that my main branch is enabled for building.

### What do you think is going on?

Not sure. 

![image](https://user-images.githubusercontent.com/12647892/115446722-3db44200-a1dd-11eb-84c8-631893e189a3.png)

**Comment by vsoch** [comment]
You missed the announcement! https://twitter.com/vsoch/status/1380980790301888513 It's currently in read only mode.

**Comment by Romit-Maulik** [comment]
Wow - just when I was really starting to love this! Thanks for all the great work :)

**Comment by vsoch** [comment]
Closing issue, thanks again for your kind words!
