### ISSUE TITLE
Trigger build gives "Building is disabled"

### ISSUE THREAD

**Issue by adriansev** [singularityhub/singularityhub.github.io#238]
### Links

 - container collection:
https://singularity-hub.org/collections/4203

 - GitHub repository or recipe file:
https://github.com/adriansev/el7cvmfs.sing

### Error on Singularity Hub
Trying to trigger the build gives a very dry "Building is disabled" message

### What do you think is going on?
i have no idea .. yesterday it worked

**Comment by vsoch** [comment]
Singularity Hub is read only this week, here is the announcement -> https://twitter.com/vsoch/status/1380980790301888513

**Comment by adriansev** [comment]
@vsoch oh, i did not see it.. Thank you very much for all your work and i wish you all the best in your future activities!

**Comment by vsoch** [comment]
Thank you @adriansev - that is very kind, and the best to you as well! <3

**Comment by vsoch** [comment]
I'm going to re-open so hopefully other users see this issue (I keep getting new ones!) relevant ones are:

 - #237 
 - #236 
 - #239
 - #240 
 - #241
