### ISSUE TITLE
"Building is Disabled" even though it is enabled in Settings

### ISSUE THREAD

**Issue by tfunck** [singularityhub/singularityhub.github.io#239]
### Links

 - container collection: https://singularity-hub.org/collections/3471
 - GitHub repository or recipe file: https://github.com/APPIAN-PET/APPIAN

### Version of Singularity

Don't know, whatever the default on Singularity hub is. Locally it's 2.4.2-dist.

### Behavior when Building Locally

Builds normally.

### Error on Singularity Hub

I get a message saying "Building is Disabled" however in Settings -> Danger Zone -> Disable Building the setting is such as to allow building.

### What do you think is going on?

The build script seems fine. The problem appears could be some backend issue related to Settings or the connection to my 
![building](https://user-images.githubusercontent.com/6856252/115898733-e1932d00-a42b-11eb-8b03-d0d13d11dd3b.png)
github.

**Comment by vsoch** [comment]
Please see discussion in #238 and linked issues - Singularity Hub is read only this week. Thank you!
