### ISSUE TITLE
Clicking 'Trigger Build' displays message "Building is disabled"

### ISSUE THREAD

**Issue by radiantone** [singularityhub/singularityhub.github.io#241]
### Links

 - container collection: radiantone/gsas2container
 - GitHub repository or recipe file: https://github.com/radiantone/gsas2container/blob/main/Singularity.gsas2

### Version of Singularity

Singularity Hub

### Behavior when Building Locally

Write here.

### Error on Singularity Hub

Clicking 'Trigger Build' displays message "Building is disabled"

### What do you think is going on?

Not sure

**Comment by vsoch** [comment]
Please see https://github.com/singularityhub/singularityhub.github.io/issues/238.
