### ISSUE TITLE
Is singularityhub down

### ISSUE THREAD

**Issue by dongfang91** [singularityhub/singularityhub.github.io#242]
I want to check the status of my singularity image, but when I go to the [Singularity-Hub](https://singularity-hub.org/), it redirects me to this new website http://datasets.datalad.org/?dir=/shub

**Comment by vsoch** [comment]
Singularity hub is now an archive at Dartmouth. If your containers were built before the 19th of April they should be there, and still pullable.

**Comment by vsoch** [comment]
https://singularityhub.github.io/singularityhub-docs/2021/going-read-only/

**Comment by dongfang91** [comment]
Got it, thank you!
