### ISSUE TITLE
github webhook isnt working

### ISSUE THREAD

**Issue by wheaton5** [singularityhub/singularityhub.github.io#244]
### Links

 - container collection: shub://wheaton5/souporcell
 - GitHub repository or recipe file: https://github.com/wheaton5/souporcell

### Version of Singularity

singularity-ce version 3.10.2-jammy

### Behavior when Building Locally

Builds successfully

### Error on Singularity Hub

github webhook returning 404. webhook address is https://singularity-hub.org/hooks/build/push

### What do you think is going on?

not sure

**Comment by vsoch** [comment]
Singularity Hub was dismantled in 2021 and there is no more service - the current `shub://` URI is serving from an archive, so unfortunately there is no webhook that exists to work! The 404 is correct.

**Comment by wheaton5** [comment]
Thanks for letting me know. Where do people host their singularity builds now? Is there a standard repository service used?

**Comment by vsoch** [comment]
You can actually push to GitHub actions with ORAS (OCI registry as storage!) Here is an example to build -> push and then pull https://github.com/singularityhub/github-ci/. I mostly (when I need Singularity) just pull from a docker:// URI these days.

**Comment by vsoch** [comment]
Let me know if you have any other questions - otherwise closing the issue!
