### ISSUE TITLE
Build failing (Docker, Fedora 25 base image), but I can't find a reason

### ISSUE THREAD

**Issue by akkornel** [singularityhub/singularityhub.github.io#26]
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/containers/1343/log

This is a bootstrap using the Docker method, based on Fedora 25.  I use the `%setup` section to copy the working directory into the container image.  I use the `%post` section to install packages, and to call `setup.py` (the source repo is a Python distribution).  I also have a `%test` section which is run.

### Behavior when Building Locally

The build completes successfully.  Here's an asciinema link:

https://asciinema.org/a/cpyn1v32752d8m0waw80wt16i

I wanted to make sure my system was completely clean, so I wiped my VM, re-installed Ubuntu 16.10, and installed Singularity 2.3 from the Neurodebian repo.  After that, building was as simple as:

```
git clone https://github.com/akkornel/pypop.git pypop
cd pypop
singularity create -s 1024 ../image
sudo singularity bootstrap ../image Singularity
```

### Error on Singularity Hub

I'm not entirely sure.  The bootstrap appears to complete successfully, but then something causes the build to fail.

> Finalizing Singularity container
> /tmp/tmp4lm0v1ru/image
> ERROR:shub_builder:Image failed to bootstrap, cancelling build.

I ran the build with debug messages on, but I still don't see anything out of the ordinary.

### What do you think is going on?

I'm sorry, but I honestly have no idea.

**Comment by vsoch** [comment]
@akkornel is this still an issue?

**Comment by vsoch** [comment]
hey @akkornel could you please try this on the new release of Singularity Hub? Thanks!

**Comment by vsoch** [comment]
ping @akkornel !

**Comment by vsoch** [comment]
Pinging since July 2017, no response, closing issue. Please ping me on slack if you are still having issue.
