### ISSUE TITLE
hub failed build with centos-7 container

### ISSUE THREAD

**Issue by dbgannon** [singularityhub/singularityhub.github.io#27]
Hi,
sorry i did not save the repo with the failed build (i did not want to clutter your space with my failures) but here is the Singularity file:

BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

%runscript
    echo "This is what happens when you run the container..."

%post
    echo "Hello from inside the container"
    yum -y install vim-minimal
    echo "Installing Development Tools YUM group"
    yum -y groupinstall "Development Tools"
    yum -y install wget
    wget https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.0.tar.bz2
    tar -xf openmpi-2.1.0.tar.bz2
    echo "installing openmpi"
    ls
    cd openmpi-2.1.0
    ./configure --prefix=/usr/local
    make
    make install
    echo "done"

### What do you think is going on?
i have no problem building a container based on a ubunu docker image
i suspect that the hub does not yet support centos?  there is probably a note to this effect in the docs but i failed to find it.  

if you wish i can reproduce the error.    let me know.   i am dennis.gannon@outlook.com.

**Comment by vsoch** [comment]
hey @dbgannon ! We have quite a bit of trouble with yum bootstraps because there can actually be errors given a mismatch of the package manager on the host, or some missing modules file for it. The first thing I would try is using the same OS but from a Docker image. Let me know if that resolves the problem!

**Comment by dbgannon** [comment]
Hi Vsoch.  That sounds like a good solution.   i'll try it when i have time.  the version i built from a docker image based on  ubuntu worked fine.   
dennis
ps: i am working on a chapter to add to our book https://Cloud4SciEng.org about Singularity.  I'll certainly recommend building from a docker image there.

**Comment by vsoch** [comment]
super cool! Definitely let me know if you want any help, I love writing things :)

**Comment by dbgannon** [comment]
How about if i send you a copy of the chapter for comments, corrections and edit?  I will, of course, ack your help.  if interested, send me an actual email address and i'll send a copy your way.   or i may just send you a github repo link.

**Comment by vsoch** [comment]
That would be great! I'll send you an email so you have my contact.

**Comment by dbgannon** [comment]
Hi Vsoch,
never heard back from you.  I finished a draft of my chapter section on Singularity and the Hub.  If you are interested in commenting or adding, it is here: https://cloud4scieng.org/singularity-a-container-system-hpc-applications/.   the page is visible but not yet linked from the main site.   There is a markdown version of the text if you want to edit it directly.  it is on github at SciEngCloud/SciEngCloud.github.io/singularity/singularity-chapter.md 
If you want to send comments or corrections only by email send to dennis.gannon@outlook.com. And, of course i want to reference anything/anybody that you would like to see ack'd in the text.

**Comment by vsoch** [comment]
Hey @dbgannon ! Did it maybe go to spam? I did send you a note right away:

![image](https://user-images.githubusercontent.com/814322/27451783-28aee34c-5745-11e7-8557-27dba6d49a01.png)

I'll take a look right away! Let me know if you find me in spam.

**Comment by vsoch** [comment]
hey @dbgannon is this issue resolved?

**Comment by vsoch** [comment]
hey @dbgannon we just released Singularity Hub 2.0 would you mind trying the build again? I'm closing the issue and feel free to re-open if you need.
