### ISSUE TITLE
Add link to Singularity web site

### ISSUE THREAD

**Issue by HenrikBengtsson** [singularityhub/singularityhub.github.io#3]
It would probably be helpful for new users, but also existing ones, if there was links to http://singularity.lbl.gov/ from the https://singularity-hub.org/ website.

A natural update to the https://singularity-hub.org/collections page would be:

> A container is built automatically from a connected Github repo with a [Singularity](http://singularity.lbl.gov/) File.

**Comment by vsoch** [comment]
Done! I added one to the [usage docs](https://singularity-hub.org/faq) page as well. Anywhere else where you think it would be good?

**Comment by HenrikBengtsson** [comment]
Great. Some possibilities for the front page:

[Singularity] containers built with Singularity Hub ...

We provide simple views for seeing inside of your [Singularity] containers, and making comparisons between containers.

**Comment by HenrikBengtsson** [comment]
Also, maybe the header / banner should read "SINGULARITY [HUB]" to distinguish it from the Singularity web site.  Right now that's not clear and someone might end up on this page when searching for "Singularity".

**Comment by vsoch** [comment]
I haven't totally decided on branding for Singularity Hub (and I'm not convinced it's totally necessary) so I'm wanting to keep it as it is now - Singularity Hub and Singularity are tightly integrated and the user / searcher (should) stumble across both in searching. I'll keep this in mind though, thanks for the suggestion!

**Comment by vsoch** [comment]
link to Singularity was added, closing issue. Thanks again!
