### ISSUE TITLE
out of space errors are ignored, container shows as complete on hub UI

### ISSUE THREAD

**Issue by fac2003** [singularityhub/singularityhub.github.io#30]
I had a problem where the hub container appeared complete, but the %post section had not run (directories created in / by post did not exist in the image). After inspection of the Hub container building log, I realized the container construction ran out of storage (they were several mentions of this occurrence in the log). These errors were ignored and the container appeared built on the UI, this is the real problem (I understand that transient out of storage conditions can exist, but they should be reported as failures to build).

**Comment by fac2003** [comment]
You can find an example of this here:
https://singularity-hub.org/containers/1406/log

INFO:shub_builder:Checking out branch master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
INFO:shub_builder:Checking out commit 8336d1ffac6e1dc6a9f76c0cac51815547d1310b
INFO:shub_builder:Found spec file Singularity in repository
DEBUG:shub_builder:Building in directory /tmp/tmpd_4yb0l7
DEBUG:shub_builder:Spec file set to Singularity
DEBUG:shub_builder:Spec file for build should be in /tmp/tmpd_4yb0l7/Singularity
tar: var/cache/yum/x86_64/7/updates/gen/primary_db.sqlite: Wrote only 5120 of 10240 bytes
tar: var/lib/rpm/Basenames: Wrote only 8192 of 10240 bytes
tar: var/lib/rpm/Dirnames: Wrote only 9216 of 10240 bytes
tar: var/lib/rpm/Packages: Wrote only 9728 of 10240 bytes
tar: var/lib/rpm/Requirename: Wrote only 2560 of 10240 bytes
tar: var/lib/rpm/Sha1header: Wrote only 1024 of 5120 bytes
tar: var/lib/yum/history/2017-06-05/13: Cannot mkdir: No space left on device
tar: var/lib/yum/history/2017-06-05/13: Cannot mkdir: No space left on device
tar: var/lib/yum/history/2017-06-05/13/config-main: Cannot open: No such file or directory
tar: var/lib/yum/history/2017-06-05/13: Cannot mkdir: No space left on device
tar: var/lib/yum/history/2017-06-05/13/config-repos: Cannot open: No such file or directory
tar: var/lib/yum/history/2017-06-05/13: Cannot mkdir: No space left on device
tar: var/lib/yum/history/2017-06-05/13/saved_tx: Cannot open: No such file or directory
tar: var/lib/yum/history/history-2017-06-05.sqlite: Wrote only 1024 of 10240 bytes
tar: var/lib/yum/rpmdb-indexes/pkgtups-checksums: Wrote only 6656 of 10240 bytes


and so on, but the container looks complete:
<img width="1340" alt="singularity_hub" src="https://user-images.githubusercontent.com/1728407/27444251-bd23a550-5743-11e7-9b69-7fe43658a054.png">

**Comment by vsoch** [comment]
Hey @fac2003 ! This is unlikely to be the instance, but the container itself. Try setting the size to a larger one in build settings and see if it completes. The reason it is deemed to be ok is because the extracted files don't seem to influence some kind of image being successfully built, which runs with a simple ls command.

**Comment by fac2003** [comment]
Thanks for the tip. It's a problem that you can't trust the image was successfully built by just looking at the UI. S
In this case the %post statements never ran, that seems a bit strange to consider it successful.

**Comment by vsoch** [comment]
I can't implement a test that is general enough to fit all containers - but there is a solution! This is exactly why we have the `%test` section - you can write tests and it will fail if they don't pass. Do you want to give it a try?

**Comment by fac2003** [comment]
Thanks, I am trying this now. The documentation of the %test section is lacking in specifics. I assume  returning a non zero status is an error code, but I would have liked this written in the doc (http://singularity.lbl.gov/docs-bootstrap).

**Comment by vsoch** [comment]
Definitely! Here is the (probably lacking) test section - http://singularity.lbl.gov/docs-bootstrap#test if you have specifics you are wanting to add, I'd be happy to tweak! I think that's about the extent of what test is, so it's all that I wrote :P

**Comment by vsoch** [comment]
I added some docs here https://github.com/singularityhub/singularityhub.github.io/wiki/Generate-Images#add-tests to make it easier to find this information as well, at least the bits relevant to Singularity Hub!
