### ISSUE TITLE
AsciiCast should be hosted on asciinema.org

### ISSUE THREAD

**Issue by matteosecli** [singularityhub/singularityhub.github.io#31]
Hello, I've uploaded an AsciiCast here: https://singularity-hub.org/demos/3/

However, when clicking "Play" the player loads for an infinite time. I tried a
```
wget --spider https://singularity-hub.org/demos/3/json
```
and indeed I get a `502 Bad Gateway` error.

**Comment by vsoch** [comment]
hey @matteosecli ! Yes I received this error in the log - could you send me the asciicast file you used to debug? The error was that the json is invalid, so I want to step through it and see how it can be best resolved. Thanks!

**Comment by matteosecli** [comment]
Yes, of course! Forgot to include it! :smile: Here it is: https://asciinema.org/a/QmcJjkdtm80BeReOSS5euw8WU. It plays just fine on Asciinema's website.
I had a suspect about the invalid json, so I was looking for an option to delete the AsciiCast and download/upload it again, but I couldn't find one. Is there any way do delete an AsciiCast?

**Comment by vsoch** [comment]
hey @matteosecli - I took care of deleting it for you - it didn't actually find the file on the server! I think there is likely a but wrt the saving - Let's hold off for now and if you don't mind, we can use asciinema.org to host it. What I think I want to do for 2.4 is embed them from there (versus saving the files on the shub server). I'll add this to the milestone for the next release, sorry for the annoyance!

**Comment by matteosecli** [comment]
No worries, for me it's ok!

**Comment by vsoch** [comment]
hey @matteosecli ! Just wanted to give an update on this - the new version is done, so will be live in the next release. The asciinema are now hosted directly from asciinema,org so we don't risk losing them on the shub server, which is what seemed to be happening with yours.

![image](https://user-images.githubusercontent.com/814322/27981999-40b30280-6365-11e7-8d5d-d04754be72b8.png)

**Comment by matteosecli** [comment]
That looks great! Looking forward to the next release! :smiley:
