### ISSUE TITLE
End usage instructions hard to find

### ISSUE THREAD

**Issue by HenrikBengtsson** [singularityhub/singularityhub.github.io#32]
I've looked through https://singularity-hub.org/ and it looks like the documentations / instructions are geared toward developers and maintainers of containers, but not to end users.  Because user are likely to find SingularityHub containers via a search engine, I think one could lower the "get-started" threshold significantly if there were usage instructions for each container on the SingularityHub site, e.g. for https://singularity-hub.org/collections/25/ there could be a section:

> # Usage
> To pull the container tagged "master" and then run it, use:
> ```sh
> $ singularity pull shub://singularityhub/ubuntu
> $ singularity run singularityhub-ubuntu-master.img
> ```
>
> To pull a container with a different tagged, append `:` followed by the tag to the URI, e.g.
> ```sh
> $ singularity pull shub://singularityhub/ubuntu:14.04
> ```
> The Singularity image file downloaded will be `singularityhub-ubuntu-14.04.img` (also in the working directory).

The first example can be added for all containers, whereas the second would require some lookup of alternative tags.

The reason for explicitly writing what the saved files are is because it is not immediately obvious where they are save (e.g. current directory or a hidden cache directory) and how the files are named (e.g. if different tags overwrite each other).

**Comment by vsoch** [comment]
oh I really like this idea! Yes huge +1 :) There is a commands section that lives with the container:
![image](https://user-images.githubusercontent.com/814322/27570415-f114cc46-5acb-11e7-8ec0-f53649a4ef51.png)

But methinks it should be moved up one level to be at the level of the collection, and fixed per your suggestion. I don't see a ton of use cases for which the running of containers would differ between containers in a collection (eg branches in the github repo) - do you? That was the reason I originally put the commands on the level of the container, but you are right that it's harder to find.

**Comment by HenrikBengtsson** [comment]
Ah...a.  I had a vague memory of having seen that way back, but then I really click-click-click-clicked around and couldn't find it.  So, yes, it's not obvious that one need to click on the green "COMPLETE" status to find the "Commands" tab, especially since there are other buttons / icons to the far right.   I would certain vote for promoting those commands being available on the front page of each container (= "the collection").

I don't know if there are need for per-branch specific use cases, but if there is, couldn't that be described in some `README.md` file that could part of the GitHub repos (and maybe displayed via SingularityHub?).  It seems hard to automate that and is probably best maintained by the developer.

BTW, is `shub://<incremental-index>` meant to work as a permalink? Is that something you wish to promote and promise? I find it more intuitive to use the full <owner>/<repos>:<branch> URI.  It is also less risky, e.g. getting a digit wrong if typed manually and one pulls down the wrong image.  Not important - just a comment.

---
While at it, I also realize I have no idea what clicking 'DISCUSSION' -> 'VIEW ASCIINEMAS' is supposed to give.  And, note have you have to click the container title to get back to the build on 'VIEW ASCIINEMAS', whereas on the 'DISCUSSION' page you click 'VIEW BUILDS'.  Should 'DISCUSSION', 'ASCIINEMAS', 'BUILDS' be tabs available everywhere - are they "sibling" pages that you should be able to reach from everywhere?  It's quite easy to get "lost" in there.

Thanks

**Comment by vsoch** [comment]
hey @HenrikBengtsson ! I just made these changes to the next version, so you should expect to see them there. Thanks for the suggestion! I totally agree, the usage needs to be seen up front.

**Comment by HenrikBengtsson** [comment]
Awesome. Thanks for your prompt replies and the awesome hub service.

**Comment by vsoch** [comment]
okay here is how the view is! I added a nice copy paste functionality too :)

![copycommands](https://user-images.githubusercontent.com/814322/27981975-c9f8aa0a-6364-11e7-8cfb-096eced5907d.png)

and this is linked directly from the main collection page, notice also some of the buttons are more logically grouped so it won't be as cluttered.

![image](https://user-images.githubusercontent.com/814322/27981985-ece3089e-6364-11e7-840e-b05aaf09f2d9.png)

**Comment by HenrikBengtsson** [comment]
Thxs - that looks great.  When do you think you roll it out?

**Comment by vsoch** [comment]
No idea - but reasonably after I get back from the conference next week, I'll likely want a few more weeks for singularity hub, and then a handful for the registry. I'd say sometime late August or early September is likely. I'd rather have it robustly tested with all the bells and whistles that are wanted vs. not before making the switch from the current!

**Comment by HenrikBengtsson** [comment]
Sounds good - no rush.
