### ISSUE TITLE
Create an image security scanner

### ISSUE THREAD

**Issue by remyd1** [singularityhub/singularityhub.github.io#33]
Hi,

This issue is not a bug, but a feature request.

Some registries like quay.io allows users to scan images for vulnerabities. You can have an example [here](https://quay.io/repository/quay/redis/image/54da947db59aafbbc0f691c96d6d3eedabb123628e2268662e0eedd875603c8f?tab=vulnerabilities)

I think it is using [clair](https://github.com/coreos/clair) from CoreOS.

Best regards,
Rémy

**Comment by vsoch** [comment]
Definitely agree! [Here is a post](https://banyanops.com/blog/analyzing-docker-hub/) from a while back to start from. I think this would be good functionality to add to the builder.

**Comment by remyd1** [comment]
New related issue : https://github.com/singularityhub/sregistry/issues/14

**Comment by vsoch** [comment]
This is for sregistry now,if anyone ever cares to contribute it. Closing here! Thanks again @remyd1 for the suggestion!
