### ISSUE TITLE
Upgrading all images from a registry

### ISSUE THREAD

**Issue by remyd1** [singularityhub/singularityhub.github.io#34]
Hi,

This is not an issue but a feature request. The main idea is to add the possibility as a registry admin, to upgrade all images from a registry and check logs for any problem, or at least, container by container (or with a scheduler).
Container by container would be as easy as `singularity exec $IMG yum update` or `singularity exec $IMG "apt-get update && apt-get dist-upgrade"`. For all containers, a loop can do the job. What would be needed is the output of these commands for the singularity-registry admin, in an admin panel view.

Best regards,
Rémy

**Comment by vsoch** [comment]
you got it! Could you put this in the [registry repo?](https://github.com/singularityhub/singularity-registry/issues) I should be starting management / logging commands soon :)
