### ISSUE TITLE
Building does crash 

### ISSUE THREAD

**Issue by apeltzer** [singularityhub/singularityhub.github.io#36]
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/containers/1569/log

### Behavior when Building Locally

Works fine like this:

`
sudo singularity create --size 3000 eager.img
sudo singularity bootstrap eager.img Singularity
`

### Error on Singularity Hub

errors in building, files are there - it just seems to fail at some point and I can't check why:

`
downloading eagerstat-0.4-1-any.pkg.tar.xz...
Errors occurred, no packages were upgraded.
[31m(B[m
/tmp/tmp8_80n4f0/image
``

### What do you think is going on?

See above - something breaks.  I will update the machine with the packages and see if that helps, but can't really say if this is the case unfortunately.

**Comment by vsoch** [comment]
hey @apeltzer ! The log linked above is a 404 for me - do you have a link to one?

**Comment by apeltzer** [comment]
Fortunately, this resolved itself somewhat. If I come back to such an issue, I will let you know (and close this for now)

**Comment by vsoch** [comment]
Thanks! I think the issue is making available an image that isn't done building yet, which should fail nicely (and doesn't). I did a PR to Singularity to return a more proper error message, and will have the same for the next version off the hub. Thanks for reporting!
