### ISSUE TITLE
turning branches on singularity hub requires additional commit to build

### ISSUE THREAD

**Issue by satra** [singularityhub/singularityhub.github.io#4]
after turning on branches in singularity hub for a specific project, one has to go back to the branch on github and make a new commit on that branch for the container to build.

from that point on it behaves normally, but that first instance requires an extra commit.

**Comment by vsoch** [comment]
@satra this should be addressed now with the ability to manually trigger builds (coming soon with 2.0). This is more flexible than enforcing an "always build" rule as some users may not want to build when enabling a new branch.
