### ISSUE TITLE
Manual release/version tagging for containers

### ISSUE THREAD

**Issue by sven1103** [singularityhub/singularityhub.github.io#43]
More a feature request than an issue :)

Created my first Singularity container today and build it on singularity hub. I wondered, if there is a mechanism to manually tag a certain version of a container, like a release tag "v1.0" or so. 
Currently, as I understood it, the git branch name is used as the tag in the container collection overview? 

I normally would have a release branch and tag releases in GitHub explicitly, and tagging a container in such a way would also enhance reproducibility imho. Any ideas/suggestions? (Btw great work so far with Singularity, having fun implementing containers and using them).

Best, Sven

**Comment by vsoch** [comment]
hey @sven1103 ! I completely agree, and this is actually already implemented in the next release, and it will look like this --> https://singularityhub.github.io/singularity-registry/user/registry-flow.html#github-for-version-control. Basically, you will be able to have multiple tags per repo, determined by the extension of the Singularity file.

**Comment by sven1103** [comment]
hey @vsoch, thanks for the fast response!

But I am thinking, if it is a good idea to have singularity files with different tags that live within the same git snapshot. At least in my humble opinion. I mean, I am using GitHub features like 'release' or 'tag' extensively, as this gives you full control about the content of a certain snapshot of the repo. If you have different tags in the filename, then you have no control, if for example Singularity.v1 is the same file / contains the same bootstrap settings as during a later development state of the repo.

Or did I get it wrong?

**Comment by vsoch** [comment]
Github tags are up to you, different from a tag for the container. For example, for docker the tag `ubuntu:latest` doesn't coincide with some tag in the Github repo called "latest."  My preference is to have one Github commit with one image, but this is in response to much feedback that people want to be able to store multiple tags (eg, gpu version, cpu version, dev version) in a single folder. You could have these three  singularity hub tags:

```
shub://sven1103/analysis:gpu
shub://sven1103/analysis:cpu
shub://sven1103/analysis:local
```
coinciding with a github tag like v.1.0, which would be associated perhaps with a zenodo id / publication. Perhaps the best way to think about it is that a tag is not a version in time, but a label to distinguish different images for one.

**Comment by sven1103** [comment]
But how would you reference a certain version of a shared Singularity container within a production workflow environment? Especially if you pull from Singularity hub? If you pull `shub://sven1103/analysis:cpu`, the container status will change over time.

**Comment by vsoch** [comment]
The same as it works now, if you ask for a tag, it returns the last build of the tag. If you want more specific than that, you ask for the commit id. In the new version I'm not going to be saving every single commit unless the user "freezes" the container specifically - so the tag will always return the last successful container built from the repo with the tag. Tag != "I am tagging this specific point in time," it is more "I am labeling the container with this term to describe it." Versioning (and how I think you are thinking of tagging) comes by way of referencing a specific commit for singularity hub.

**Comment by vsoch** [comment]
And the way I would probably do it is akin to having master/development branches on github, always one tag called "production" so for the workflow you always use `shub://sven1103/analysis:production` and only update when necessary.

**Comment by vsoch** [comment]
if you disagree, then this might be a good issue to bring up with others on slack.  it's an important enough detail that we should get it right.

**Comment by sven1103** [comment]
hey @vsoch, thanks for your feedback. I agree, Slack would be a good place to get some other impulses/ideas referring this issue :)

**Comment by vsoch** [comment]
hey @sven1103 - this will be possible with the next release of shub - you basically can define tags based on the extension of the Singularity file, and  a plain `Singularity` builds latest. Each new build of a tag over-writes the previous (old version if existing) unless the user has frozen a container, in which case it builds a new one.
