### ISSUE TITLE
builder should check exit code to determine status success/fail

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularityhub.github.io#45]

**Comment by vsoch** [comment]
I think something might be broken then. The failures I see are non-0 exit codes. For example:

https://singularity-hub.org/collections/363/

and specifically:

https://singularity-hub.org/containers/2267/log

In the log:
```
+ exit 1
ABORT: Aborting with RETVAL=255
DEBUG:shub_builder:Built image: /tmp/tmp5lpu4xb9/0f814040e7ba5552d0277d76f8fc89d3
INFO:shub_builder:Final time of build 11 seconds.
INFO:shub_builder:Singularity 2.3-master.gf737013 being used.
```

But the build still is marked as "Complete".

If you want to try the same one, the Singularity file is very simple: https://github.com/rynge/hub-test/blob/master/Singularity

When I run it on my one host, bootstrap exits with exit code 255:
```
$ sudo singularity create --force --size 4000 /tmp/foo.img ; sudo singularity bootstrap /tmp/foo.img Singularity
Initializing Singularity image subsystem
Opening image file: foo.img
Creating 4000MiB image
Binding image to loop
Creating file system within image
Image is done: /tmp/foo.img
Sanitizing environment
Building from bootstrap definition recipe
Adding base Singularity environment to container
Docker image path: index.docker.io/library/centos:7
Cache folder set to /root/.singularity/docker
[1/1] |===================================| 100.0%
Exploding layer: sha256:7b6bb4652a1be64d39920f7d8c12c5f0bd8abfc10820177109e73817357c07e3.tar.gz
Exploding layer: sha256:60e3079474b1671bcc20b340572ee6cae735ecdd5a13d6686475ca4916eb6003.tar.gz
Running post scriptlet
+ exit 1
ABORT: Aborting with RETVAL=255
rynge@colo-vm63:~/git/hub-test$ echo $?
255
```

**Comment by vsoch** [comment]
this is logical behavior given the current way the image is checked, but should be changed to check the exit code instead.

**Comment by yarikoptic** [comment]
FWIW -- added `set -eu` to my %post script, which caused it to fail as soon as first error, but hub reported 'COMPLETE' as well and now pull fetches that crippled image

**Comment by vsoch** [comment]
If it has a shell that is able to echo, it's determined a success. Like we already talked about, this will change to look at the exit code.
