### ISSUE TITLE
Is it possible to mark a container to be rebuilt?

### ISSUE THREAD

**Issue by anderbubble** [singularityhub/singularityhub.github.io#49]
I'm trying to build my first container; but I was running into a situation where I needed more space than the default 800MB. I increased the image size for the collection, but I can't figure out how to get it to rebuild without removing and re-adding the whole collection, or pushing a garbage commit.

Does this feature exist?

**Comment by vsoch** [comment]
You can't go back in time and rebuild an (old) container, the idea behind singularity hub is that the builds and they corresponding spec files are frozen. You would want to push (commit) again to produce an updated (possibly with different collection settings) build.

**Comment by vsoch** [comment]
hey @anderbubble ! Heads up I'm looking to add this ability to the next version of shub - it will be possible to trigger a build for a finished / cancelled / error container that already has a commit and associated recipe file.
