### ISSUE TITLE
Container build keeps failing due to lack of size?

### ISSUE THREAD

**Issue by anderbubble** [singularityhub/singularityhub.github.io#50]
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/containers/2576/log

### Behavior when Building Locally

Not tried

### Error on Singularity Hub

At least 538MB more space needed on the / filesystem.

### What do you think is going on?

I think there's not enough space in the image; but the space it says is required seems to be inconsistent. I've increased the size of the image to no avail. I'm also confused because the log sometimes says the build succeeded, and sometimes says it failed.

**Comment by vsoch** [comment]
hey @anderbubble ! You have a large image, so you need to set the size in the collection portal under the builder settings. That will cut your build time in half, and also make the space available for the image proper. If you read the log carefully, the size that the builder estimates is just under 1500. If you want to try building locally to get your own size guesstimate, that would work too. Please try that and post an update.

**Comment by vsoch** [comment]
Hey @anderbubble ! Could you please test this on the new release of Singularity Hub? We might still need a larger instance. I'm going to close the issue, please open a fresh one if the error continues!
