### ISSUE TITLE
[wishlist] button/url to download raw build log

### ISSUE THREAD

**Issue by yarikoptic** [singularityhub/singularityhub.github.io#51]
ATM, e.g. https://singularity-hub.org/containers/2530/log, it is an HTML with the log colored etc somewhere in the middle... makes it hard to use it locally to troubleshoot failures

**Comment by vsoch** [comment]
What would you suggest instead?

**Comment by vsoch** [comment]
Just a download button?

**Comment by yarikoptic** [comment]
may be not instead but in addition?  yeah, just a button "Download" or "Raw" (like github iirc)?

**Comment by vsoch** [comment]
will do!

**Comment by vsoch** [comment]
hey @yarikoptic this is done! Will be included with next release.

![image](https://user-images.githubusercontent.com/814322/31318197-2bbf4db6-ac03-11e7-9364-f4b70f0fa45d.png)

**Comment by yarikoptic** [comment]
Great. Thank you @vsoch !
