### ISSUE TITLE
Failure in %setup should fail the build, but instead it seems to continue building something else?

### ISSUE THREAD

**Issue by yarikoptic** [singularityhub/singularityhub.github.io#52]
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/containers/2530/log   has

```
[0mDEBUG [U=0,P=19102] main() Iterating through file looking for sections matching: %setup
[0m+ set -eu
+ echo Setting up the environment
+ apt-get update
+ apt-get -y install python
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
ABORT: Aborting with RETVAL=255
Creating and bootstrapping image...
INFO [U=0,P=2678] main() Initializing Singularity image subsystem
[0mINFO [U=0,P=2678] main() Opening image file: image
[0mINFO [U=0,P=2678] main() Creating 12000MiB image
[0mINFO [U=0,P=2678] main() Binding image to loop
[0mINFO [U=0,P=2678] main() Creating file system within image
[0mINFO [U=0,P=2678] main() Image is done: /tmp/tmpnlidpw6y/image
...
User defined %runscript found! Taking priority.
Setting up the environment
Hit:1 http://us-west1.gce.archive.ubuntu.com/ubuntu xenial InRelease
...
```

So `%setup` failed (not sure why yet since should have been ran as root and there should be no other process) but build continued on with building something else (there should have been no ubuntu but debian), and replaced previously built correct image, and now whoever fetched it  was totally confused seeing nothing "neurodebianish" 

### Behavior when Building Locally

building now... will report when done

**Comment by vsoch** [comment]
setup is before image build, I'm not sure that we dunk out when setup fails (just post?) It makes sense it's different because commands on setup aren't happening in/for the image, but outside of it.

**Comment by yarikoptic** [comment]
ha -- I should have got that.  and it explains why it worked for me locally ;-)

**Comment by yarikoptic** [comment]
but should/could I just assume that the build box has git and python installed? ;)

**Comment by vsoch** [comment]
lol, no you don't get to control the build box :P

**Comment by yarikoptic** [comment]
what does it have then -- is there a list somewhere so we could know what tools we could use in %setup stage?

**Comment by vsoch** [comment]
hey @yarikoptic - I don't see giving users control of the servers anytime soon, in fact we are securing the environment even more so. I'm going to close this issue.

**Comment by yarikoptic** [comment]
well, the issue still that if %setup fails one way (me trying to do evil) or another (or not evil), I think the build should fail.  Also it would still be nice to get some description of the build boxes -- what to expect to have there

**Comment by vsoch** [comment]
oh I see! Yes we can definitely put more information about the particulars of the builder. I'll re-open until I do this.

**Comment by vsoch** [comment]
hey @yarikoptic let me know what else you want added here - https://github.com/singularityhub/singularityhub.github.io/wiki/Meet-Builders

**Comment by vsoch** [comment]
I have added details, closing this issue.
