### ISSUE TITLE
Description missing on detail page

### ISSUE THREAD

**Issue by dtrudg** [singularityhub/singularityhub.github.io#54]
When searching/paging through https://singularity-hub.org/collections there is a description for containers shown - e.g.

researchapps/edd | 1 | Enriched Domain Detector for ChIP-seq data
-- | -- | --

When looking at the detail page: https://singularity-hub.org/collections/74/ - there is no description shown.

This can be confusing, esp. when sending a direct link to someone.

**Comment by vsoch** [comment]
okay, this should be all set! Thanks @dctrud
