### ISSUE TITLE
ERROR Improperly formed manifest, layers or fsLayers must be present

### ISSUE THREAD

**Issue by colinmcnally** [singularityhub/singularityhub.github.io#57]
## Link to Container Collection Log, Build, or Collection (in that order)

https://singularity-hub.org/containers/2971/log

### Behavior when Building Locally

I have not attempted this build locally, don't have a local singularity install where I have root. It is a minimal description, with only a bootstap from Docker.

### Error on Singularity Hub

The error line in the log is:
ERROR Improperly formed manifest, layers or fsLayers must be present

### What do you think is going on?

This appears to be the behaviour described in the recently patched Singularity issue:
https://github.com/singularityware/singularity/issues/925

**Comment by vsoch** [comment]
hey @colinmcnally! Yes, this needs to be fixed, and pronto! I'm creating builders with the patch release for the software right now - I just posted an FYI message: https://singularity-hub.org/. Stay tuned!

**Comment by vsoch** [comment]
hey @colinmcnally ! This should be all set. Please click the "Edit Builders" in your collection view to update to builder 2.3.2 (size 50 or 100GB) and then retry the build. Let us know here if it works for you!

**Comment by colinmcnally** [comment]
Thanks @vsoch! It works now after the switch to builder 2.3.2.

**Comment by vsoch** [comment]
Awesome! Build away, @colinmcnally
