### ISSUE TITLE
[wishlist] Download stats of some kind?

### ISSUE THREAD

**Issue by yarikoptic** [singularityhub/singularityhub.github.io#58]
no error here -- just a wishlist (if possible) to provide some feedback on either any given container was downloaded and how many times

**Comment by vsoch** [comment]
This is implemented in Singularity Registry, but not Hub. I'll see if it's easy / non trivial to use in both places.

**Comment by vsoch** [comment]
hey @yarikoptic - your wish is done! The new singularity hub has a page to keep track of downloads (as in calls to retrieve via the API). There is also a page for user favorites (stars). 

![image](https://user-images.githubusercontent.com/814322/31303769-c26e9fc4-aac7-11e7-9ee6-a9fdc397f5af.png)

**Comment by vsoch** [comment]
This will be released with Singularity Hub 2.0.

**Comment by yarikoptic** [comment]
Very much thank you @vsoch

**Comment by yarikoptic** [comment]
Hi @vsoch , sorry to pester -- was 2.0 released already?  I just thought to check the downloads count but see none at eg. https://singularity-hub.org/collections/209 

Thanks in advance for the clarification

**Comment by vsoch** [comment]
yep it's on the main page! 19!

![image](https://user-images.githubusercontent.com/814322/34689413-4de17ff4-f46a-11e7-9c61-9ab04e524378.png)

**Comment by yarikoptic** [comment]
HA -- I got lost!  I went not to "All collections" but "Registry" and that one looked like this:
![img](http://www.onerussian.com/tmp/gkrellShoot_01-08-18_154517.png)
Now I found it, thanks!  Hopefully more to come (i.e. >19 downloads). Cheers!!

**Comment by vsoch** [comment]
haha, wrong website :P No worries!!
