### ISSUE TITLE
shub: build failed without obvious error

### ISSUE THREAD

**Issue by yinglilu** [singularityhub/singularityhub.github.io#59]
## Link to Container Collection Log, Build, or Collection (in that order)
https://singularity-hub.org/containers/3283/log

### Behavior when Building Locally
Success

### Error on Singularity Hub
No obvious error.

### What do you think is going on?
No idea.

### Buider spec:
could builder: singularity-builder-2.3.2-50gb
enable debug printing: yes
image size: 20000

### Singularity file:
Bootstrap: docker
From: ubuntu:xenial

#########
%setup
#########
cp ./install_scripts/*.sh $SINGULARITY_ROOTFS

#########
%post
#########

bash 00.install_basics_sudo.sh
bash 03.install_anaconda2_nipype_dcmstack_by_binary.sh /opt
bash 10.install_afni_fsl_sudo.sh
bash 11.install_minc_by_deb_sudo.sh /opt
bash 12.install_c3d_by_binary.sh /opt
bash 13.install_itksnap_by_binary.sh /opt
bash 14.install_dcm4che_ubuntu.sh /opt
#bash 15.install_freesurfer_by_source.sh /opt
bash 16.install_ants_by_binary.sh /opt
bash 17.install_dcm2niix_by_binary.sh /opt
bash 18.install_elastix_by_binary.sh /opt
bash 19.install_dcmtk_by_binary.sh /opt
bash 20.install_slicer_by_binary.sh /opt
bash 21.install_MRtrix3_by_source_sudo.sh /opt
bash 22.install_ashs_by_binary.sh /opt
bash 23.install_heudiconv_by_source.sh /opt
bash 24.install_bids-validator_sudo.sh

#remove all install scripts
rm *.sh

#create scripts folder
mkdir -p /opt/scripts

#########
%environment
#########
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#anaconda2
export PATH=/opt/anaconda2/bin/:$PATH

#c3d
export PATH=/opt/c3d/bin:$PATH
export LD_LIBRARY_PATH=/opt/c3d/lib/c3d_gui-1.1.0:$LD_LIBRARY_PATH

#itksnap
export PATH=/opt/itksnap/bin:$PATH
export LD_LIBRARY_PATH=/opt/itksnap/lib/snap-3.6.0:$LD_LIBRARY_PATH

#dicom_retrieve.py use dcm4che's getscu. So, put dcm4che's PATH before dcmtk's PATH
#dcm4che
export PATH=/opt/dcm4che-3.3.8/bin:$PATH

#freesurfer
export PATH=/opt/freesurfer/bin:$PATH
export FREESURFER_HOME=/opt/freesurfer
export FSFAST_HOME=/opt/freesurfer/fsfast
export FSF_OUTPUT_FORMAT=nii.gz
export SUBJECTS_DIR=/opt/freesurfer/subjects
export MNI_DIR=/opt/fresurfer/mni
export MINC_BIN_DIR=/opt/freesurfer/mni/bin
export MINC_LIB_DIR=/opt/freesurfer/mni/lib

#ants
export PATH=/opt/ants:$PATH
export ANTSPATH=/opt/ants

#dcm2niix
export PATH=/opt/mricrogl_lx:$PATH

#elastix
export PATH=/opt/elastix:$PATH
export LD_LIBRARY_PATH=/opt/elastix:$LD_LIBRARY_PATH

#dcmtk
export PATH=/opt/dcmtk/bin:$PATH

#slicer
export PATH=/opt/slicer:$PATH

#MRtrix3
export PATH=/opt/mrtrix3/bin:$PATH

#ashs
export PATH=/opt/ashs/ashs-fastashs/bin:$PATH

#minc
export MINC_TOOLKIT=/opt/minc/1.9.15
export MINC_TOOLKIT_VERSION="1.9.15-20170529"
export PATH=/opt/minc/1.9.15/bin:/opt/minc/1.9.15/pipeline:${PATH}
export PERL5LIB=/opt/minc/1.9.15/perl:/opt/minc/1.9.15/pipeline:${PERL5LIB}
export LD_LIBRARY_PATH=/opt/minc/1.9.15/lib:/opt/minc/1.9.15/lib/InsightToolkit:${LD_LIBRARY_PATH}
export MNI_DATAPATH=/opt/minc/1.9.15/share
export MINC_FORCE_V2=1
export MINC_COMPRESS=4
export VOLUME_CACHE_THRESHOLD=-1
export MANPATH=/opt/minc/1.9.15/man:${MANPATH}

#heudiconv
export PATH=/opt/heudiconv:$PATH

#scripts
export PATH=/opt/scripts:$PATH

#########
%files
#########
./files_scripts/dicom_retrieve.py /opt/scripts/dicom_retrieve.py
./files_scripts/7T_TOPSY_BIDS_heuristic.py /opt/scripts/7T_TOPSY_BIDS_heuristic.py

**Comment by vsoch** [comment]
It looks like a bad gateway (502). Have you tried this more than once? The BIDS container are infamously known for being huge / installation at root so this might be an issue related to that, or a less frequent server blurp. I'm currently working against the clock to finish the next version of shub, so we might be better off waiting for that.

**Comment by vsoch** [comment]
hey @yinglilu could you please try this on the new singularity hub? Thanks! I'm going to close this issue, and please re-open if you still have trouble.
