### ISSUE TITLE
Build hung in "Running" status for 2 days (either due to image size or %test pipes)

### ISSUE THREAD

**Issue by omsai** [singularityhub/singularityhub.github.io#60]
### Link to Container Collection Log, Build, or Collection (in that order)

- Collection log: N/A because the build hangs with status "Running".
- Build: https://github.com/UConn-HPC/singularity-ctffind
- Collection: https://singularity-hub.org/collections/454/

### Behavior when Building Locally

Build proceeds as normal.  I'm using an older version of Singularity than on the hub, but which has worked fine for my [other recent hub build](https://singularity-hub.org/collections/432/).  I've changed the Hub to use a setting of 1500 MB because my final local image is 1.3 GB:

``` bash
$ du -h ctffind-4.1.8.img 
1.3G    ctffind-4.1.8.img
```

Local build machine info:

``` bash
$ singularity --version
2.2.1
$ docker --version
Docker version 1.12.1, build 23cf638
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

### Error on Singularity Hub

The remained in the "Running" state for 2 days.  Unfortunately I deleted hung build in my effort to test the fix.  I applied 2 fixes simultaneously: increasing the building allowable size from 1200 to 1500 MB, and removing pipes from the `%test` section in case that was causing the hang: UConn-HPC/singularity-ctffind@332790ab9e602f273b3bb3ac58b12fd377ee8e6c

Previously the problem I had was the build would fail even before executing the first `%post` command ([example log](https://singularity-hub.org/containers/3247/log)).  I was able to resolve this problem by switching from `singularity-builder-2-3-50gb` to `singularity-builder-2-3-2-50gb` as suggested by the hub homepage announcement.

### What do you think is going on?

- Either the build hangs when the image size is larger than what the builder allows.  This should not happen: the hub builder should fail with an error complaining about the image size is too big and suggest changing the builder setting.
- Another possibility is having pipes in the `%test` stage caused it to fail which might have been fixed by UConn-HPC/singularity-ctffind@332790ab9e602f273b3bb3ac58b12fd377ee8e6c

**Comment by vsoch** [comment]
hey @omsai ! Thanks for the post, and sorry about the troubles. I'm not sure about this one - the log on the builder suggests it had some issue with downloading errors:

```
DEBUG:shub_builder:build_folder is true, creating /tmp/tmpvaihc3gv/image
ERROR Error downloading https://index.docker.io/v2/tensorflow/tensorflow/blobs/sha256:2c4b3f104d307bcb5f7274b428f41590d7486fa0539447de9b120a8c2d36d8ce. Do you have permission to write to /root/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/tensorflow/tensorflow/blobs/sha256:15d538e0e90c358f5b4fc839b20b70e4a80f0db002466bccf7a39f3086c9d8cc. Do you have permission to write to /root/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/tensorflow/tensorflow/blobs/sha256:dc27a084064fee108f4d486469939bbfa6a5b16f6d6d3c6b5b2475e938f4c71e. Do you have permission to write to /root/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/tensorflow/tensorflow/blobs/sha256:c220aa3cfc1bff0c1df733eac869a66476ea35136c69d881da1e297ed8d0af2f. Do you have permission to write to /root/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/tensorflow/tensorflow/blobs/sha256:2e9398f099dcc5a3e5521205e1f55ee5d7665e203193cf48b32553eabcca323c. Do you have permission to write to /root/.singularity/docker?
ERROR Error downloading https://index.docker.io/v2/tensorflow/tensorflow/blobs/sha256:1300883d87d5ae0582a4e0f3f86ad93985b18676e8d829f6f3b4990403fdf145. Do you have permission to write to /root/.singularity/docker
```
but I've just run it and watched, and it seemed ok. Have you tried this build more than once? I don't think the issue is image size. I've never done anything with pipes in test, so that might be the issue. Maybe I would retry removing the test, and add back when we release the next version of singularity hub (with updated 2.4 builders).

**Comment by omsai** [comment]
The hang in "Running" happened only once, so it's quite possible there was a network error and I was confused after switching from 2-3 to the 2-3-2 builder and seeing it change from Erroring out to hanging in Running.

I'm leaving the pipes out for now in `%test`.  Upstream makes doesn't provide a basic usage message because it either wants to read from stdin or enter interactive mode, and my using `head` with a short line count before the output reached the interactive prompt was my hacky way of running the test.  So this is an example of where it might be appropriate for me to complain to upstream to help make their project more testable to make it singularity awesome :o)

Thanks for helping me get to the bottom of this @vsoch!

**Comment by vsoch** [comment]
sure thing! I hope to get the next version for you to use soon :)
