### ISSUE TITLE
Mobile rendering hides the menu on the left

### ISSUE THREAD

**Issue by yarikoptic** [singularityhub/singularityhub.github.io#61]
I thought I have complained before but can't find it, sorry if a duplicate
See
https://photos.app.goo.gl/CgjB23XL9pyZ9pW12

**Comment by vsoch** [comment]
hey @yarikoptic ! I might not get around to fixing this for this particular go around - it's a good thing to fix and an important detail for mobile users, but not essential (and I wouldn't advocate using shub on mobile anyway, ha)

**Comment by vsoch** [comment]
Fixed! Amazing that I stumbled into a (sort of?) working solution. Closing!
