### ISSUE TITLE
maximum build time?

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularityhub.github.io#64]
hey @cclerget what do you think about enforcing a maximum build time? This will ensure that if something goes weird, there is a job in the queue to automatically kill a build (maybe one day?)

**Comment by cclerget** [comment]
@vsoch Yes ! timeout command (http://man7.org/linux/man-pages/man1/timeout.1.html) seems appropriate: `timeout -s KILL 2h singularity build ...`, after two hour, command is killed with exit code 137 which mean build job has been killed because too long

**Comment by vsoch** [comment]
okey doke, I just added a very simple (with 2 hour limit, this should be reasonable or you think too short?) when we are ready for another go of testing, I can update the builder.

**Comment by cclerget** [comment]
2 hours for most build is enough, at worst it could be adjusted
