### ISSUE TITLE
Container Collections / Branches  - last sentence is not clear

### ISSUE THREAD

**Issue by alaindomissy** [singularityhub/singularityhub.github.io#65]
## Link to singularity-hub wiki page

https://github.com/singularityhub/singularityhub.github.io/wiki/Release-Notes

The last sentence in this paragraph seems to miss something:
```
Container Collections
Branches 
We recommend that you build from fewer (or just master) or a production branch to not create confusion.
```
Did you mean:
To avoid confusion, we recommend that you build from fewer branches. Ideally, just build from a single branch: either master or a production branch.

**Comment by vsoch** [comment]
Fixed!!

For small details like these, give a go at editing the wiki. Sort of like wikipedia !

**Comment by alaindomissy** [comment]
Thanks. And I would but I just could not figure out how to edit the wiki ! lol... it is not like submitting Pull Request, is it ?
