### ISSUE TITLE
Github permissions

### ISSUE THREAD

**Issue by mathiaswagner** [singularityhub/singularityhub.github.io#66]
I wanted to login to singularity hub but it ask for a lot of permissions for which I have a hard time seeing the necessity. For me it asked for:

```
Personal user data
Full access
This application will be able to read and write all user data. This includes the following:

Private email addresses
Private profile information
Followers
Learn more

Repositories
Public and private
This application will be able to read and write all public and private repository data. This includes the following:

Code
Issues
Pull requests
Wikis
Settings
Webhooks and services
Deploy keys
Collaboration invites
```

I do get read access for the code but read **and write** access to some of the information seems unnecessary. Is it documented somewhere what you need and why?
I recommend reducing it to the bare minimum.
I get that you need to read the code of the repositories (not sure about private ones though) but reading and writing private information and all the settings, deploy keys, invites really worries me.

**Comment by vsoch** [comment]
hey @mathiaswagner ! We have changed this with the new version. Would you like to be one of our testers and see if the new permissoins model is better fit for your needs?

**Comment by mathiaswagner** [comment]
Sure, happy to help.

**Comment by vsoch** [comment]
Great! I just sent you an email with details. Please post here any issues you find and I'll fix them real time!

**Comment by vsoch** [comment]
hey @mathiaswagner have you checked it out? I saw that you had migration requests? If you make corresponding collections I can migrate the images for you (and apologies if you did and I missed the repository names)

**Comment by vsoch** [comment]
ping @mathiaswagner ?

**Comment by mathiaswagner** [comment]
Sorry for the delay. The new version is fine.
