### ISSUE TITLE
Logo incorrect (GitHub Icon/Picture fetched incorrectly? ) 

### ISSUE THREAD

**Issue by apeltzer** [singularityhub/singularityhub.github.io#67]
### Error on Singularity Hub

When using the Singularity hub, the picture used in the top is incorrectly fetched from Github. My current user logo is definitely different from the one that is used by Singularity hub. Its still the first (and outdated) picture I used years ago when setting up my Github back then ;-) 
![screenshot from 2017-10-16 22-07-53](https://user-images.githubusercontent.com/2359510/31632806-894e37b4-b2be-11e7-9b2f-a6de00a4f9d6.png) (as seen on Singularity-Hub, outdated picture - and I didn't change it recently. Already > 1 yr old. 
![screenshot from 2017-10-16 22-08-12](https://user-images.githubusercontent.com/2359510/31632807-896cf816-b2be-11e7-999b-405cec6ca099.png) (current picture on Github)

### What do you think is going on?

I can't say - its a minor thing, but still not correct.

**Comment by vsoch** [comment]
It's actually not pulling from github - it's your gravatar, which is associated with your email account. I think if you wanted to change that you would go to --> https://en.gravatar.com/

**Comment by apeltzer** [comment]
Correct, I will close this now!
