### ISSUE TITLE
Investigate more granular permissions control for membership

### ISSUE THREAD

**Issue by alexhrescale** [singularityhub/singularityhub.github.io#7]
This may allow more involvement from the company account when tight control over private access is needed.

I don't actually know the extent of exposure after granting private repo access from the github OAuth signup, but this uncertainty is likely a blocker at the organization level.

Thanks!

**Comment by vsoch** [comment]
hey @alexhrescale how does this look?

![image](https://user-images.githubusercontent.com/814322/27842785-01d7bf1a-60db-11e7-8d9a-5ca30d9cab17.png)

This would be for the next version I'm working on now. It gives no direct code access, but the webhooks to know when the user commits should still work, along with making an account associated with the user email.

**Comment by vsoch** [comment]
I'm going to close this issue in favor of #19 , the change is done and will be in the next release. Thanks @alexhrescale !
