### ISSUE TITLE
Unable to pull container: not in gzip format

### ISSUE THREAD

**Issue by edraizen** [singularityhub/singularityhub.github.io#77]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/containers/394

### Behavior when Building Locally

When I pull the container, I get the following error:

### Error on Singularity Hub

> singularity pull shub://edraizen/Singularity
gzip: ./edraizen-Singularity-master.img.gz: not in gzip format
ERROR Error extracting image, cleaning up.
ERROR: pulling container failed!

**Comment by vsoch** [comment]
Hey @edraizen! You need to update your Singularity client. The images on the new shub are in squashfs, so older clients that try to extract them will see this error.

**Comment by edraizen** [comment]
Ok, I'll try that. Thanks!
