### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by bneron** [singularityhub/singularityhub.github.io#79]
## Link to Container Collection Log, Build, or Collection (in that order)

Write here.

### Behavior when Building Locally

When the section test is name test**s** by mistake. the error message is not really helpful:

/bin/sh: 0: Can't open s

 The complete trace and a singularity recipe to reproduce the behavior
[Singularity.txt](https://github.com/singularityhub/singularityhub.github.io/files/1418402/Singularity.txt)

> sudo singularity build foo.img Singularity 
> Using container recipe deffile: Singularity
> Sanitizing environment
> Adding base Singularity environment to container
> Docker image path: index.docker.io/library/ubuntu:zesty
> Cache folder set to /root/.singularity/docker
> Exploding layer: sha256:8b23367590c32dbb6954ab3cc9b6c451b9763556c72a893538efe88583f6a5dc.tar.gz
> Exploding layer: sha256:c7feb578947e4b86e0a0cff64b42489dc1305bbacdb3ed36d0afe95a19ebf845.tar.gz
> Exploding layer: sha256:ac836f06379c8d7356e0d2e7dbb3e9f3924616527fa51b95545fb455eec31f08.tar.gz
> Exploding layer: sha256:be286dc472df31f16953d34151f836d0186fddeea6cd56dcefd2a6d46a992500.tar.gz
> Exploding layer: sha256:5533df5f353d9fbcbd081e9dd653fe7d8ddebed958d1f0e56fa4a87b216f13c1.tar.gz
> Exploding layer: sha256:f6be9f4f6905406c1e7fd6031ee3104d25ad6a31d10d5e9192e7abf7a21e519a.tar.gz
> User defined %runscript found! Taking priority.
> Running post scriptlet
> Adding deffile section labels to container
> Adding runscript
> Adding runscript help
> Running test scriptlet
> /bin/sh: 0: Can't open s
> ABORT: Aborting with RETVAL=255
> Cleaning up...
> 

### Error on Singularity Hub

Write here.

### What do you think is going on?

Write here.

**Comment by vsoch** [comment]
Parsing for correctness of the build recipe is something we haven't done yet, and I think it's best to bring up an issue here: https://github.com/singularityware/singularity/issues with Singularity proper. Singularity Hub shouldn't do anything special other than run the build, so if there is an error not being caught (as is above) it should be added there. That way, if you were to do the build locally, the output received would be consistent.

**Comment by bneron** [comment]
done https://github.com/singularityware/singularity/issues/1097
