### ISSUE TITLE
re-enable manual download with next singularity release

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularityhub.github.io#8]
There seems to be a bug with running the compressed images, currently. there are two errors that I can observe, and both are handled by the Singularity executable. The first is the image name (this is an image I just downloaded from the interface):

      singularity run singularity-hub-regional%2Fgithub.com%2Fpforai%2Fslamdunk%2F75c4350eacd1976ff360238f4f1adc5ffb102a3c%2F4c0b540a1627f19cb8c0e8bd61d674aa.img.gz 
     ERROR  : Illegal input character '%' in: 'SINGULARITY_IMAGE=singularity-hub-regional%2Fgithub.com%2Fpforai%2Fslamdunk%2F75c4350eacd1976ff360238f4f1adc5ffb102a3c%2F4c0b540a1627f19cb8c0e8bd61d674aa.img.gz'
     ABORT  : Retval = 255

The reason it has that long nasty url, and with illegal characters, is because the image is stored in google cloud (bucket) with a reversed github username. Something like:

      /github.com/username/reponame/commit/content-has.img.gz

The illegal characters are of course translating that to the browser url. The first thing singularity client does to fix this is to rename the image according to just it's hash, the end of that.  We can sort of mimic that by renaming manually:

      $ mv singularity-hub-regional%2Fgithub.com%2Fpforai%2Fslamdunk%2F75c4350eacd1976ff360238f4f1adc5ffb102a3c%2F4c0b540a1627f19cb8c0e8bd61d674aa.img.gz myimage.img.gz

Now testing running it..

      singularity run myimage.img.gz 
      ERROR  : File is not a valid Singularity image, aborting...
      ABORT  : Retval = 255

Now, the final bit is that there seems to be a current bug with singularity "sniffing" that the image is compressed, and uncompressing it. @gmkurtzer this should work, no? Methinks this should be fixed in the next release, but let's keep an eye on it in case not. The fix, which is done by the Singularity client when the image is pulled, is to decompress properly:

      gzip -d -f myimage.img.gz 

and then the shell works
  
       singularity run myimage.img 
       singularity shell myimage.img
       Singularity: Invoking an interactive shell within container...
       Singularity.myimage.img> $ 
 
I have disabled (manual downloads) for now and we can revisit this issue with the next software release.

**Comment by pforai** [comment]
+1

**Comment by vsoch** [comment]
@pforai I was going to close this issue, because you can easily pull a container with singularity command line, like

```
singularity pull shub://vsoch/hello-world
```
And further, the software handles de-compressing the file, which isn't obviously necessary to do, and the command isn't something that users are likely to get right the first time. Do you see any rationale for still needing this?
