### ISSUE TITLE
Issue boostrapping from shub base

### ISSUE THREAD

**Issue by jekriske** [singularityhub/singularityhub.github.io#81]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/containers/601/log

### Behavior when Building Locally

No issues when building locally

### Error on Singularity Hub

`/usr/local/libexec/singularity/functions: line 356: FROM: unbound variable`

### What do you think is going on?

My shub base image started with a centos image from Docker... no issues there.
This image builds upon that original shub image. It works fine locally in multiple VMs and yet fails on shub seemingly as it's creating the new container after %post is complete.

**Comment by vsoch** [comment]
With the updates to the server do you want to try this again? Then I will manually debug in the case that it persists. The other thing you can try is to switch the builder from the default to the other provided - which has had some updates and might make a difference.

**Comment by jekriske** [comment]
Looks like the same type of error:
https://www.singularity-hub.org/containers/615/log
```
Finalizing Singularity container
Calculating final size for metadata...
/usr/local/libexec/singularity/functions: line 356: FROM: unbound variable
Cleaning up...
Cleaning up...
```

**Comment by vsoch** [comment]
okay just reproduced the error building manually - and issue is filed here https://github.com/singularityware/singularity/issues/1118

Hopefully we can get the image fixed and the builder rebuilt to support shub bootstrap! Thanks for your patience as we do that.

**Comment by vsoch** [comment]
just recording here - plan is to update builder with a security release that is coming out soon. Stay tuned :)

**Comment by vsoch** [comment]
hey @jekriske !

I've just quietly added the new builder (with Singularity 2.5) as an option, and I think it would be worth a go to see if your container builds! To change your builder:

 - navigate to your Collection
 - click on "Settings"
 - under the Builder settings tag, change the cloud builder to `singularity-builder-2-5-100gb`

![image](https://user-images.githubusercontent.com/814322/39400175-4f814304-4af9-11e8-9f55-043ea9b45cd7.png)

And then commit and push again to trigger of course, and report back to me. Thank you!

**Comment by jekriske** [comment]
@vsoch It builds ok with the new 2.5.0 builder, congrats

However, the build spec content at 
https://www.singularity-hub.org/containers/2281
is incorrect. The build metrics are correct, just not the spec content, it's based on an older commit.

**Comment by vsoch** [comment]
Did you push a new commit?

**Comment by vsoch** [comment]
Your build is set to manual, so you would need to choose a commit or set it to build on commit and choose that one.

**Comment by vsoch** [comment]
And woohoo! There were a TON of changes and I did one server restart and there doesn't seem to be any huge obvious damage, +1 points dinosaur-robot developers!

**Comment by jekriske** [comment]
yes, I had pushed another commit and manually triggered the build. The container itself is the latest, but the build spec didn't change. Now, the spec listed doesn't match the spec used by the builder to build the actual container. The spec shown isn't the one in the commit.

This can also be verified in the container itself:
```
$ singularity pull shub://jekriske/rstudio
$ singularity inspect -d jekriske-rstudio-master-latest.simg | grep Rstudio_Version
Rstudio_Version 1.1.447
```
vs `Rstudio_Version 1.1.442` on https://www.singularity-hub.org/containers/2281 even though the commit listed: `4d898b2` is correct. Everything about the build process happened correctly, except for the singularity-hub website becoming out of sync with the contents of the container.

**Comment by vsoch** [comment]
Ah thanks for the clarification! I think I know the bug - the updated spec comes from the static file saved in Storage, and I just left that file out :) Here is where that happens:

```python
            elif name == "Singularity":
                container.spec = requests.get(bfile["mediaLink"]).text
```
I will fix up the builder, give me a few minutes and we can test again! I'll let you know when he's ready!

**Comment by vsoch** [comment]
okey doke! Ready for your testing again. The repo I just tested is here:

https://www.singularity-hub.org/containers/2688

And the local recipe is:

```
Bootstrap:docker
From:ubuntu:16.04

%post

    echo "The sun is shining, the weather is sweeeet..."

%runscript

    exec echo "You say please, but all I see is pizza.."

```
And commit starting with 130... for image hash starting with a1 (not the steak sauce) is also correctly found:

![image](https://user-images.githubusercontent.com/814322/39410218-881135c0-4bc2-11e8-95f0-ae12f5acebfc.png)

Could you give it another go, and hopefully the same works smoothly for you?

**Comment by vsoch** [comment]
closing, inactivity
