### ISSUE TITLE
When subsequent pushes (and container not frozen) delay start

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularityhub.github.io#83]
the builder for a (currently running build) that is cancelled needs some padding time before launching another build, otherwise the builder gets stuck in "WAITING" because the instance cannot be generated.

**Comment by tmozgach** [comment]
@vsoch In my case, the builder got stuck in "Pending" status, I was trying to delete the container build and re-commit it, but it doesn't work. Is that related problem? 

https://www.singularity-hub.org/collections/354
