### ISSUE TITLE
Deployment build webhook returning 500

### ISSUE THREAD

**Issue by eriknstevenson** [singularityhub/singularityhub.github.io#85]
Hi again,

I think I'm quite close to getting the singularity hub deployment build triggering after docker build working as I asked about in #84, but my deployment webhook is receiving a 500 error response from singularity hub.

### On Singularity Hub

I enabled deployment build on [my collection](https://www.singularity-hub.org/collections/214) settings.

### On Travis

Configured to build the docker image and push to Dockerhub.

### On GitHub

Set up the GitHub Auto-Deployment integration to trigger on the status code received from Travis (using guide located [here](https://developer.github.com/v3/guides/automating-deployments-to-integrators/#sending-deployments-whenever-you-push-to-a-repository).
I set the singularity hub webhook in my repository settings to send all events (it was previous set to only send push events).

### Webhook Request Headers
```
Request URL: https://www.singularity-hub.org/hooks/build/push
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/3cf879e
X-GitHub-Delivery: d90d9440-c554-11e7-8a15-0e6c4d257036
X-GitHub-Event: deployment
X-Hub-Signature: sha1=4cd0885ce07df5496400fa277738c074c71df796
```

### Webhook Payload
```
{
  "deployment": {
    "url": "https://api.github.com/repos/narrative/remoll/deployments/58518568",
    "id": 58518568,
    "sha": "26506f673fccb9e8ce231c72719f17a2f121eb13",
    "ref": "26506f67",
    "task": "deploy",
    "payload": {

    },
    "environment": "production",
    "description": "Auto-Deployed on status by GitHub Services@3cf879e8 for web-flow - master@26506f67",
    "creator": {
      "login": "narrative",
      "id": 344609,
      "avatar_url": "https://avatars1.githubusercontent.com/u/344609?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/narrative",
      "html_url": "https://github.com/narrative",
      "followers_url": "https://api.github.com/users/narrative/followers",
      "following_url": "https://api.github.com/users/narrative/following{/other_user}",
      "gists_url": "https://api.github.com/users/narrative/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/narrative/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/narrative/subscriptions",
      "organizations_url": "https://api.github.com/users/narrative/orgs",
      "repos_url": "https://api.github.com/users/narrative/repos",
      "events_url": "https://api.github.com/users/narrative/events{/privacy}",
      "received_events_url": "https://api.github.com/users/narrative/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-11-09T13:49:46Z",
    "updated_at": "2017-11-09T13:49:46Z",
    "statuses_url": "https://api.github.com/repos/narrative/remoll/deployments/58518568/statuses",
    "repository_url": "https://api.github.com/repos/narrative/remoll"
  },
  "repository": {
    "id": 110004526,
    "name": "remoll",
    "full_name": "narrative/remoll",
    "owner": {
      "login": "narrative",
      "id": 344609,
      "avatar_url": "https://avatars1.githubusercontent.com/u/344609?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/narrative",
      "html_url": "https://github.com/narrative",
      "followers_url": "https://api.github.com/users/narrative/followers",
      "following_url": "https://api.github.com/users/narrative/following{/other_user}",
      "gists_url": "https://api.github.com/users/narrative/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/narrative/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/narrative/subscriptions",
      "organizations_url": "https://api.github.com/users/narrative/orgs",
      "repos_url": "https://api.github.com/users/narrative/repos",
      "events_url": "https://api.github.com/users/narrative/events{/privacy}",
      "received_events_url": "https://api.github.com/users/narrative/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/narrative/remoll",
    "description": "12 GeV Moller Simulation",
    "fork": true,
    "url": "https://api.github.com/repos/narrative/remoll",
    "forks_url": "https://api.github.com/repos/narrative/remoll/forks",
    "keys_url": "https://api.github.com/repos/narrative/remoll/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/narrative/remoll/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/narrative/remoll/teams",
    "hooks_url": "https://api.github.com/repos/narrative/remoll/hooks",
    "issue_events_url": "https://api.github.com/repos/narrative/remoll/issues/events{/number}",
    "events_url": "https://api.github.com/repos/narrative/remoll/events",
    "assignees_url": "https://api.github.com/repos/narrative/remoll/assignees{/user}",
    "branches_url": "https://api.github.com/repos/narrative/remoll/branches{/branch}",
    "tags_url": "https://api.github.com/repos/narrative/remoll/tags",
    "blobs_url": "https://api.github.com/repos/narrative/remoll/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/narrative/remoll/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/narrative/remoll/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/narrative/remoll/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/narrative/remoll/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/narrative/remoll/languages",
    "stargazers_url": "https://api.github.com/repos/narrative/remoll/stargazers",
    "contributors_url": "https://api.github.com/repos/narrative/remoll/contributors",
    "subscribers_url": "https://api.github.com/repos/narrative/remoll/subscribers",
    "subscription_url": "https://api.github.com/repos/narrative/remoll/subscription",
    "commits_url": "https://api.github.com/repos/narrative/remoll/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/narrative/remoll/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/narrative/remoll/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/narrative/remoll/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/narrative/remoll/contents/{+path}",
    "compare_url": "https://api.github.com/repos/narrative/remoll/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/narrative/remoll/merges",
    "archive_url": "https://api.github.com/repos/narrative/remoll/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/narrative/remoll/downloads",
    "issues_url": "https://api.github.com/repos/narrative/remoll/issues{/number}",
    "pulls_url": "https://api.github.com/repos/narrative/remoll/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/narrative/remoll/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/narrative/remoll/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/narrative/remoll/labels{/name}",
    "releases_url": "https://api.github.com/repos/narrative/remoll/releases{/id}",
    "deployments_url": "https://api.github.com/repos/narrative/remoll/deployments",
    "created_at": "2017-11-08T16:56:29Z",
    "updated_at": "2017-11-08T16:56:31Z",
    "pushed_at": "2017-11-09T13:29:46Z",
    "git_url": "git://github.com/narrative/remoll.git",
    "ssh_url": "git@github.com:narrative/remoll.git",
    "clone_url": "https://github.com/narrative/remoll.git",
    "svn_url": "https://github.com/narrative/remoll",
    "homepage": null,
    "size": 5739,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Fortran",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "narrative",
    "id": 344609,
    "avatar_url": "https://avatars1.githubusercontent.com/u/344609?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/narrative",
    "html_url": "https://github.com/narrative",
    "followers_url": "https://api.github.com/users/narrative/followers",
    "following_url": "https://api.github.com/users/narrative/following{/other_user}",
    "gists_url": "https://api.github.com/users/narrative/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/narrative/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/narrative/subscriptions",
    "organizations_url": "https://api.github.com/users/narrative/orgs",
    "repos_url": "https://api.github.com/users/narrative/repos",
    "events_url": "https://api.github.com/users/narrative/events{/privacy}",
    "received_events_url": "https://api.github.com/users/narrative/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

### Singularity Hub Webhook Response

**Error 500**

```
Connection: keep-alive
Content-Length: 0
Content-Type: application/json
Date: Thu, 09 Nov 2017 13:49:47 GMT
Server: nginx/1.13.5
X-Frame-Options: SAMEORIGIN
```

### What do you think is going on?

I think this is caused by the fact that I have left the webhook URL to the default which is `https://www.singularity-hub.org/hooks/build/push`. If it is the case that this must be updated to some other URL, perhaps details on this can be added to the documentation for deployment builds.

Thanks

**Comment by vsoch** [comment]
The webhook should be the same url, the information that you provided here, this is great! Let me take a look at the server.

**Comment by vsoch** [comment]
okay! The bug was very minor - the key to look for deployment used to be a flat lookup (eg, `payload["deployment_status"]` and it looks like it is not under just `payload["deployment"]`. I was able to walk through the steps and get your (previous) deployment to trigger a builder to run, and he's running full steam!

![image](https://user-images.githubusercontent.com/814322/32613434-c101f68c-c51f-11e7-9e83-4f042c0bb849.png)


What we can do is wait for it to finish, and be sure there aren't any remaining errors. If everything looks good, then a "real" test can be for when your next (actual) deployment is done.

If this all works, would you mind contributing some outline for the specific steps that you took? I'd like to add a better description of steps to our docs. One thing we might need to look into (and have users add it manually as you did) is why the deployment scope isn't active. I do ask for it when the user authenticates, eg:

```
SOCIAL_AUTH_GITHUB_SCOPE = ["admin:repo_hook",
                            "repo:status",
                            "user:email",
                            "read:org",
                            "admin:org_hook",
                            "deployment_status"]
```
Based on their docs, I think that should do it? 

https://developer.github.com/v3/repos/deployments/

I will keep watching the build and send you an update. I did some other changes to fix bugs (always like to do this if the server is going to restart anyway) so I want to make sure everything is up and running as it should before reporting back.

**Comment by vsoch** [comment]
Houston, we have container! Here is for you to check out --> https://www.singularity-hub.org/collections/214

**Comment by eriknstevenson** [comment]
Really appreciate the quick turnaround on this. I can definitely provide a brief write up of the steps I took to set this up. 

As for setting up the webhook to be triggered by deploy events out of the box (not requiring users to enable this themselves), I think [this](https://developer.github.com/v3/repos/hooks/#create-a-hook) might be useful, in particular the `events` parameter might be what you're looking for?

Again thanks for the quick fix on this.

**Comment by vsoch** [comment]
Found it!

```
 params = { "name" : "web",
               "active" : True,
               "events" : ["push", "deployment"],
               "config" : config }
```
So now we have the deployment added to events, plus the scope adjusted. This should work for users that haven't already created a webhook, and for those that have, we can give instruction for how to add the scope. The group is likely relatively small so it shouldn't be a huge hindrance.

I'm really grateful for your help in testing this - it's a very useful thing that I know off hand several groups wanted for a while.

**Comment by eriknstevenson** [comment]
Here is a quick rundown of information I would've found helpful in the wiki while figuring this out:
I think this issue can be closed now. Thanks again for the awesome support @vsoch.

## Deployment Builds

### Overview

A deployment build works similarly to a commit (automatic) build and indeed is also automatic, however it checks if the webhook came via a deployment commit first. The build only happens given a deployment. This kind of build is best suited for those that want more control (e.g., continuous integration and testing) before serving their finished containers, and strongly encouraged.

### Configuring your GitHub repository

Deployment builds occur when a deployment event is raised by GitHub and received by Singularity Hub. In order to cause a deployment event to be raised, you may follow the steps outlined [here](https://developer.github.com/v3/guides/automating-deployments-to-integrators/#sending-deployments-whenever-you-push-to-a-repository) to setup GitHub's Auto-Deployment integration for your repository. 

This will require a personal access token, which can be created by following the steps [here](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/).

The GitHub Auto-Deployment integration can be configured to only send the deployment event after receiving a success status from your CI server.

**Note**: this integration only triggers a deployment event when pushes are made to your repository's default branch (usually master).

### Troubleshooting

#### Deployment build not being triggered

Verify in your repository webhook settings that you have a Singularity Hub webhook that is configured to send Deployment events. This is enabled by default for newly-linked repositories, but it may be the case that you need to set it yourself if you linked the repository to Singularity Hub in the past.

More information on webhook events is available in GitHub's [webhook documentation](https://developer.github.com/webhooks/#events).

**Comment by vsoch** [comment]
Thanks @narrative ! I just updated the docs, and it's much better than before:

https://github.com/singularityhub/singularityhub.github.io/wiki/Deployment-Build

Closing!

**Comment by willprice** [comment]
@narrative could you share your Auto-Deployment configuration? I'm trying to set up a similar workflow but can't get the Auto-Deployment integration to trigger the Singularity Hub webhook.

Here's the workflow I'm after:
* Push new commit, status is set to `pending`
* Travis builds container
* Travis pushes container to Docker Hub
* Status of commit changes to `success`
* Auto-Deployment integration is triggered by change in commit status and creates deployment event
* Webhook is triggered by deployment event

It seems the Auto-Deployment integration fails to trigger by the commit status change/fails to create the deployment as I get a red triangle warning next to the integration in the integrations list that states "Last delivery was not successful. An exception occurred"

**Comment by eriknstevenson** [comment]
Hi @willprice,

The workflow you describe is the same one I was after. I did manage to get it working eventually so there is hope. I configured GitHub Auto-Deployment as follows:

- **GitHub token**: I used a token generated in `GitHub's Settings -> Developer Settings -> Personal access tokens`. Ensure the token you generate has all "repo" permissions enabled.
- **Environments**: I used "production"
- **Deploy on status**: checked
- **GitHub api url**: I left this blank
- **Active**: checked

Other things to verify:
- The container is configured for deployment builds on singularity hub.
- The singularity hub webhook in your github repository's settings has the "deployment" event checkbox checked and is active.

Hope that helps, and if there is any other information I can provide that might help, feel free to let me know.

**Comment by willprice** [comment]
Hi @narrative,

Thanks for the quick response. I've got more details on an ongoing thread on the Singularity mailing list: https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/C79YrwZHyPY

I've got the exact configuration you describe *except* for *all* the `repo` permissions enabled, I've got all the sub-repo options enabled, but not the top level `repo` one. I've just created a new token with everything checked to ensure its not a permissions error, but alas I still get the same error message on the integration page. 

**Integration settings**
![2018-02-04-224718_1003x1110_scrot](https://user-images.githubusercontent.com/966205/35783354-8270498c-09fd-11e8-8c2d-e09a391ef2b2.png)
---

**Access token permissions**
![token](https://user-images.githubusercontent.com/966205/35783357-97521042-09fd-11e8-8e89-21368e7f5d1f.png)
---

**Singularity hub webhook settings**
![2018-02-04-225006_989x1336_scrot](https://user-images.githubusercontent.com/966205/35783373-c556f886-09fd-11e8-8a1f-f74d6f9625bc.png)
