### ISSUE TITLE
Collection team management feature

### ISSUE THREAD

**Issue by gdolle** [singularityhub/singularityhub.github.io#87]
Currently it seems that only the owner of a github repository can add/manage a collection and can manually trigger builds on singularity hub.

It would be nice to add the possibility for owner to give access to github repository/organization team members via the shub interface (add a check box list in the settings to select which github team member can also manage the shub collection for example to trigger build)

**Comment by vsoch** [comment]
hey @gdolle ! This is a good idea! I'll add it as a feature for the next update.

**Comment by vsoch** [comment]
hey @gdolle ! I've decided that Singularity Registry server can have this team functionality, but Singularity Hub will remain to have "team" functionality through interaction with Github. I don't have the bandwidth to add another layer of checking permissions atm, so I'm sorry I can't do this for you.
