### ISSUE TITLE
Is debootstrap supported for xenial and other OS's

### ISSUE THREAD

**Issue by karlmutch** [singularityhub/singularityhub.github.io#88]
## Link to Container Collection Log, Build, or Collection (in that order)

https://github.com/karlmutch/singularity-images/blob/master/ubuntu/16.04/x86_64/cuda_base/Singularity

karlmutch/singularity-images

https://www.singularity-hub.org/containers/836/log

### Behavior when Building Locally

Successfully builds

### Error on Singularity Hub

ERROR Return Code 1: b'Using container recipe deffile: /tmp/tmpoi9zbjfr/ubuntu/16.04/x86_64/cuda_base/Singularity
Using container recipe deffile: Singularity
Sanitizing environment
\x1b[0mAdding base Singularity environment to container
E: No such script: /usr/share/debootstrap/scripts/xenial
\x1b[31mABORT: Aborting with RETVAL=255
\x1b(B\x1b[mCleaning up...
Cleaning up...

### What do you think is going on?

I think that the hub might not be able to support OS specific debootstrap style builds but cannot find a statement to this effect ?

**Comment by vsoch** [comment]
I think this was fixed, but you need to change your builder! Go into build settings and select the other builder, and give that a try.

**Comment by karlmutch** [comment]
I tried changing to the 2.4-dev builder which is the only alternative and the web page won't save the option.

**Comment by vsoch** [comment]
Is there an error message? Can you click save, then tell me what the blue bar at the top says? Or if you navigate away and then come back?

**Comment by vsoch** [comment]
Right now your builder is set to:

```
builder.specs
{'bucket_name': 'singularityhub',
 'builder_name': 'singularity-builder-2-4-50gb',
 'environment': 'gce'}
```

**Comment by karlmutch** [comment]
Looks like a UI confusion for me. When I click the drop down I see both a 2.4-dev and a 2.4.  If I select the 2.4-dev then the selection changes inside the drop down selection box.  Then when I click save I see the blue message noting that the -dev version is being used.  When I look back at the selection drop down box it reports I am using the non dev version.

**Comment by vsoch** [comment]
ok I can fix this up. For now rest assured that the message you see in blue is accurate to reflect your builder choice.

**Comment by vsoch** [comment]
here is your selection from my end:

```
{'bucket_name': 'singularityhub',
 'builder_name': 'singularity-builder-2-4-dev-50gb',
 'environment': 'gce'}
```

**Comment by karlmutch** [comment]
Thanks !  Appears to be more of a UI misunderstanding than anything.  Closing

**Comment by vsoch** [comment]
Thanks! And I just fixed the UI, so it shouldn't be an issue for future users. Thanks for catching the bug!
