### ISSUE TITLE
CRON schedule build feature

### ISSUE THREAD

**Issue by gdolle** [singularityhub/singularityhub.github.io#89]
It would be nice to have the possibility to schedule build directly from the interface.
For example to schedule nightly weekly builds.
That would add another automatic possibility aside to CI deployment and commit build.

**Comment by vsoch** [comment]
hey @gdolle ! What if you used the scheduler in Circle CI or travis, and then put Singularity Hub on "build on deployment" mode? That would accomplish what you seek, I think. I haven't tried out these new features for the CI, and am definitely interested to learn more.

**Comment by vsoch** [comment]
here we go! https://docs.travis-ci.com/user/cron-jobs/

**Comment by gdolle** [comment]
Ah! that can be a solution in my case. 
Actually have a repository for singularity recipes separated from the sources (so commits does not follow dev). 
We use buildkite CI mainly, but I think I can manage to do the cron via travis thanks for the idea! 👍

**Comment by vsoch** [comment]
I think we found a cool solution (and for note @gdolle I just used my first travis cron too!) I'm going to close the issue.
