### ISSUE TITLE
Container visualization with Krona?

### ISSUE THREAD

**Issue by GodloveD** [singularityhub/singularityhub.github.io#9]
Compare this:
https://singularity-hub.org/containers/114/view
to this:
https://hpc.nih.gov/examples/rnaseq.html

**Comment by vsoch** [comment]
others feedback appreciated! I am less inclined to want to use 3rd party visualizations (license issues, etc) and I'm also more a fan of simpler, less cluttered views of things. It does depend on the use case, of course. Thanks for the suggestions and feedback!

**Comment by GodloveD** [comment]
License issues may be a legit reason not to use this.  The license looks pretty laid back to me, but I'm no lawyer.

**Comment by vsoch** [comment]
hey @GodloveD do you still have strong feelings about this? I'm still liking the simple container tree better, and for the new shub I have added better dealing with overflow:

![image](https://user-images.githubusercontent.com/814322/27846641-e6a013f6-6106-11e7-8e5e-ff890856fc60.png)

The krona looks really cool, I'm just not convinced that it's easy to get information from (akin to a pie chart). Do you have some other ideas for new visualizations? For example, d3 v4 has been out a while - https://github.com/d3/d3/wiki/Gallery if you have a nutty idea that would be cool and useful for shub, I'd love to implement it! Maybe something to show users less structure, but some kind of content?

**Comment by GodloveD** [comment]
Hi @vsoch!  No I don't have strong feelings one way or the other about this.  I basically just got really excited about Krona when I first discovered it and thought it might be a good way to display all the things.  But in truth, if a user wants to display the contents of their container with Krona it is just a single command, so I don't know if it is necessary to do it via the shub.  Feel free to close.  :-)

**Comment by vsoch** [comment]
Okay, closing this issue! I am going to keep thinking about some new visualizations :) I hope you do too!
