### ISSUE TITLE
How to update descriptions for existing containers?

### ISSUE THREAD

**Issue by marcc-hpc** [singularityhub/singularityhub.github.io#92]
First off, great tool! We are eager to use this tool to support users at Johns Hopkins, and using Singularity Hub is very smooth.

http://singularity-hub.org/u/marcc-hpc -> collections
https://github.com/marcc-hpc/theano

Seems like the descriptions are cached on the initial container creation, or did we miss out on an interface to update the description?

**Comment by vsoch** [comment]
hey @marcc-hpc ! What happens is that the description is maintained for the overall collection to match the one one Github, but updates can only happen when you do a following interaction with Singularity Hub via the webhook. However for individual containers you can edit the descriptions in the interface, and they start with a default of a description matching the collection. For example, try going here http://singularity-hub.org/containers/924 and then given that you are the collection owner, you should be able to click on the description and edit it (note that the field is contenteditable). This is based on the idea that you would want to describe different containers subtle differences under a common collection. Once you edit the description for a container, it won't revert back to the original that was given to it (the collections).

For the collection description, we should be grabbing the description from the updated repo whenever a webhook is issued (e.g., you commit to trigger a build). For example, if repo is a dictionary with a field description, when we do this:

```
    # Update the collection repo
    collection.repo = repo
    collection.save()
```
Then the updated value that gets rendered in the links above comes from that:

```
{{ collection.repo.description }}
```
So your options are to:

1. make edits to container descriptions in the interface
2. get the updated description for the collection from the webhook

So if you have updated and then haven't interacted with the collection via the webhook, there is no way for the changed description to be known. Is this the case, or is there another bug we should look into?

**Comment by marcc-hpc** [comment]
Thanks! Option 1 is useful (the UI didn't make it clear that it something I could click)
My only remark is maybe having something to indicate we could 'edit' it.

Option 2 is very informative - this is better for longer-term use.

I would classify this as more information needed - no bugs from our POV.

-Kevin

**Comment by marcc-hpc** [comment]
I feel silly but I'm not able to do Option 1 and 'save', is that just me?

**Comment by vsoch** [comment]
Can you open the browser console (right click inspect and then go to console table) and tell me what you see when you click, write something, and then click away? Does it change but revert back (and this isn't saving?)

**Comment by marcc-hpc** [comment]
I don't see any action on the console (should I)?

In the element tab:
`<p id="the_description" contenteditable="true" onkeyup="saveDescription()" class="metric">Climate Data Operator jjj</p>`

I click away and see the new text, but starts over when leaving/refreshing.

Separately I saw 

```
paper-dashboard.js:39 Uncaught TypeError: Cannot read property 'outerHTML' of undefined
    at Object.initRightMenu (paper-dashboard.js:39)
    at HTMLDocument.<anonymous> (paper-dashboard.js:10)
    at l (jquery.min.js:4)
    at Object.fireWith [as resolveWith] (jquery.min.js:4)
    at Function.ready (jquery.min.js:4)
    at HTMLDocument.S (jquery.min.js:4)
```

I don't know if this is related or if this is pertinent.

**Comment by vsoch** [comment]
Collections descriptions are (manually) editable, closing issue also due to inactivity.
