### ISSUE TITLE
Change Github username

### ISSUE THREAD

**Issue by gipert** [singularityhub/singularityhub.github.io#93]
Is there anything that could go wrong or I should be aware of if I change my Github username? I did it yesterday and I'm still able to log in (however the old username persists on the Hub). Then how can I change also the Singularity Hub username?

**Comment by vsoch** [comment]
It should be updated in the webhook, although the displayed collection name wouldn't be. How were you able to change it? If it's just a few collections, then I can adjust the name in Singularity Hub for you.

**Comment by gipert** [comment]
I changed it on Github under "(Profile) Settings > Account > Change username"

> If it's just a few collections, then I can adjust the name in Singularity Hub for you.

Only one collection actually, it would be nice!

**Comment by vsoch** [comment]
ok definitely can! Which collection?

**Comment by gipert** [comment]
My (old) username was `luigipertoldi` and the only collection I have is `baseos-containers`.

**Comment by vsoch** [comment]
It looks like most of it changed automatically, which is good! The one issue that I anticipated was a database conflict changing the old container names to be updated, so I removed them seeing them rebuilt.

**Comment by gipert** [comment]
Thanks so much!

**Comment by adswa** [comment]
Hi @vsoch, would you be able to do the same thing for me? I updated my username from ``AdinaWagner`` to ``adswa`` yesterday (not thinking about any consequences for shub - sorry :/ ), and I would be grateful if I could link shub to my github profile again (I also can log in, but the account is still associated with my old gh-account). Its only one repository called ``BIDSsacc``. Thanks a lot in advance!

**Comment by vsoch** [comment]
yes of course! Let me take a look.

**Comment by vsoch** [comment]
okay found the one collection:

```python
 collection
<Collection: AdinaWagner/BIDSsacc>
```
Confirmed to be owned by `AdinaWagner`

```python
collection.owner
<User: AdinaWagner>
```
What I don't see is your username `adswa` - are you saying that when you log in, it uses your previous username? I'm hesitant to just change the username in case there are other changes - what I can do is assign the collection to myself, delete your account, and then you can log in again with the updated username. Would that work for you?

**Comment by vsoch** [comment]
Also @adswa note that I didn't physically do any changes - the username seemed to update for the previous user just by interacting with the collection. Have you tried this yet?

**Comment by adswa** [comment]
Oh! Thank you so much, @vsoch - interacting did indeed help! Sorry I if I caused trouble and thanks for getting back to me so quickly! :-)

**Comment by vsoch** [comment]
Haha, totally no worries! You should never feel badly for asking for help. I'm glad it worked out!
