### ISSUE TITLE
Perl module fails on Singularity Hub but not locally. 

### ISSUE THREAD

**Issue by tmozgach** [singularityhub/singularityhub.github.io#94]
## Link to Container Collection Log, Build, or Collection (in that order)

https://www.singularity-hub.org/containers/1108/log

### Behavior when Building Locally

Singularity version: 2.4.1-master.gf2d7795

Used the follosing command: singularity --debug build linuxbrew41.1.simg Sing4

--> Working on IO::All
Fetching http://www.cpan.org/authors/id/F/FR/FREW/IO-All-0.87.tar.gz ... OK
Configuring IO-All-0.87 ... OK
Building and testing IO-All-0.87 ... OK
Successfully installed IO-All-0.87

### Error on Singularity Hub

--> Working on IO::All
Fetching http://www.cpan.org/authors/id/F/FR/FREW/IO-All-0.87.tar.gz ... OK
Configuring IO-All-0.87 ... OK
Building and testing IO-All-0.87 ... ! Installing IO::All failed. See /home/linuxbrew/.cpanm/work/1513027986.782/build.log for details. Retry with --force to force install it.
FAIL

### What do you think is going on?

I can not debug and reach the log file on Singularity Hub.

**Comment by vsoch** [comment]
You should run the build using the secure build image, that is what singularity hub does. Here are the details of the host (and note installing the secure image branch from @cclerget)

https://github.com/singularityware/singularity-python/blob/master/singularity/build/scripts/singularity-prepare-instance.sh

Importantly, notice that we are doing `make secbuildimg`

Then you can either run it the way singularity hub does:

https://github.com/singularityware/singularity-python/blob/master/singularity/build/scripts/singularity-build-latest.sh

or skip the python wrapper and try just on your host (using the secure build installation)

```
sudo singularity build --isolated container.simg Singularity
```
I have a feeling something with the secure build is blocking a library from being accessed on the host, or there is some other missing dependency. We need one more level up from "it works on my host" because your host might have a different configuration than some other machine.

**Comment by cclerget** [comment]
@tmozgach @vsoch All build failed, try build with developement branch with/without --isolated option and 2.4.2 release.

```
Writing /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Bio/.packlist
-> OK
Successfully installed BioPerl-1.007002
Installing /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/.meta/BioPerl-1.007002/install.json
Installing /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/.meta/BioPerl-1.007002/MYMETA.json
27 distributions installed
+ false
ABORT: Aborting with RETVAL=255
Cleaning up...
```

Between @tmozgach you don't need to use su and sudo during build you are already root

**Comment by tmozgach** [comment]
@vsoch @cclerget Thank you for your help, I am pretty new in Singularity. I tried the following options:
* I installed the singularity using the above script:
``` 
cd /tmp && git clone -b feature-squashbuild-secbuild-2.4.1 https://github.com/cclerget/singularity.git &&
cd /tmp/singularity && ./autogen.sh && ./configure --prefix=/usr/local && make && sudo make install && sudo make secbuildimg
```
I build the container successfully by:
```
/usr/local/bin/singularity build --isolated baseTests3.simg Sing
```
* Tried the to install 2.4.2 release, with and without --isolated, development branch. I can not repeat error.

If I build the environment like in `singularity-prepare-instance.sh` based on basic Ubuntu:xenial, is that enough to mimic Singulary Hub behavior?

**Comment by vsoch** [comment]
I think you would need to have the same base operating system, and then install singularity as above, and then run the entire thing through singularity python (in the scripts linked above). I do believe the os is 16.04 LTS.

**Comment by tmozgach** [comment]
@vsoch I reached the detailed description of the error:
https://www.singularity-hub.org/containers/1132/log
```
# Failed test \'Checking for validity of sock No. 1\'
# at t/accept.t line 68.
```
One possible problem could be:
```
If the build system is missing localhost in /etc/hosts,
the test suite does this, and hangs forever at the end
```

Any thoughts?

**Comment by vsoch** [comment]
Pinging @cclerget on this- my gut is saying we could do some trick so the build works but the machine host should not have exposed localhost.

**Comment by tmozgach** [comment]
Hello @cclerget and @vsoch any new updates on this issue?

**Comment by vsoch** [comment]
We haven't heard yet from @cclerget , who is in charge of the secure builder image. I can't offer any additional insight.

**Comment by cclerget** [comment]
@tmozgach @vsoch Sorry for the delay. First error after looking at definition file https://github.com/bcgsc/orca/blob/master/Singularity.1, the following line https://github.com/bcgsc/orca/blob/a298ed7c22a33489c043d9b2adb58fc9e8b468c5/Singularity.1#L33, if you don't remove this line, build will always fail. After removing this line I successfully build container

For error:
`# Failed test \'Checking for validity of sock No. 1\'`

Secure build doesn't bind /etc/hosts in container, and /etc/hosts in container is empty. @vsoch I commit fix https://github.com/cclerget/singularity/commit/220f8e0ded97102d781967ada9e593d01b082bec hope it will fix the issue

**Comment by vsoch** [comment]
hey @tmozgach ! I'm working on a new builder for you right now! I'll let you know when he's ready to go with the updates from @cclerget .

**Comment by tmozgach** [comment]
@vsoch thank you very much! I appreciate that! =)

**Comment by vsoch** [comment]
okay @tmozgach the builder is ready, the image is called `singularity-builder-2-4-dev-50gb` please test it out (and note to remove the build line as suggested above) and let us know if it works.

**Comment by tmozgach** [comment]
@vsoch I tried 2 times to build image but now, it is the in running mode forever:
https://www.singularity-hub.org/collections/367

**Comment by vsoch** [comment]
Thanks for letting me know - I will shell in and debug this guy manually tomorrow.

**Comment by vsoch** [comment]
Just to make sure - you changed the builder image?

**Comment by tmozgach** [comment]
Yes

**Comment by vsoch** [comment]
Roger that!

**Comment by vsoch** [comment]
hey @tmozgach , making tiny progress! There was a library with a version that triggered a bug (not surprisingly, pandas) and I was able to fix and update the builder. Could you try a fresh build for the image again? The builder name is still `singularity-builder-2-4-dev-50gb`. I can't say this fix will 100% comb through all the knots in the hairball, but I think we are one step in the right direction. Thank you!

**Comment by tmozgach** [comment]
@vsoch It is still in the running mode. Thank you for your help to build this image!

**Comment by vsoch** [comment]
okay, the builder for some reason was still missing pandas, which is a bit confusing because I re-created and wiped the disk, so it must have some kind of timing / cache so that you still were able to use it. I'm again interactively logged into the server and trying to run it manually. If it works (or not) I'll go about re-creating the builder in a different way to hopefully fix this rather stupid bug.

**Comment by vsoch** [comment]
okay the build seems to work, are either of you @tmozgach or @cclerget familiar with this error:

```
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
# include 
^
compilation terminated.
```
it seems to be the one [in the log](https://www.singularity-hub.org/containers/1167/log) that ends the build and thus terminates.

**Comment by vsoch** [comment]
I'll hold off on creating the updated builder in case singularity needs something done to it.

**Comment by vsoch** [comment]
Just for reference, I think the recipe needed this fix: https://askubuntu.com/questions/470796/fatal-error-sys-cdefs-h-no-such-file-or-directory for a different architecture. Other than that, we resolved the issue in this thread, so closing!
