### ISSUE TITLE
How do I build containers housed within an organization's github?

### ISSUE THREAD

**Issue by jgrn307** [singularityhub/singularityhub.github.io#96]
Hi there -- I got my lab set up as an educational organization in github, but I can't seem to figure out how to import repositories listed under my organization rather than my personal github.  Ideas?

**Comment by vsoch** [comment]
Yeah! I'm afk so I can't give you direct links, but under your user settings there should be a tab section for Oauth apps, under which Singularity Hub is one. When you click on it, you should switch the toggle for your organization so it's green and save. Then you should be able to see the tepos there when you add a new container collection.

**Comment by vsoch** [comment]
Closing this issue, if you are still having trouble please let me know.
