### ISSUE TITLE
Docs about singularity and Drone io integration

### ISSUE THREAD

**Issue by henrykironde** [singularityhub/singularityhub.github.io#98]
Trying to get singularity and Drone io set up. Any help is welcome

**Comment by vsoch** [comment]
I'd be totally glad to help! How can I help?

**Comment by vsoch** [comment]
ping @henrykironde, how can I help?

**Comment by henrykironde** [comment]
I talked to a few folks and it turned out that they have not used Drone io and singularity. May be a new feature request to support Drone io like dockers

**Comment by vsoch** [comment]
If you could give me more details, it would be helpful. I don't know what drone.io is, or what an example use case looks like.

**Comment by henrykironde** [comment]
This is for reference, an article on drone.io works with dockers.
https://blog.maqpie.com/2017/03/21/build-and-deploy-applications-using-drone-ci-docker-and-ansible/

**Comment by vsoch** [comment]
If you are interested in singularity having integration with drone, this is an issue to bring up as an issue here https://github.com/singularityware/singularity/issues Having such functionality requires more advanced control of services that is not yet developed for Singularity, and that would be needed before any kind of discussion here. Thanks!

**Comment by henrykironde** [comment]
Thanks @vsoch I will create a new issue https://github.com/singularityware/singularity/issues

**Comment by vsoch** [comment]
Awesome thank you! There are a bunch of CI and general container tools that (once Singularity fits a formal specification and has controllers for services) will be really fun and useful to develop. I don't know a lot about drone.io but it looks clean and useful, and will definitely help out getting it up and running when Singularity proper is up to speed.
